### ISSUE TITLE
エフェクトのリバーブの項目がありますがリバーブも細かい調整出来るようにして欲しい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#101]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/132

## 2018.05.07 arigayas
https://twitter.com/ryota_yama/status/993267936021245952
『#ハヤえもんAppStoreでのやりとり
素晴らしい ★★★★★
投稿者: Y.K (助) – 2018年5月6日
音程をいじったりイコライザで音質をいじったり…あるいは耳コピにも使えたりと万能すぎるアプリ

因みに要望ですがエフェクトのリバーブの項目がありますが
リバーブも細かい調整が来たらな〜みたいに思うんですけど可能なのでしょうか』

『「万能すぎる」なんて言って頂けて、とっても嬉しいです！
リバーブはプリセットの種類を増やそうとしているのと、
パラメータのカスタマイズをできるようにしようと思ってます。
もうしばらくお待ちくださいね！』

**Comment by ryotayama** [comment]
対応済みなので、Closeします٩( ᐛ )و
