### ISSUE TITLE
 イコライザー画面で高速に操作するとクラッシュする

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#111]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/159

## 2018.05.18 ryutaro
高速にイコライザープリセットを削除しようとするとアプリケーションがクラッシュします

現象及び再現手法
https://youtu.be/iz03PIJDa3Y

**Comment by ryotayama** [comment]
#167 で対応済なのでCloseします٩( ᐛ )و
