### ISSUE TITLE
再生リスト画面の修正について

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#116]
iOS版の再生リスト画面にメニューボタンを増やしたら、ゴミゴミして見づらくなってしまったのでアイコン類を修正したい。
前バージョン⇒2.41

## 2018.05.21 ryutaro
全てのファイルにアイコンをつけるとごちゃごちゃしちゃうので、ローカルにあるファイルにはアイコンをつけずに
クラウド上にあるファイルだけにアイコンを付けるというのはどうでしょうか？

## 2018.05.22 arigayas
関連ある気がしたので #50 「iPhone機能追加：再生リストの画面」とリンクさせます

## 2018.05.22 arigayas
変更前のスクリーンショット
![resized_01_ddr1a3ovaaevypr](https://user-images.githubusercontent.com/11251874/40321877-7689159c-5d6b-11e8-836d-30f0dac2c8e2.jpg)

変更案のスクリーンショット
![resized_02_ddr1a3rvwaavam4](https://user-images.githubusercontent.com/11251874/40321909-8f600e4a-5d6b-11e8-9c51-e67df2aec25b.jpg)

変更案の説明スクリーンショット
![resized_03_ddr8k5ouqaahnm](https://user-images.githubusercontent.com/11251874/40322225-99825cf6-5d6c-11e8-8d71-808d043790ba.jpg)

## 2018.05.22 arigayas
うめぼし @UmeboshiKantaro
https://twitter.com/UmeboshiKantaro/status/998388431846756352
『あ、説明が不足してましたが、Dropbox マークはストリーミング再生が
わかるようにクラウドマークにしてみました。
将来的にGoogleドライブなんかに対応した時もこれでいけるかなと思います。
（Googleドライブ上のデータをストリーミング再生できるかはわからないけど笑）』

## 2018.05.24 ryotayama
対応中です٩( ᐛ )و*
ryutaroさんから「クラウド上にあるファイルだけにアイコン」という案もありましたが、いったんローカルもアイコン表示する方向で対応してみて、ユーザーサイドからの反応を見てみる事にします。

## 2018.05.26 ryotayama
ハヤえもんiOS版ver.2.43で対応済ー！٩( ᐛ )و

**Comment by arigayas** [comment]
引っ越し元
https://github.com/ryotayama/Hayaemon/issues/165
