### ISSUE TITLE
「ローカルに保存」の文言が分かりにくい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#121]
ハヤえもんiOS ver.2.66

https://twitter.com/recarendraven/status/1035819036632739842?s=21

すごい今更な疑問。

iOS版ハヤえもんの「ローカルに保存」の「ローカル」ってどこ？

https://twitter.com/recarendraven/status/1035819172763119616?s=21

端末なのは分かるさ。
どこに保存されるの？各App用保存エリア？

https://twitter.com/umeboshikantaro/status/1035819294485958656?s=21

アプリ内の領域って事らしいよ。ユーザーはアプリを介してしかアクセスできないらしい。

https://twitter.com/umeboshikantaro/status/1035819576930402305?s=21

確かに「ローカルに保存」って書き方分かりにくいかもね〜、issue登録しようかな？？

〜〜引用ここまで〜〜

これは最近りょーたさんのツイキャスで話していた気がします。（どの枠かは覚えてないですが…）
アプリごとに用意された領域があって、そこに保存されると説明していたような。

確かに、「ローカル」って表現はスマホ的ではないかもなぁと。
最低でも端末内なのはわかるけど、ユーザーがアプリ外から直接アクセスして開いたりできるわけではないので
「アプリ内に保存」
とかどうでしょうか？？
ご意見頂戴したいです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
対応しました！　バージョン2.92でリリース予定٩( ᐛ )و
