### ISSUE TITLE
再生リストの余白を長押した時にメニュー（アクションシート）が出てきてしまう

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#122]
ハヤえもんiOS ver.2.66

https://twitter.com/recarendraven/status/1036186780234477569?s=21
？？？

https://twitter.com/ryota_yama/status/1036187292421898240?s=21
なぜ下腹部あたりを指してしまったのか？？(*ノﾉ)

https://twitter.com/recarendraven/status/1036187416191619073?s=21
わかりません！何があったのでしょう！

https://twitter.com/ryota_yama/status/1036187686397046784?s=21
なにをしたら下腹部から吹き出しが出ちゃったか覚えてる？？(　ﾟдﾟ)

https://twitter.com/recarendraven/status/1036188138979250176?s=21
ただ、ロングタップしてただけなの(　ﾟдﾟ)

https://twitter.com/ryota_yama/status/1036193275864965120?s=21
サンキュー、あとで試してみる٩( ᐛ )و

https://twitter.com/umeboshikantaro/status/1036197254988587009?s=21
あ〜これ、iPhoneでも下の余白を長押しするとメニュー出てきたね…！

https://twitter.com/ryota_yama/status/1036202006170415104?s=21
ほんとだー！？(　ﾟдﾟ)
知らんかった！！

〜〜引用ここまで〜〜

再生リストの曲名のない余白部分を長押しすると、アクションシートが出てきてしまうのを見つけました。
iPadとiPhone両方で確認済みです。

曲名は出ませんが、再生リストの先頭のものが認識されているようです。

よろしくお願いします(´人･ω･｡)

**Comment by ryotayama** [comment]
対応しました！　ver.2.67でリリース予定です！
