### ISSUE TITLE
[再生中] 再生リストで曲名が長い場合、全て表示されないのでスクロールして欲しい 

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#130]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/179

## 2018.05.24 arigayas
https://twitter.com/UmeboshiKantaro/status/999560921876807680
『SEは狭いのですぐこうなります(*ﾉﾉ)
スクショはバージョン2.42』
![resized_se_2_42](https://user-images.githubusercontent.com/11251874/40472949-db97b14e-5f75-11e8-84b1-17811658020c.jpg)

曲名が長くなくてもスクロールした方が「再生中」だとわかりやすいかな？

## 2018.08.13 UmeboshiKantaro
追加情報ですφ(･ω･｡)

https://twitter.com/ryota_yama/status/1028868398581669888?s=21

ふむふむ、iOSデフォルトのミュージックアプリだと一覧画面ではスクロールされないけど、再生中画面ではスクロールされる感じだった！
ちなみにiOSのデフォルトコントロールに自動スクロール機能は無いから、ライブラリを探すか、自前で作るかだね！

![Image](https://i.imgur.com/dPfFVrn.jpg)

**Comment by KanzakiSaki** [comment]
https://twitter.com/UmeboshiKantaro/status/1074766203128668160
ハヤえもん、再生中の曲名とアーティスト名がスクロールして欲しさが強くなってきた… 横幅が収まってないやつだけでいいよね？？ 先頭まで来たら数秒止まるとか色々難しそうだなぁ…

![dupwkaovaaaerwl](https://user-images.githubusercontent.com/32741225/50355493-40151b80-0592-11e9-8ba8-4da7e5108f01.jpg)

![dupwkaou8aa0-r5](https://user-images.githubusercontent.com/32741225/50355501-44d9cf80-0592-11e9-9609-0ca2436d0baf.jpg)


スクロールする時、文字の両端にグラデーションついてるんだな…

![dupwk9cuyaen3mg](https://user-images.githubusercontent.com/32741225/50355510-4c00dd80-0592-11e9-8b95-070b8fef1f58.jpg)


おっけー、やりましょう٩( ᐛ )

**Comment by ryotayama** [comment]
対応しました！　バージョン3.00でリリース予定٩( ᐛ )و
