### ISSUE TITLE
再生リストの一時停止ステータスアイコンが表示されなくなる

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#14]
ハヤえもん iOS ver.2.64

https://twitter.com/umeboshikantaro/status/1032552840399544321?s=21

一時停止中にバックグラウンドにしたあと、一度下タブの画面を切り替えてから再生リスト画面に戻ると、一時停止中のアイコンが表示されなくなるのを見つけました！
一時停止→再生リスト以外の画面→バックグラウンド→再生リスト画面
の順番でもなります、ご確認お願いします🙏

↑のリンク先に動画がありますので参考まで🙏

**Comment by ryotayama** [comment]
#25 の対応をした結果、この不具合についても修正されました！
