### ISSUE TITLE
セーブ中のプログレスバーの下にキャンセルボタンがほしい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#150]
ハヤえもんiOS ver.2.66

https://twitter.com/satoupawapuro12/status/1038408043275280384?s=21
こんばんは。
iOS版ハヤえもんについて要望です。
セーブ中の画面で、プログレスバーの下にキャンセルボタンをつけて欲しいです。画面のどこかを押せばキャンセル可能ですが、ボタンをつけたらわかりやすくなると思います。
よろしくお願いします。
![Image](https://i.imgur.com/LfVbJzP.jpg)

うめちゃん、どう思うー？？
たしかにキャンセルボタンがあったほうがキャンセルできるってことが明示的かなぁ？？

キャンセルボタン私も欲しいです！ヾ(｡･ω･｡)ﾉ
issue登録しておきますね！ありがとうございます！🙏

ありがとー！！
‎よろしくお願いしまーす٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.92でリリース予定٩( ᐛ )و
