### ISSUE TITLE
曲追加の＋ボタンが消えることがある

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#151]
ハヤえもんiOS ver.2.66

https://twitter.com/chiimasuxu/status/1038423293131255809?s=21
ところでどういう方法があるのだろうとカメラロールから追加を押して、何も入れずにキャンセルするとプラスボタンが消えるバグ(？)が……( 'ω')……

https://twitter.com/ryota_yama/status/1038426225843134464?s=21
あらら……？？
試してみたけど消えない……！？
プラスボタンって、再生リストの右下の「＋」ってボタンのことだよね？？

https://twitter.com/chiimasuxu/status/1038429248287981569?s=21
判明しました！！
ipadminiで横向き固定の場合のみ発生するやつみたいですΣ(ﾟ□ﾟ)

https://twitter.com/ryota_yama/status/1038429419272949760?s=21
うぉー、ありがとう！！
確認します！！

**Comment by ryotayama** [comment]
対応しました！　ver.2.67でリリース予定です！
