### ISSUE TITLE
ABループを設定した状態でローカルに保存を選択すると落ちてしまうケースがある

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#152]
ハヤえもん ver.2.66

https://twitter.com/satoupawapuro12/status/1038969820610408448?s=21
こんにちは！
iOS版のハヤえもんについて、ABループで曲の1部を切り取ってローカルにエクスポートすると、アプリが落ちてしまう不具合が出てます。改善をよろしくお願いします。

あらら、ABループ設定からのローカルに保存メニューを選択って流れで確認してみたんですが落ちませんでした！！
曲によって起きる／起きないとか、何か条件ありそうですか？？

先にお話しするの忘れてました！発生したのはiPhone6s（iOS12のベータ版）でして、もう1台持っているiPhone7+（iOS11.4.1）では起きませんでした。もしかしたらiOSの問題かもしれませんね。失礼しました。

了解です！　ちょっと様子見してみますね！

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1088352361284681733
これってその後発生してないかなぁ？？

こんばんは。わざわざご心配いただきありがとうございます。おかげさまで今のところこの現象は起きていません。あの時はすみませんでした。

おぉ、良かった……！

**Comment by ryotayama** [comment]
本人がその後発生していないと言っている為、このIssueはCloseします！
