### ISSUE TITLE
エフェクトのオプション設定のアイコンがiマークなのが違和感がある

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#154]
![Image](https://i.imgur.com/g0Hxw5w.jpg)

ツイッターの鍵垢さんからの指摘です。

iはinformationの略で、設定ならsettingsなので違和感があるとの事。

りょーたさんいわく、最初はiOSのデフォルトのパーツを使っていたけど、今はiOSもAndroidもオリジナルで作っているとの事でした。

私はひょっとして＞マークだけでもいいのかも？と思ったけど、オンオフ切り替えそのものはチェックボックス形式にして、エフェクト名＋＞マークをタップでオプション設定画面でもいいかなーと。

エフェクト画面は並べ替えの要望（issue #134）もあるので、併せて検討する必要がありそうです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
対応済みの為、Closeします！
