### ISSUE TITLE
エフェクトの設定状態を保持にしていてもイコライザの音量が保持されない

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#155]
ハヤえもん ver.2.66

https://twitter.com/garahad_age3/status/1039511405240573955?s=21
ハヤえもんについて質問があるのですが、よろしいでしょうか？
イコライザのカスタマイズについてなんですが、"音量"のところだけエフェクト設定保持にしていても曲ごとに保持されていないように思うのですが…。
環境はiOS11.2.1です。

おぉ、バグってますね！
ありがとうございます、直しますね！

対応ありがとうございます！

**Comment by ryotayama** [comment]
対応しました！　ver.2.67でリリース予定です！
