### ISSUE TITLE
タイマー機能がほしい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#156]
ハヤえもん ver.2.66

https://twitter.com/8ine_natsu/status/1039176789174542336?s=21
はやえもん、タイマー機能とか付かないかな

https://twitter.com/ryota_yama/statuses/1037158848501506049
#ハヤえもんAppStoreでのやりとり
良アプリ ★★★★★
投稿者: たつをメンバー – 2018年8月31日
タイマー機能があったら更に良い

https://twitter.com/freedomobasan/statuses/1023949848200994816
@ryota_yama こんばんは。いつも楽しく使わせて頂いております。 
機能追加のお願いなのですが、スリープタイマーを付けて下さることはできませんでしょうか？寝落ちして朝起きたときにイヤホンからまだ音が流れていてびっくりしてしまうことがよくあり……😂😂
ご検討下さいますと幸いです！

https://twitter.com/ryota_yama/statuses/1016883783839039490
#ハヤえもんAppStoreでのやりとり
毎日使ってます ★★★★★
投稿者: リネトー – 2018年7月8日
本当に使いやすいです
スリープ機能もあれば助かります

https://twitter.com/ryota_yama/statuses/1006393419449622530
#ハヤえもんAppStoreでのやりとり
素晴らしい ★★★★★
投稿者: コイン欲しさにw – 2018年6月12日
ほんとに素晴らしいアプリをありがとうございます！
欲を言えばスリープタイマー機能を追加して頂ければ嬉しいです。

https://twitter.com/ryota_yama/statuses/1005659263635607552
#ハヤえもんAppStoreでのやりとり
最高👍✨ ★★★★★
投稿者: s.e01 – 2018年6月10日
文句ひとつなしです♪(๑ ́ᄇ`๑)

よ、欲を言えば、スリープタイマーがほすぃぃぃ！！( ˙◊˙ )

https://twitter.com/_kinakomoto/statuses/982055032919965696
ハヤえもんとかミュージックとか音楽アプリにタイマーでストップする機能ないかな…？夜寝るときに音楽聞くし_(:3｣∠)_

https://twitter.com/ryota_yama/statuses/959679739664334848
#ハヤえもんAppStoreでのやりとり
こういうアプリを待ってた！ ★★★★☆
投稿者: Mりんっち – 2018年1月25日
本当に大好きで重宝してるアプリです。
自分で編集した曲をアラームにできたらなって思います！(このアプリにアラーム機能とかつけて欲しい！)
期待も込めて星4つ☆☆☆☆

〜〜引用ここまで〜〜

オンタイマーとオフタイマーは別issueかな？？
見てる感じ、オフタイマー（スリープタイマー、おやすみタイマー）のが要望が多そうですね(*･ω･)ﾉ

現状では、iOS標準のタイマー機能を代わりに案内しています↓
https://twitter.com/ryota_yama/status/1039311467357466624?s=21
![Image](https://i.imgur.com/3WlE9iG.jpg)
iPhoneでしたら、実はiPhone純正の機能でスリープタイマーはできます！
iPhoneのタイマー機能の一番右のタブに「タイマー」というのがあって、そこのタイマー終了時というところを「再生停止」にすると音楽を止める事ができます。
ぜひぜひお試しくださいね！

同様の要望が増え次第、こちらのissueにコメント追加していきます(*･ω･)ﾉ

**Comment by arigayas** [comment]
issue登録するなら、オンタイマーとオフタイマーは別issueですね。

**Comment by KanzakiSaki** [comment]
https://twitter.com/umeboshikantaro/status/1067704222903296000?s=21

ナイトモードとスリープタイマーは左メニューからクイックアクセスできたらいいんじゃないかなーという妄想

![Image](https://i.imgur.com/FBAc3KH.jpg)

なにこれめっちゃいいじゃん٩( ᐛ )و
‎スリープタイマーと目覚ましは兼用ボタンかな…！？ ⁦‪

あー！そっか目覚ましもあるかぁ…！
画面悩ましいな…！

時計マークだから兼ねられそうな気はしたけど、そっから先の画面でどう分岐させるかってのが悩ましそうだよね…！

オンタイマーは、時刻指定でいいとして、
オフタイマーは、「何時間何分後に終了」とかのがいいのかな…？？

どうだろうね…！！
オフタイマーなるものを使ったことが無いや…！(*ノﾉ)

困ったときのiOS標準仕様準拠でいくなら、オフタイマーは時間指定で良さそう…！！

![Image](https://i.imgur.com/mhqFHbq.jpg)

そうだよね！ありがとう！！
ちょっと考えてみるら💪

**Comment by ny-yamana** [comment]
出来れば、自分のアレンジした音で朝起きられる、目覚まし機能を追加して頂ければ、と思います。
https://mobile.twitter.com/SanadamaruD/status/998492556806701056

**Comment by ny-yamana** [comment]
あったらいいな～と思うのがアラーム機能です
https://mobile.twitter.com/ryota_yama/status/1132754169599746048

**Comment by ny-yamana** [comment]
曲を再生する際、再生を少し遅らせることは出来ますか？
曲によって、すぐに再生される曲もあります。
ベース練習に使わせていただいていますが、再生をスタートして 3秒程度遅らせる事が出来れば助かります。
https://mobile.twitter.com/ryota_yama/status/1137130258853838849

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1138235409283002369?s=21
#ハヤえもんAppStoreでのやりとり
神アプリ
★★★★★
3日前 ぼぼぽんち
iOS | バージョン3.22 | 日本

こういうアプリを探していました！

アラームでなる機能がついたら、目覚ましに使えて便利です…（ハヤえもんにしか入っていない音楽があるので…）

**Comment by ryotayama** [comment]
https://twitter.com/corochar/status/1140027806375542785?s=21
Clipbox経由でハヤえもんにぶち込んだ『Haruka Happy Birthday』を一曲リピートしながら寝落ちをキメるとかいう猛者っぷりを最近発揮している タイマー終了時再生停止とかいう機能神やな

https://twitter.com/ryota_yama/status/1140033288783847424?s=21
‎愛用してくれててありがたい……！
‎ハヤえもん自体にもおやすみタイマー機能いずれ付けよーっと！٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/MeSObgkcB9CxWjk/status/1159903429558280192?s=20
ハヤえもん iOS ver.3.32 iOS 12.4 iPhone10,1 
機能の要望になりますが、いつも寝るときに音楽を聴きながら寝るのですが、音楽を何時までで切れるようにする、もしくは音楽を何分後に切れる、という機能が欲しいです。できれば検討お願いします。

**Comment by ryotayama** [comment]
https://twitter.com/mi_yabi2051/status/1118184731739164672?s=20
はじめまして！
機能要望です･･･！
｢タイマーをセットして時間になると音楽が止まる｣おやすみタイマーみたいな機能が欲しいです。
ご検討の程宜しくお願い致します🙏💦

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1148730822800756736?s=20
#ハヤえもんAppStoreでのやりとり
もしもできるなら…
★★★★★
アルルフォンス
いつも手頃に使わせていただいてます！
使い勝手もよくて文句なしなのですが、
もしも可能なら、タイマー機能を付けて自動的に音楽を止める昨日が欲しいです…！
寝ている時ずっと聴いてるわけにもいかないので自動的…

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1144801872735113216?s=20
#ハヤえもんAppStoreでのやりとり
提案
★★★★★
たくわん、
このままでも十分良いのですが設定した時間になったら切れるタイマー機能があったらもっと良いです！

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1135258805795639296?s=20
#ハヤえもんAppStoreでのやりとり
友達に勧めたい
★★★★★
今はダメ
超いいアプリです！
僕はよく音程を変えて聴いています！
曲調が変わって飽きないんですよね〜
ところで、リクエストといいますか、お願いがあります。
タイマー機能をつけて頂けないでしょうか？
どうかお願いします！

（追伸…

**Comment by ryotayama** [comment]
https://twitter.com/sky_12345678952/status/1037052115963662336?s=20
こんばんは！質問です。
スリープタイマーの機能はありますか？あれば教えていただきたいです！
なければ作っていただけると嬉しいです！

**Comment by ryotayama** [comment]
https://twitter.com/ymochi_camera/status/1089708018101510144?s=20
リクエストなんですが、おやすみタイマー的なモノがあればめちゃくちゃ嬉しいです！！！！

**Comment by ryotayama** [comment]
https://twitter.com/sugeeeeeeeyoo/status/1166015275709296642?s=20
ハヤえもん iOS ver.3.35 iOS 12.3.1 iPhone10,1 
できたらスリープタイマー的なのが欲しいな、、、、、、
おねがいします！！！

**Comment by ryotayama** [comment]
https://twitter.com/mikadai_ch_jp/status/1213193701700145152?s=20
ハヤえもん iOS ver.3.52 iOS 13.3 iPhone9,1 

機能拡張・修正をお願いします

・時間設定で曲を停止する機能拡張
(寝ながら聴くときに)

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7472
金のコイキング様
寝る時用に… ★4
〜分後に音楽が止まる
タイマー機能が欲しいです。

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7578
ゼリーコーヒー
使い勝手がいい。 ★4
スリープタイマーつけてくれたら星5

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7670
ねこひなこｗ
スリープタイマーを作って欲しいです…！ ★4
題名の通りなんですが、寝る時に使用したいので設定した時間になったら勝手に音楽が止まるっていう機能が欲しいです…！
それ以外本当に素晴らしいアプリだと思います！
どうか、検討よろしくお願いします！！

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7833
元祖草刈機
スリープタイマー ★4
めっちゃいいアプリで愛用してます！！！
しかし、最近スリープタイマーがあったらなぁって思うことがあり…

ぜひ新機能として追加して頂きたいです！
ご検討の程宜しくお願い致します！

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7876
とても使い勝手がいいです ★5
いつも愛用させてもらっています。様々な機能がついており大変使用しやすいです。個人的な意見として１つ要望があります。スリープタイマーの方を導入して頂けたらなと思っております。寝る時によく聞くのですが、「音楽を止め忘れて朝まで流れていた」ということが多々あります。なので是非スリープタイマーを導入して頂きたいです。宜しくお願い致します。

**Comment by ryotayama** [comment]
https://twitter.com/satomiku_taiko/status/1247399286934929408?s=20
これぜーんぶ実装してほしい！ものすごく使い勝手よくなりそう！

**Comment by ryotayama** [comment]
https://twitter.com/SiSn_moe2249/status/1263861916285329408?s=20
ハヤえもん iOS ver.3.73 iOS 13.4.1 iPhone10,3 
1時間したら勝手に止まる機能が欲しいです

**Comment by ryotayama** [comment]
https://twitter.com/math_1357/status/1243251470176116737?s=20
ハヤえもん iOS ver.3.68 iOS 13.3 iPhone12,1 
寝るときに睡眠導入として音楽をかけたいので、タイマー設定して自動で音楽が切れる機能とか追加可能ですか？
もしくはもう既に有れば使い方を教えていただけますでしょうか。

**Comment by ryotayama** [comment]
https://twitter.com/wayamoti2015/status/1266521890559942656?s=20
はやえもんに欲しい機能があるけど本体機能でも賄えちゃう、けど欲しいんだよね
なんというか、おやすみモード的な？
設定時間(ex.30分)を超えたら再生を自動的に止める機能(もしくはその逆で再生する機能)が欲しいかなぁ、、、

https://twitter.com/ryota_yama/status/1266539809167650821?s=20
いずれきっと対応します٩( ᐛ )و

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7962

らひまたたわゆま
素晴らしいです！ ★4
円盤化されずオフラインで聴けなかった曲がライブラリから追加できて感動しました！
私は普通に音楽再生のみとして使っているので
・再生リスト内の曲順が入れ替えられる
・スリープタイマー
の機能があると更にいいなあと思います！
これからも愛用します（＾ν＾）

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7962

ﾏｰｺﾏｰｺﾏｰｫ
凄くいい！！！ ★5
自分の好きな曲をカメラロールから入れられるのでまだCDを出していないアーティストの曲も聞けます🥰
凄く便利で毎日使わせていただいています！
オフラインでも聞けるのでいいですね！！
ひとつ言うとしたらスリープタイマー機能があれば寝る際も使えるかなーと思います😌
ほんとに素晴らしいアプリありがとうございます^ ^

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/7962

あなまはまさらたらざはやけなさやはてやは
超多機能で無料かつ高頻度アップデート ★5
機能が豊富すぎて自分では全てつかいこなせないくらいです。
寝る時にとても小さい音で音楽を流すのに使っています。
iPhoneはBluetoothイヤホンの最低音量がかなり大きいので…
イコライザーで音量をとても小さく出来るので助かっています！

欲を言いますと、再生停止するタイマー機能と、アラーム機能を付けて頂けると大変ありがたいです。
毎日決まった使い方をするならひとつのボタンを押すだけで全ての動作が設定されるようなものがあればより良いですかね。
あるボタンを押すと特定のプレイリストを何分間または何時までか再生し、何時間後または何時に特定のプレイリストを再生すると言った感じの…
その際それぞれイコライザーや音量も指定出来ればなお嬉しいです。
ややこしい機能ですが普段使いするなら寝る前の行動を大きく省略できます。

ぜひともよろしくお願い致します。
長文失礼しました。

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/8084
おやすみタイマーつけてほしい ★5
音楽聴きながら寝るんで…

**Comment by ryotayama** [comment]
http://hayaemon.jp/blog/archives/8084
スリープモード？がほしい ★5
つい先日友人に教えてもらいこのアプリに出会いました！ とっても使いやすいのですが、夜寝る時に再生して音楽を聴いているのでスリープモード(2時間後に自動で切れる、3時間後に切れるなど)がほしいなと感じました。 これからもたくさん使わせていただきます！

**Comment by ryotayama** [comment]
https://twitter.com/PCnohito/status/1293408916844326914?s=20
最強だ

**Comment by ryotayama** [comment]
対応済みのため、クローズします！

**Comment by KanzakiSaki** [comment]
https://twitter.com/hayato_no_12/status/1229074539834773510?s=21
ハヤえもん iOS ver.3.61 iOS 13.3.1 iPhone9,1 

スリープタイマー欲しい、、、、
もう既にあったらごめんなさい🙏

**Comment by KanzakiSaki** [comment]
https://twitter.com/raraayakatyu/status/1228370936044220416?s=21
ハヤえもん使ってるんだけど、アプリ単体でスリープタイマーとか曲が止まるまでの時間設定？みたいのできればいいのにな…っておもってる
あるのかもしれないけどやり方わからない←
