### ISSUE TITLE
ハヤえもんが立ち上がっていない状態で他のアプリから「ハヤえもんにコピー」を選んでも曲が追加されない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#162]
- iOS版ver.2.67

https://twitter.com/ryota_yama/status/1042566394754195457

#ハヤえもんAppStoreでのやりとり
修正してほしい ★★★☆☆
投稿者: １２３４５６７８９０ – 2018年9月9日
はやえもんを起動してない状態で他のアプリから曲を共有してはやえもんへ送っても見えないデータとなり、無駄な曲でキャッシュのような存在になります。
これを何度か繰り返すと見えないデータだらけで、はやえもんのアプリサイズがどんどん大きくなり、16GBの私のiPhoneじゃ厳しいです、どうか修正してほしいです。

はやえもんを起動した状態ならできるのですが…

起動した状態で共有すればいいじゃないかと思うところですが、起動をつい忘れてしまいます。

デベロッパの回答 – 2018年9月20日
１２３４５６７８９０さん、はじめまして！
ハヤえもん開発者のりょーたと申します！
おぉ、こちらの環境でも再現できましたので、修正しますね。
修正までしばらくお待ちくださいませ。
他にも何かお気付きの点などありましたら、いつでもご連絡くださいね。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

**Comment by KanzakiSaki** [comment]
これ私も遭遇していて、エクスポート1回目でハヤえもんを起動させた状態になり、
エクスポート2回目で成功すると、タイトルのおしりに「-1」とかって数字が付くので、裏にデータが残ってないか気になっていました…
その辺りも含めて見ていただけると嬉しいです🙏

**Comment by arigayas** [comment]
この状態に遭遇した端末用に「インポートに失敗したデータを整理する機能があったら良いのに」と思ったけど、
普通に再インストールした方が手っ取り早いのかな？

**Comment by ryotayama** [comment]
修正しました！　ver.2.73でリリース予定です！
