### ISSUE TITLE
夜間モードが欲しい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#166]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/203

## arigayas 2018.06.03
きっかけは結（むすび）＠musubi8enishiさんのツイート
https://twitter.com/musubi8enishi/status/1003124885311242240
『ハヤえもん、いつか背景の色を変えられるようになると嬉しいなあ。』

良太さんの引用RTによる返信ツイート
https://twitter.com/ryota_yama/status/1003126547044110336
『夜間モードは付けようと思ってるけど、
何でもカスタマイズできるような方向性にはわりと慎重な姿勢かな！』

## ryotayama 2018.08.04
https://twitter.com/muchi_shumi/status/1025555132786728960

機能追加の要望です!
Twitterのようにナイトモード?ダークモード?を追加してほしいです!

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1063659128797585408

#ハヤえもんAppStoreでのやりとり
良い！ ★★★★☆
投稿者: k.h12125 – 2018年11月12日
音楽の音程、速さなどを自由に変えることができて大変便利です。今後のアプデも期待してます

〇要望
- iPhoneとPCを繋いでいる際に、 iTunesのファイル共有をハヤえもんでもできるようにして欲しいです
- 暗い場所や寝る前etc…用にナイトモードが欲しいです!

デベロッパの回答 – 2018年11月17日
k.h12125さん、どーも！　りょーたです٩( ᐛ )و
とっても嬉しいコメント、ありがとうございます！
ファイル共有と夜間モード、検討してみますね！
他にも何かありましたら、いつでもご連絡くださいませ。

**Comment by ryotayama** [comment]
https://twitter.com/katuragi0616/status/1086256830920028160
ハヤえもんiOS、強いて言えば反転色？黒背景白文字スキンが実装されたら普通に課金してでも購入したい。

夜間モード的なやつなら実装予定です٩( ᐛ )و

それですそれそれ！ありがとうございます！待ってます！

**Comment by ryotayama** [comment]
https://twitter.com/zxcvbnm87615785/status/1082295898896388101
こんばんは！夜分遅く失礼します。いつもハヤえもんにお世話になってます🙇‍♂️🙇‍♂️ 機能要望なのですがダークモードなどあれば夜も使いやすくて良いと思うのですがどうでしょうか…？既に出ていたらすみません( ˊᵕˋ ;)💦

**Comment by ryotayama** [comment]
https://twitter.com/Yozwi/status/1069931866340225024
はやえもんさん、Twitterの夜間モードと同じような背景が黒で文字が白とか暗い中でも扱いやすいデザイン欲しいです…(›´ω`‹ )

**Comment by ryotayama** [comment]
https://twitter.com/shinpi_no_glass/status/1095398457177591808
テーマの色を変更できる機能を付けて欲しいです...

夜間モード的なやつですかね？？
いずれ対応しますね٩( ᐛ )و

そーです！
ありがとうございます、

**Comment by ny-yamana** [comment]
ダークモードとかきませんかね？
https://mobile.twitter.com/2ozhiazkmoftddq/status/1127854488742588417?s=21

**Comment by ny-yamana** [comment]
無難にダークモードなどを追加してみてはいかがでしょうか、夜などに使用する場合は白いUIは目に優しくないので昼と夜でUIの切り替えができると使いやすくなるかなと思います😄
https://mobile.twitter.com/hakuchuuumu/status/1135531697972211712

**Comment by ryotayama** [comment]
https://twitter.com/jirou1229/status/1138291747442683904?s=21
はやえもんもご愛用しています( ・∇・)❤︎

質問ですがはやえもんにはダークモードはありますか？

もしなければアップデートできないでしょうか？
絶対導入するかはわからないですが
YouTubeとかはダークモードが快適です！

**Comment by ryotayama** [comment]
https://twitter.com/tappi_otomad/status/1140469776717770752?s=21
ハヤえもんにもTwitterみたいにダークテーマとかあったらいいなぁ(ﾎﾞｿｯ)

**Comment by ryotayama** [comment]
https://twitter.com/twelpuru/status/1140546629792960512?s=21
白ベースは目が痛いのdのでああるといいなぁって自分も思います。

**Comment by ryotayama** [comment]
https://twitter.com/spa_taiko/status/1148446815261356032?s=21
こんにちは！
今、iOS13のベータ版を使っているのですが、ダークモードがものすごく使いやすくて気に入っています！ただ、他社製のアプリは個別に対応をしないとダメみたいでちょっと残念。
そこで、少し先の話になりますが、ハヤえもんはダークモードに対応する予定はありますか？

**Comment by ryotayama** [comment]
https://twitter.com/gamer_mikichan/status/1152364532469075968?s=20
実装されるの楽しみ😊

**Comment by ryotayama** [comment]
対応した！　まだこだわりきれてない部分もあるけど、それは別Issueを立てる方針にします！
バージョン3.30でリリース予定٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/Maddnes40227162/status/1092010822035886080?s=20
ハヤえもん、白くて眩しいので
「ナイトモード」的なの
ください。

**Comment by ryotayama** [comment]
https://twitter.com/renzou1216/status/1123228362804056064?s=20
こんばんは
普段ハヤえもんいじりながら夜寝ているんですが、明るさ最小にしてもやはり背景が白すぎて眼にきます
アプリ版Youtubeのダークテーマみたいに黒い背景に変更できたり、テーマ色を好みの色に変えられるようになったらいいなぁと思ってます

**Comment by ryotayama** [comment]
https://twitter.com/mokodate/status/1155046981850390528?s=20
ついに…おめでとうございます！そしてありがとうございます！

**Comment by ryotayama** [comment]
https://twitter.com/miyabi74427/status/1154283890929913856?s=20
え、物凄く助かります…。白い画面だと片頭痛が起きやすいので、課金してでも欲しかった機能です(´;ω;`)ダークモードはどうやって使えますか？リリースはまだっぽいですか？
