### ISSUE TITLE
再生リスト名の最大文字数を制限する

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#168]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/205

## UmeboshiKantaro 2018.06.03
再生リスト名の最大文字数が制限されていないため、制限を設ける。
最大40字が適切？

## arigayas 2018.06.03
今日はver.2.47で更新予定の再生リストの機能改善作業をしていた良太さんのスクリーンショットツイート
https://twitter.com/ryota_yama/status/1003232084289187840
![resized_longplaylistname_dewyqhav4aa3057](https://user-images.githubusercontent.com/11251874/40887162-1e062c48-677f-11e8-9a2c-039377c27e91.jpg)

もう一つ
https://twitter.com/ryota_yama/status/1003226596663177216
![resized_longplaylistname_dewtrlxvmaaxtmf](https://user-images.githubusercontent.com/11251874/40887201-d9a5ae7e-677f-11e8-8f6f-617f23048bd0.jpg)

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1082560248269889536
あとやっぱ地味に気になるのはバリデーションチェックなんよね…再生リスト名とか無限に文字数設定できちゃうし…（枠超えたら省略されるから意味ないけど

これ全体的にももちろんそうなんだけど、再生リスト名は優先順位高そうだよね……！
![dwj6tcku8aecpm6](https://user-images.githubusercontent.com/6075785/51031948-9e597b00-15e1-11e9-8a6f-bfd66659ce24.jpg)

あー確かにタブとして機能しなくなるねそれ💦
一覧があるからまだいいけど…やっぱ横幅いっぱいくらいまでが許容範囲かな？？

そうだねー、現状サポートしてる最小サイズであるiPhone SEで全角で打ち込んだ時に横幅が収まるぎりぎりを制限文字数にしよう٩( ᐛ )و

ひらがな19文字だった💦
半角だと28だけどどうかな？？

個人的には32がキリが良いなーって感じかな？
![dwl116wucaabyob](https://user-images.githubusercontent.com/6075785/51031973-b29d7800-15e1-11e9-8e6b-98d58b952741.jpg)
![dwl116wvsae2pga](https://user-images.githubusercontent.com/6075785/51031976-b5986880-15e1-11e9-8a00-d065484189ea.jpg)

iOSのテキストボックスの仕様を調べてみるけど、全角／半角を分けた指定はできないかもー！
調べてみるね👍

いや全角半角で分けたいわけじゃなくて、短すぎると困るケースも出てくると思って💦
世界一長いバンド名、43文字だった💦

「横幅はみ出しても仕方ないから、困らないようにした方がいいのでは？」って事かな？٩( ᐛ )و

私はSEもそうなんだけど、1番大きいiPadも同時に想定しないといけないと思っていて、SEだとスクロールが長くなってしまうけどiPadで見れるならそれの間を取るのがいいんじゃないかな？という感じかな？？

理解した٩( ᐛ )و
それなら、いったん32文字で組んでみてiPhone SEと最大サイズのiPadでスクショ見せるね👍

ありがとう🙏
iPhone SEは手元で確認するので、iPadだけお願いできるかな？？

おっけー👍

ほい！　iPad Pro(12.9インチ）での半角／全角それぞれの32文字٩( ᐛ )و
![dwl8fm2uyaaho09](https://user-images.githubusercontent.com/6075785/51032010-da8cdb80-15e1-11e9-9c90-14ad29a14fb3.png)
![dwl8g0ruwaazo5m](https://user-images.githubusercontent.com/6075785/51032012-dc569f00-15e1-11e9-9243-b052404ecf13.png)

はやっ！？！？Σ（・□・；）
ありがとー！！
やっぱiPad結構余裕あるんだね…！広い…！
一旦これで適用させてみたいけどどうかな？？

ありがとー、いいと思う👍
ちなみにiOS標準で文字数制限って機能はなくて、自前で組む感じらしい😱
これも部品化しとこーっと٩( ᐛ )و

自前で…組む…！？！？Σ（・□・；）

エラー表示はポップアップな感じがいいかな？？
入力欄の上に赤文字で出すとか色々ありそうだけど…

エラー表示というか32文字以上は入力できない感じにしよーかと思ってたけど、どーかなぁ？？

あ、入力そのものがね！
マジで勝手を忘れてた、そうしよう、その方がいいね！

いぇあ٩( ᐛ )و
自前で作るからどこまで自然にできるか分かんないけど、いったんやってみるね👍

**Comment by arigayas** [comment]
既に32文字以上の再生リスト名を作っていた場合、どうなりますか？

**Comment by ryotayama** [comment]
あ、ごめん返信できてなかった！
新たに再生リストに付けられる名前に対して、32文字のチェック機能を組み込もうと思ってる！

**Comment by ryotayama** [comment]
対応した！　バージョン3.01でリリース予定٩( ᐛ )و
