### ISSUE TITLE
不具合報告のリンクから遷移するツイート画面で各種情報が自動で補完されるようにしてほしい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#170]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/209

## ryotayama 2018.06.05
◆使用しているOS：iOS版
◆使用しているバージョン：2.47

◆引用元
https://twitter.com/ryota_yama/status/1003954614012600320

いったん出せるものは出してみたけど、もはや「ハヤえもんについて」じゃなくてユーザー側の情報を出してる。

とはいえ、ユーザーサポートするのにOSとか機種名があったらプラスになる。

これを解決するには、「ハヤえもんについて」画面にはハヤえもんの情報のみを出して、メニュー→不具合報告・機能→→要望が選ばれた時にツイート画面にハヤえもんのバージョン情報とユーザー側のOS／端末情報をツイート内容に含めるようにするのがいいんじゃないかと思うけどどうだろう？

もしこれで良ければ、いったん「ハヤえもんについて」画面には、バージョン: 2.47だけ出すようにして、不具合報告・機能要望→→に必要な情報を含めるようにするのは別issueで対応しよーかな！ #長い
うめちゃん、余裕のある時に意見ちょーだい @UmeboshiKantaro

![de7dyxyu0aa2nka](https://user-images.githubusercontent.com/6075785/40977093-f35f10c6-690a-11e8-9a03-954ccf7da06a.jpg)

https://twitter.com/UmeboshiKantaro/status/1003956945764532224
わー！ありがとうございます！！
確かに！この画面にはハヤえもんのバージョンのみにしましょう！
そんで「不具合報告・機能要望」メニューから

@ryota_yama ハヤえもん ver.2.47
端末情報：
iOS：

って感じで新規ツイート生成して、ユーザーサポートに繋げられると素敵っすね…！👍

https://twitter.com/arigayas/status/1003957187247419392

素敵！！ @ryota_yama

◆補足情報
#115 の対応中にでてきた改善点

## ryotayama 2018.06.06
◆メモ書き
≪OS名取得≫
NSProcessInfo.processInfo.operatingSystemVersionString
≪機種名取得≫　※「#include <sys/sysctl.h>」必要
size_t size;
sysctlbyname("hw.machine", NULL, &size, NULL, 0);
char *machine = malloc(size);
sysctlbyname("hw.machine", machine, &size, NULL, 0);
NSString *deviceName = [NSString stringWithCString:machine encoding:NSUTF8StringEncoding];
free(machine);

## ryotayama 2018.07.31
◆メモ書き
Twitter Kit SDKのサポート終了のお知らせ
https://blog.twitter.com/developer/ja_jp/topics/community/2018/TKSDK_tr.html

**Comment by ryotayama** [comment]
対応した！　バージョン3.27でリリース予定٩( ᐛ )و

**Comment by arigayas** [comment]
### 日本語
![D-NlgwOUIAEci7l](https://user-images.githubusercontent.com/11251874/60385724-39c6a580-9ac7-11e9-9dac-ec4aafb2b948.jpg)

### 英語
![resized_D-Ns9EyVAAE3nx8](https://user-images.githubusercontent.com/11251874/60385729-4c40df00-9ac7-11e9-9e98-2da4e3199c3f.jpg)

### 中国語
![resized_D-Ns9EwU8AET5CY](https://user-images.githubusercontent.com/11251874/60385731-5236c000-9ac7-11e9-91de-411d637f77b0.jpg)


機種名もあったら良いかもと思ったけどリプライ時に聞き出す感じにします？

**Comment by ryotayama** [comment]
ありさん、ありがとー！
機種名は最後のやつだよー！（iPhone9,2→iPhone 7 Plus）
ほんとは「iPhone 7 Plus」とかを表示したいけど、iOS純正の機能で取得できないから「iPhone9,2」ってやつをそのまま出してる！

◆iPhone iPad 端末での 一般名と内部名の対応表
https://qiita.com/YumaInaura/items/31838a72678fa09d7e19

**Comment by arigayas** [comment]
なるほど！
それなら開発者がわかれば良いので問題ないですね！
