### ISSUE TITLE
入力したテキストを一気に消す為の「×」ボタンがほしい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#171]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/210

## ryotayama 2018.06.06
◆使用しているOS：iOS版
◆使用しているバージョン：2.47

◆引用元
https://twitter.com/satoupawapuro12/status/1003987305131008002

こんばんは！
iOS版のハヤえもんについて要望です。
アーティスト名などを変更する際、写真のようなテキスト全部消しのバツボタンをつけてほしいです。
些細なことですが、よろしくお願いします。

## ryotayama 2018.07.19
対応しました。ver.2.60でリリース予定です٩( ᐛ )و

## arigayas 2018.07.19
スクリーンショットが欲しいです

## ryotayama 2018.07.19
こんな感じ₍₍ (ง*ᐛ)ว ⁾⁾
![Image](https://i.imgur.com/GNohd7Z.jpg)

## arigayas 2018.07.19
おお！Webサイトとかで見るやつだ！

**Comment by arigayas** [comment]
引っ越し元では対応済みだから閉じるね。
