### ISSUE TITLE
画面下部のタブメニューのデザインをリニューアルする

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#174]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/217

## UmeboshiKantaro 2018.06.07
画面下部の「再生リスト」や「コントロール」などのタブメニューを、#172 に合わせてデザインのリニューアルをはさみたいと思います。(*･ω･)ﾉ

## arigayas 2018.06.15
デザインのリニューアル前のスクリーンショットが記録として欲しいです。

## arigayas 2018.06.17
良太さんの[スクリーンショットツイート](https://twitter.com/ryota_yama/status/1008165011624083457)から切り抜きました。
### Ver. 2.50 スクリーンショット
![bottomcontroller_v250](https://user-images.githubusercontent.com/11251874/41506328-8e835e8c-7256-11e8-9d01-fba4e676c54f.png)

## arigayas 2018.06.17
関連するissue：#148

**Comment by ryotayama** [comment]
ver.2.76で対応しました！
![Image](https://i.imgur.com/AEIBrcm.jpg)
