### ISSUE TITLE
歌詞を表示させながら録音したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#179]
ハヤえもん ver.2.67

https://twitter.com/ryota_yama/statuses/952452782161764352
現状のハヤえもんに対する不満。歌詞を見ながら録音できない。録音したあとにミックスできない。Aメロ、Bメロとかで分けて録音したやつをミックスできない。録音した音をツイッターとかで共有できない。

〜〜

歌詞を見ながら録音できると、nanaやカラオケアプリみたいでいいですよね。(*･ω･)ﾉ

**Comment by KanzakiSaki** [comment]
https://twitter.com/ryota_yama/status/1052140489078595586?s=21
歌詞の表示中も録音できるように……と思ったんだけど、こういうUIである以上は、歌詞の表示画面で録音できるようにしたとしてもこのダイアログが歌詞を隠しちゃうから、そもそものUIを変えないといけないんじゃないか疑惑。
![Image](https://i.imgur.com/LM5LjQX.jpg)

nana はこんな感じだけど、録音ありきのアプリだからなぁ〜、、(；-ω-)ゞ
![Image](https://i.imgur.com/XHVpXcl.jpg)
![Image](https://i.imgur.com/h3TrFhN.jpg)
![Image](https://i.imgur.com/7CXXwip.jpg)

ふむふむ、再生中にせよ録音中にせよ、画面下部にバーがあるのは分かりやすいかもね〜。

音量レベルの表示と、親指でスライドして音量調節ができるの大事だよね…！

ふむふむ、また画面設計考えてくれるかな？？

考える考えるー！！👍

わーい、お願いしまーす！
じゃあ歌詞の表示画面に上部のコントロールボタンを追加ってのは後回しにしよーっと！

こんな感じで書いてみたけどもどうかな？？
←ボタンは、再生リスト画面のタブの←ボタンと同じ感じです！
![Image](https://i.imgur.com/su92lWn.jpg)

はやっ！？　すげぇ！！
めっちゃいいと思います！！
以下３段階に分けて実装しよーかな！！
①下部にバーを追加（停止ボタンと録音時間のみ）
②レベルメーターを追加
③音量スライダーを追加

ありがとう！！勝手にキャンセルボタン消しちゃったけど平気かな？？💦
あった方がいいのかなやっぱ…？？
停止したらどんどん録音してく感じになっちゃうよね💦
レコーダーアプリによっては、一時停止できたりもするしうーん。。

んー、録音停止したあと、名前を付けるダイアログでキャンセルできるから、いったん無しでいってみて、「いやいや、１タップでキャンセルしたいんです！」ってニーズが出てきたら検討するって感じでどーだろ！？
![Image](https://i.imgur.com/KsNjVWs.jpg)

おお、なるほどね！！
やっぱパーツ少なくスッキリさせたいもんなぁ…
これ今の画面に追加してるだけだからまだいいけど、この辺の再生中の表示とか出し始めたらもっと狭くなるよね(*ﾉﾉ)
https://github.com/ryotayama/Hayaemon/issues/55

iPhone SEとかは特に「狭い」って問題で悩むことになりそうな予感はするよねー！！

そうなんだよね💦
広告消してない人とか特に狭そう…！💦

あと下の再生リストとかコントロールとかのタブメニューつけちゃったけど、こっちはいけそうかな！？

いったんトライしてみまーす！！

ありがとう…！！🙏✨✨

**Comment by ryotayama** [comment]
バージョン2.88で歌詞をみながら録音できるようにしました！
機能追加が必要になった場合は、別途Issueを立てる事とし、このIssueはClose扱いにします٩( ᐛ )و
