### ISSUE TITLE
iOS版 の更新履歴一覧が欲しい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#183]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/221

## arigayas 2018.06.10
更新頻度が高いので早めに作らないと作業が徐々に大変になっていくと思います。

上部が新しい物になるように記述する。
_しかしこの作業やるとなると、作業漏れが起こりそうで怖いなぁ_

# 作例 

## Ver. 2.49  2018/6/10  

- 再生モードに「１曲のみ」というモードを追加
- 上部のコントロールアイコンリニューアル
- 再生リストのアイコン表示をリニューアル

## Ver. 2.48 2018/6/7

- メニューに「ハヤえもんについて」というメニューを追加
- 「追加」メニューを削除

## arigayas 2018.06.10
関連するissue： ryotayama/hayaemon/issues/222  ryotayama/hayaemon/issues/223

更新(リリース)した日付もあった方が良いかもですね。

**Comment by arigayas** [comment]
これを実現するには、もう作業量がスゴいことになっているから手動じゃ実現は難しそう・・・。

**Comment by arigayas** [comment]
もう作業量がスゴいことになっているから作るのは無理そうだからCloseでも良いかも・・・。

**Comment by ryotayama** [comment]
ありさん、ありがとー！
ひとまずCloseします！
