### ISSUE TITLE
iTunesのファイル共有機能に対応してほしい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#184]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/224

## ryotayama 2018.06.10
◆使用しているOS：iOS版
◆使用しているバージョン：2.49

◆引用元
https://twitter.com/ryota_yama/status/1005648897195118593
#ハヤえもんAppStoreでのやりとり
良い ★★★★☆
投稿者: k.h12125 – 2018年6月5日
音楽の音程、速さなどを自由に変えることができて大変便利です。カラオケの練習などに重宝しています。

<個人的な要望>
- iPhoneとPCを繋いでいる際に、 iTunesのファイル共有をハヤえもんでもできるようにして欲しいです。ハヤえもんのファイル内にある音楽ファイルをPCへ保存、またはPCからハヤえもんのファイルに音楽ファイルの追加をできるようにして頂けるとありがたいです。

<個人的な提案>
- "メニュー"は右側にある「・・・」で表示できるので、曲を長押しで"メニュー"を表示するのでは無く、iPhoneのホーム画面のアプリアイコンのように、長押ししながら曲の移動(曲順の並び替え)をできるようにすれば便利になるのではないでしょうか。
長押しが分からない方にも今までどおり、メニューから曲順の並び替えができるようにする形で。

長文失礼しました。
ご検討頂ければ幸いです。

デベロッパの回答 – 2018年6月10日
k.h12125さん、ありがとうございます！
りょーたです٩( ᐛ )و
ファイル共有に対応するべく調査してみますので、しばらくお待ちくださいね！
メニューについては、「・・・」メニューでできるようになりましたので、長押しに別の意味を持たせるのも確かにアリですね！
ちょっと考えてみます。
また何かありましたら、いつでも何でもご連絡くださいね。
ツイッター（@ryota_yama）でもサポートを行なっていますので、もし良かったら覗いてみてくださいませ。

**Comment by ryotayama** [comment]
https://twitter.com/satoupawapuro12/status/1073916109097558018
iPhoneのハヤえもん、あとはiTunesのファイル共有機能だけつけてくれれば最高なんだけどなー。

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1065258542880309249
Spoonに投稿するにあたって初めてiTunesのファイル共有
を使ったけど、確かにここにハヤえもんのアイコン並んでたら便利だなぁと思った。
なるほどなぁー。 


![itunes](https://user-images.githubusercontent.com/11251874/50065782-99302880-01fb-11e9-8339-9705ead534a4.jpg)

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1074346506520428544
#ハヤえもんAppStoreでのやりとり
さらに最高！ ★★★★★
投稿者: あーぼ2 – 2018年12月12日
先日ついに、ABループ画面での、経過時間表示が可能となり、感謝感激です！
…あとは、itunesでのファイル共有を待つばかりです。
開発速度が上がってきているとのこと、期待しておりますです。

デベロッパの回答 – 2018年12月17日
あーぼ2さん、どーも！　りょーたです٩( ᐛ )و
おぉ、再生位置機能よろこんでいただけて嬉しいです！
ファイル共有機能、対応しますね！
もうしばらくお待ちいただけると嬉しいです！
他にも気になる点などありましたら、いつでもご連絡くださいね。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

**Comment by ryotayama** [comment]
対応しました！　バージョン2.94でリリース予定٩( ᐛ )و

**Comment by arigayas** [comment]
_ツイートを観に行くのが面倒なので_
うめさんのツイートのコピーのコメントにスクリーンショットを転載しました。

**Comment by ryotayama** [comment]
ありさん、ありがとー！
#271 でアプリ内に残った不要ファイルと、iTunesの共有機能で追加されたファイルかの見分けがつかなかった為、いったんバージョン2.94のリリースからiTunesの共有機能は外す事にしました！
Reopenします！

**Comment by ryotayama** [comment]
対応しました！　バージョン3.00でリリース予定٩( ᐛ )و
