### ISSUE TITLE
 複数曲の削除、移動に対応してほしい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#185]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/226

## ryotayama 2018.06.10
◆使用しているOS：iOS版
◆使用しているバージョン：2.49

◆引用元
https://twitter.com/alxd_dororin5/status/1005737077411962880

iTunesの編集機能みたいに曲を複数選択して、まとめて削除や移動できるように私はしてほしい。

## UmeboshiKantaro 2018.07.08
曲名の長押しによってチェックボックスが表示される仕組みを採用できないか、画面を考えています(*･ω･)ﾉ

現在、Googleフォトがそのような仕様になっています。

↓長押し前の状態
![img_8197](https://user-images.githubusercontent.com/32741225/42415863-47c4a8f4-8299-11e8-9849-d0e9f8753a6d.PNG)

↓長押し後の状態
![img_8198](https://user-images.githubusercontent.com/32741225/42415867-674859d2-8299-11e8-82a2-a121dcd345be.PNG)

参考まで(*･ω･)ﾉ

## ryotayama 2018.07.08
いいね！　Googleフォトの操作性好き！

## UmeboshiKantaro 2018.07.08
複数選択ができるようになると、
「２曲同時再生機能が欲しい」 ryotayama/hayaemon/issues/296
にも対応できるかもしれないので、それも踏まえながら検討してみますね(*･ω･)ﾉ

**Comment by KanzakiSaki** [comment]
https://twitter.com/UmeboshiKantaro/status/1077743051060142080

昨日考えていた長押しで複数選択できる案。
激しく作りかけなのでもう少し練らないとな。。

![Image](https://i.imgur.com/FHZ1FJ8.jpg)

え、めっちゃいいじゃん٩( ᐛ )و

ありがとー！！アイコン小さかったから大きくした！
あと再生中との兼ね合いも考えてみたよ

![Image](https://i.imgur.com/CsiJlDs.jpg)

うぉー、ありがとーめっちゃ楽しみ٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1080081211903492097
複数曲のコピーに着手したいんだけど、めっちゃ時間かかりそうだから、次のアプデ申請してからにしたいんだよねー！
ちなみに、あれって長押しした時にあの画面になるんだよね？
曲順の並べ替えを押した時は今のまま？

曲の並べ替えを押した時…？？
あー並べ替えのマークつけっぱなしだったからか！！！！

複数選択の時は消したほうがいいかなこれ？？
なんかレビューコメントでも「複数曲の並べ替えができるようになりませんか？」ってきてて悩むんだよね…(´ω`；)

いったん消させてもらった方がだいぶ楽に実装できると思う٩( ᐛ )و
並べ替えはiOS標準の機能を使ってるんだけど、「複数選択された時の右側三本線スワイプ の動き」とかを自前で組もうと思うとだいぶパニクりそう……！

よし！！じゃあ消そう！！
複数選択、再生リスト間の移動は分かるけど、再生リスト内の並べ替えはなかなか難しいんだよなー

うんうん、おっけー！
複数選択の並べ替えって何……？ってとこからまず難しいよね……！

**Comment by arigayas** [comment]
複数選択の並べ替え　って

1. とりあえずハヤえもんをインストールしたから再生リストを作ってみる
2. 考えずにどんどん曲を追加した
3. 再生リストを聴いている内に追加した複数の先頭にある曲は先頭じゃなく中盤or終盤にあるのが良いなぁ
4. ん？曲の位置の変更って1曲ずつなの！？
5. よし、面倒くさいから開発者に要望を出そう

というシナリオが思い浮かびました。

**Comment by ryotayama** [comment]
対応しました！　バージョン2.98でリリース予定٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
@arigayas ありさん、コメントありがとー！
これ複数移動ができるようになったから、一旦まとめて別の再生リストに移動すれば、ひとまず実現できるかも！
コピーでも再生リストの1番下に追加されるから、いったんまとめてコピーして、いらないのをまとめて削除って方法もありそう！

**Comment by KanzakiSaki** [comment]
上で並べ替えなしで実装の流れがありますが、標準で搭載されていたのでそのまま残す方向になりましたので、経緯について記録しておきますね(*･ω･)ﾉ

https://twitter.com/umeboshikantaro/status/1081220468227502086?s=21
あとこれ複数選択モードだけど、並べ替えって標準で付いてるのひょっとして！？！？（今更

あー、ごめんそれ伝えるの忘れてた！
標準でついてて消す方が大変そうだったから残した！

スゲーそうなんだ！！Σ（・□・；）
作った画面完全に再現されててびびった、、全然消さなくていいと思う！！👍

**Comment by arigayas** [comment]
@UmeboshiKantaro さん
なるほどね～。
