### ISSUE TITLE
 イコライザの「なし」がわかりにくい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#198]
ハヤえもん ver.2.67

https://twitter.com/ryota_yama/status/1046655241574178816?s=21
#ハヤえもんAppStoreでのやりとり
イコライザ項目への修正提案 ★★★★☆
投稿者: どろすぅ – 2018年9月29日
イコライザ設定を選択した後、元に戻す
『 なし 』という項目が見当たらないため
イコライザ設定前の音に戻すことが出来ません。因みに、『 エフェクト 』設定では
『 なし 』という項目が存在しています。
ご検討の程宜しく御願いします。

デベロッパの回答 – 2018年10月1日
どろすぅさん、はじめまして！
ハヤえもん開発者のりょーたと申します！
イコライザのプリセットについては、「フラット」というものが「なし」にあたります。
「フラット」というメニューを選んでみてくださいね。
他にも不明点などありましたら、いつでも聞いてくださいませ。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

https://twitter.com/umeboshikantaro/status/1046722005024661505?s=21
アプリを起動した時に、エフェクト画面は「なし」が選択されている状態だけど、イコライザ画面では「フラット」は選択されていないので、それも理由の一つかな？？

![Image](https://i.imgur.com/Dq7A3e9.jpg)

![Image](https://i.imgur.com/qNAjOPT.jpg)

こんな感じ。
デフォルトで「フラット」が選択されていたら、気が付くかも。

あ、たしかに！
「フラット」って言葉に馴染みがないだけじゃなくて、そういうところにも原因があるかもね！

〜〜引用ここまで〜〜

とツイッターには書きましたが、iOSの標準ミュージックアプリに倣うとすると、「オフ」という表記もありかと。

![Image](https://i.imgur.com/o9AZ6F9.jpg)

ご意見頂戴したいです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
登録ありがとー！！
純正、「オフ」と「Flat」がある……！？

**Comment by KanzakiSaki** [comment]
え…！ホンマや！！Σ(ﾟДﾟ )

**Comment by ryotayama** [comment]
これ「Flat」よりは「オフ」の方が明示的なので「オフ」に変えようかと思うけど、イコライザは「オフ」、エフェクト画面は「なし」ってのが分かりづらいかなぁー、うーん！

**Comment by arigayas** [comment]
無効化　ってどうでしょうか？

**Comment by ryotayama** [comment]
なるほどなるほど！
うめちゃん的にはどうかなぁー？ @UmeboshiKantaro 
「オフ」で統一するのがもっとも認識相違が起きづらい気もしてきた！

**Comment by KanzakiSaki** [comment]
確かにイコライザを「オフ」にするなら、エフェクトの方も「なし」より「オフ」で合わせた方がいいかも！

**Comment by ryotayama** [comment]
ありがとー、イコライザ／エフェクトともに「オフ」で対応しまーす٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.92でリリース予定٩( ᐛ )و
