### ISSUE TITLE
保存後の再生／一時停止の挙動を統一したい 

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#199]
曲の再生中に保存をすると、保存中は再生が止まりますが、保存完了後に再生が自動的に再開されるものと一時停止になるものがあります。

「ローカルに保存」と「Dropboxに保存」の場合、保存が終わると自動で再生が再開されますが、
「カメラロールに保存」の場合、保存後は一時停止になります。

どちらかに合わせた方がいいかなと思いました(*･ω･)ﾉ

**Comment by ryotayama** [comment]
「長時間保存した後にいきなり再開してビックリする」というパターンを考慮し、一時停止で統一します！

**Comment by ryotayama** [comment]
対応しました！　ver.2.84でリリース予定です٩( ᐛ )و
