### ISSUE TITLE
パンの「−」「＋」ボタンを「L」と「R」に変更

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#2]
内部テスト版 バージョン2.65.1

![Image](https://i.imgur.com/nKbdInI.jpg)

エフェクトのオプション画面に「−」「＋」ボタンを新設しましたが、パンだけ違和感があるので「L」と「R」に変更してみるのはどうでしょう？？

**Comment by ryotayama** [comment]
対応した٩( ᐛ )و
![dllb_5bu0aae2d_](https://user-images.githubusercontent.com/6075785/44440679-1f4cb180-a604-11e8-8474-1f28e109ac83.jpg)

**Comment by ryotayama** [comment]
対応しました！　ver.2.65でリリース予定です٩( ᐛ )و
