### ISSUE TITLE
エフェクトをかけて保存した後、別のエフェクトをかけると効果が強くなってしまう

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#200]
エコーをかけて再生する→ローカルに保存する→再生したまま別のエコーをかける→エフェクトが強く聞こえる？？？？→停止してまた再生する→普通のエコーに戻る

こんな感じです。

保存されたデータは正しいエフェクトの状態になっています。

エコー、リバーブ、ディストーションで再現できました。
「カメラロールに保存」でもなります。

調査のほどよろしくお願いいたします(-人-)

**Comment by ryotayama** [comment]
修正しました！　ver.2.83でリリース予定です٩( ᐛ )و
