### ISSUE TITLE
ツイッターにシェアする時にURLが付かなくなった

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#206]
ハヤえもん ver.2.74

アップデートのポップアップから、ツイッターにシェアする時にアプリのURLが付かなくなりました！

![Image](https://i.imgur.com/IBSdQzM.jpg)

![Image](https://i.imgur.com/N7vTYWn.jpg)

バージョン自体は2.67→2.68を境に消えてしまっていますが、iOS12に上がったタイミングが怪しいかなとみています。

よろしくお願いします！

**Comment by ryotayama** [comment]
ver.2.77で対応済です！
