### ISSUE TITLE
再生リストを削除すると、再生リスト内の曲画面に切り替わってしまう

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#221]
ハヤえもん iOS ver.2.86

https://twitter.com/umeboshikantaro/status/1065858601749626880?s=21

再生リスト削除の挙動
最後の１つを消そうとしても消えないね…

再生リストを消すと曲の画面に行っちゃうのもイマイチだね…！

そう！それ今日気がついた（笑）

削除で曲画面に遷移しちゃうのは早めに直すとして、最後の１つを消した時の挙動はちょっと仕様を練った方が良さそうだね٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.90でリリース予定٩( ᐛ )و
