### ISSUE TITLE
「ローカルに保存」でアーティスト名が引き継がれない

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#222]
ハヤえもん iOS ver.2.88

![Image](https://i.imgur.com/TvCLjr8.jpg)

「保存／エクスポート」の「ローカルに保存」で
タイトルは引き継がれるのに、アーティスト名が引き継がれませんでした。

ご確認いただきたいです！
よろしくお願いします〜(*･ω･)ﾉ

**Comment by ryotayama** [comment]
修正しました！　バージョン2.92でリリース予定٩( ᐛ )و
