### ISSUE TITLE
録音バーを下からスライドして出てくるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#223]
ハヤえもん iOS ver.2.88

https://twitter.com/UmeboshiKantaro/status/1068318906710863872

録音バーも、じつは下からニョキッと出てくる感じにしたかったけど…笑

あ、ぜったいその方がいいじゃん！
‎また対応しよーっと٩( ᐛ )و

〜〜引用ここまで〜〜

録音バーを下からスライドして出てくるようにしたいです！
よろしくおねがいします〜！

![Image](https://i.imgur.com/ZsB5L8D.jpg)

**Comment by ryotayama** [comment]
対応しました！　バージョン2.90でリリース予定٩( ᐛ )و
