### ISSUE TITLE
「サイドギターの耳コピ」エフェクトを追加したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#224]
ハヤえもん iOS ver.2.89

https://twitter.com/ryota_yama/status/1070155412400291840?s=21
ハヤえもんAppStoreでのやりとり
せっかく見つけたのに… ★★☆☆☆
投稿者: ととたととむ – 2018年12月3日
ギターの耳コピがしたくて、入れたのに、「ベースの耳コピ」というモード(？)だけしか見つからなくて、困っています…
また、曲をURLから追加しようとすると、再生可能ではない、‎とか言われて、曲を読み込んでくれません…
‎せっかく見つけたアプリなので、アンインストールはしたくないです…
‎できるだけ早く改善してほしいです。

‎デベロッパの回答 – 2018年12月5日
‎ととたととむさん、はじめまして！
‎ハヤえもん開発者のりょーたです٩( ᐛ )و
‎ギターの耳コピは、耳コピしたいギターが左右どちらかに寄っているのであれば、エフェクト画面から「ボーカルキャンセル」、イコライザ画面から「ボーカル強調」というメニューを選んでみてください。
ボーカルキャンセルは中央の音を消す機能なので左右だけが残り、またギターと音域の似通っている「ボーカル強調」によってギターを聴き取りやすくする事ができます。

https://twitter.com/ryota_yama/status/1070160759651352576?s=21
「サイドギターの耳コピ」エフェクトは入れてもいいかなーと思った٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.98でリリース予定٩( ᐛ )و
