### ISSUE TITLE
一時停止状態でシークバーが正しく反応しない

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#225]
ハヤえもん iOS ver.2.89

https://twitter.com/umeboshikantaro/status/1070694108954415104?s=21
曲を途中まで流した時に、「前へ」をタップすると頭出しになると思うんだけど、一時停止の状態だとシークバーが反映されないのを発見した！（再生を押すとシークバーが動いて頭出し再生になる 

![Image](https://i.imgur.com/fQBJg4y.jpg)

**Comment by ryotayama** [comment]
対応しました！　バージョン2.90でリリース予定٩( ᐛ )و
