### ISSUE TITLE
「全曲リピート」選択時、先頭の曲で「前へ」を押した時に最後の曲に移るようにしたい 

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#228]
ハヤえもん iOS ver.2.90

「全曲リピート」選択時、先頭の曲で「前へ」を押した時に最後の曲に移らず、先頭の曲で止まったままになっています。
これを最後の曲に移るようにしたいです。

純正ミュージックアプリだとこの挙動になっていますので、よろしくお願いします(*･ω･)ﾉ

**Comment by ryotayama** [comment]
対応しました！　バージョン2.92でリリース予定٩( ᐛ )و
