### ISSUE TITLE
「リピート」や「シャッフル」がわかりにくいので、初期設定を「全曲リピート」にしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#229]
ハヤえもん iOS ver.2.90

https://twitter.com/gareki_nana_/statuses/1070691907049639937

すみません嘘吐きました←
1曲リピートしたくて、AとBを曲の初めと最後に置いて再生してました！
今やったら普通に時間進んでいきました！
またこれも再現出来たら連絡します！

おぉ、そっかそっか！
またなんか分かったら教えてくれたら嬉しいな！
ちなみに１曲リピートなら、ここからできたりもするよ٩( ᐛ )و

〜〜〜〜

https://twitter.com/nyohebya1/statuses/1071375267392708608
 
りょーたさん！はじめまして！
いつも楽しくハヤえもんを使わせていただいております。
そこでお願いなのですが、シャッフル再生機能を追加して欲しいです！
よろしくお願いします🤲

めるあさん、ご連絡ありがとうございます！
ハヤえもんを楽しんでくださって、嬉しいです٩( ᐛ )و
シャッフル機能、分かりづらくて申し訳ありません。
実は、ここを何回かタップするとシャッフルモードになります！

https://twitter.com/UmeboshiKantaro/statuses/1071377796549697538

前に提案出てたと思うけど初期設定をリピートかシャッフルにしておくのはどうだろう…？？

おぉ、そんな案出てたっけ……！
それいいね！
「全曲リピート」を初期設定にしよう٩( ᐛ )و

おお！？！？採用された…！！Σ(ﾟДﾟ )

「連続再生」よりも「全曲リピート」の方が確実に気づかれやすいもんね٩( ᐛ )و
リピート／シャッフルのリニューアルまでの暫定対応だけど、いいと思う！！

〜〜引用ここまで〜〜

現在再生モードは「連続再生」が初期設定になっていますが、リピートやシャッフルの存在がわかりにくいため、「全曲ループ」にしたいです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
対応しました！　ver.2.91でリリース予定٩( ᐛ )و
