### ISSUE TITLE
セーブ中のゲージの表示がおかしくなることがある

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#23]
https://twitter.com/m0usec0mputer/status/1033768840126062592?s=21

![Image](https://i.imgur.com/F3JPgsX.jpg)

逆再生を維持したまま「その他のアプリにエクスポート」するとセーブのゲージの挙動がバグることがあります
エクスポート自体は問題なく行えていますし、個人的に逆方向に振り切ったりするの面白くて笑えるので好きなんですが…
正常な動きではなかったので一応連絡しました🙇

わお、ありがとうございます٩( ᐛ )و
‎これヤバいですね(*ノﾉ)笑
‎助かります！！

**Comment by ryotayama** [comment]
対応しました！　ver.2.66でリリース予定です٩( ᐛ )و
