### ISSUE TITLE
「エフェクトの設定状態を保持」が伝わりにくいため、「各画面の設定を保持」に変更したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#230]
ハヤえもん iOS ver.2.90

「エフェクトの設定状態を保持」が伝わりにくいため、「各画面の設定を保持」に変更したい

https://twitter.com/maman_45cho/status/1068128520704937985?s=21
いつもお世話になっております
PC版の頃からの愛用者です
曲(もしくは再生リスト)ごとのループ設定を記憶させる機能など検討いただけないでしょうか
反復練習したい部分は大抵決まっているので、その度に設定するのがなかなか…

ご連絡ありがとうございます٩( ᐛ )و
‎再生リスト画面の「・・・」メニューに「エフェクトの設定状態を保持」っていうメニューがあるので、それで記憶させる事ができますよ！
![Image](https://i.imgur.com/kAfawdu.jpg)

https://twitter.com/umeboshikantaro/status/1068129598372700160?s=21
これって適用範囲はABループ、イコライザ、エフェクトの３つでしたっけ？？
名称を考え直す必要があるかな？？

ABループ、マーカー再生、イコライザ、エフェクトだね！！٩( ᐛ )و
‎たしかに「エフェクト」の言葉には当てはまらないぐらい色々保持してる……！！

あ、コントロールもか…！
全部！？！？

あ、たしかに…！！

「エフェクトの」→「曲の」の方がいいのかな？？分かりにくいか？？

「曲の設定状態を保持」
うーん？？
「各種パラメータの設定状態を保持」
うーん……？？
「曲の各種設定状態を保持」
うーん…………？？
「現在の設定状態を保持」
うーん………………？？

2番目のやつ文字数やばいねｗｗ

ヤバイよねww
「曲の設定状態を保持」は曲を設定するわけじゃないとこがなんか引っかかるんだよねー。
あ、「曲の再生状態を保持」か！？

もういっそのこと「設定状態を保持」だけにする…？？？？

再生リスト画面のメニューで「設定状態を保持」って出てきたら、自分なら再生リスト絡みの設定状態と思っちゃう気がするなぁ…！　なかなか難しい！

「各メニューの設定を保持」とかは？？

各メニュー……「メニュー」は左からと下から出てくるやつのイメージがついちゃってるなぁ。。それを活かすなら「各画面の設定を保持」はどーかなぁ？？

確かに左上に「メニュー」ってはっきり書いてあるもんね！
お！「各画面」でも伝わる！？！？それも考えた！

「各画面」なら、再生リスト／コントロール／ループ／イコライザ／エフェクトの各画面の事を指してるんだなって個人的にはだいぶ連想しやすいよ٩( ᐛ )و

一旦それで対応してみる？？また問い合わせ来たらその時に対応しようか…！同じような問い合わせ結構多かったもんなぁ…

よしそれでいこー٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.92でリリース予定٩( ᐛ )و
