### ISSUE TITLE
再生リスト画面の奇数行と偶数行の色分けをなくしたい 

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#238]
ハヤえもん iOS ver.2.91

https://twitter.com/siwo951_submain/status/1072129112066580481?s=21
今思えばハヤえもんの初期リリース版見てみたい

https://twitter.com/ryota_yama/status/1072255155473592320?s=21
再生リスト画面٩( ᐛ )و
https://twitter.com/ryota_yama/status/381724645277184000?s=21
![Image](https://i.imgur.com/NmgnbxI.jpg)

https://twitter.com/umeboshikantaro/status/1072296972168650752?s=21
え！ああー！？！？
曲一覧の画面なんで奇数行と偶数行で色分けされてんだろ？？って思っていたけど、これならしっくりくるなぁ…！！

そう、これ当時のiTunes Storeのデザインをそのまま踏襲したんだよね！！
‎色分けいらなければいつでも変えれるよー٩( ᐛ )و

そういう事かぁ…！！！！これ見てほんとビックリした！！
今のデザインなら、色分けない方が自然かもなぁ…！イコライザとかエフェクト画面も色分けしてないし…

おっけー、対応するね٩( ᐛ )و

〜〜引用ここまで〜〜

再生リストの曲一覧画面と再生リスト一覧画面が奇数行と偶数行で色分けされていますが、現行のデザインと合わなくなってきたため、この色分けをなくしたいです。
（なかなか歴史を感じる興味深い資料でした！ありがとうございます！）

**Comment by ryotayama** [comment]
対応しました！　バージョン2.92でリリース予定٩( ᐛ )و
