### ISSUE TITLE
並べ替え中は下部のタブバーを非表示にしたい 

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#239]
https://twitter.com/umeboshikantaro/status/1070230196626763776?s=21

曲順や再生リストの並べ替えモードは、歌詞やエフェクトと違って、他の画面に遷移できなくしてあげたほうが、視認性が良くなって親切なのかなーなどと思っていますが、どうかな…！？ 
![Image](https://i.imgur.com/xqLUjPt.jpg)

再生中も並べ替えができるので、再生バーが追加となると、かなり狭くなるのでできる限り広げてあげたいなーという。。
https://twitter.com/umeboshikantaro/status/1069556725290659840?s=21

おぉ、いいじゃん٩( ᐛ )و
‎なんとなく再生リスト画面をそういう仕様にするなら、同じ見た目をしてるイコライザの並べ替えも合わせたいと思っちゃうけど、そうでもない？？

あ！イコライザも並べ替えできるの忘れてた💦
そっちも同じにしたいです！！🙏

あ、やっぱそうだよね！
‎それでいこー٩( ᐛ )و

**Comment by arigayas** [comment]
(念のために)イコライザの画面のissueも登録よろしくお願いいたします。

**Comment by ryotayama** [comment]
ありさん、ありがとー！
イコライザも同時対応しちゃうからIssue登録はいらないよー！

**Comment by ryotayama** [comment]
@UmeboshiKantaro 
うめちゃんに確認です٩( ᐛ )و
画像を見る限りタブバーの話だけでは無く、「再生リスト名」が表示される箇所も非表示にする仕様で良いかなぁ？？

**Comment by KanzakiSaki** [comment]
あっそれ書くの忘れてた…！！再生リスト名も非表示になるようにしたいです！
別issue対応？？

**Comment by ryotayama** [comment]
一気にやるから全部このIssueで大丈夫٩( ᐛ )و

**Comment by ryotayama** [comment]
うめちゃん、これって趣旨を考えるとイコライザ画面の並べ替え中はプリセット／カスタマイズのスイッチも非表示にした方が良いのかなぁ？？ @UmeboshiKantaro

**Comment by KanzakiSaki** [comment]
ああー！確かにそうだね…！
並べ替え中にカスタマイズ画面行かないもんね…！
もし難しいようなら分けて対応でも全然大丈夫です！🙏

**Comment by ryotayama** [comment]
よし、ありさんごめん！　前言撤回！
やっぱりIssue分割します！笑　@arigayas

**Comment by ryotayama** [comment]
という事で、このIssueでは再生リスト画面のみを対応します٩( ᐛ )و

下部のタブバー及び、上部の「再生リスト名」のエリアを非表示にします！

**Comment by arigayas** [comment]
ラジャーw

**Comment by ryotayama** [comment]
対応しました！　バージョン2.93でリリース予定٩( ᐛ )و
