### ISSUE TITLE
シークバーを動かすとタイトルとアーティスト名の座標がずれる

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#244]
ハヤえもん iOS ver.2.91

https://twitter.com/umeboshikantaro/status/1072457900927389697?s=21
ああー！？！？バグ見つけました！！シークバー動かすとタイトルとアーティスト名の座標がおかしくなります…！！ 

おぉ、ありがとー٩( ᐛ )و
‎直すねー！！

**Comment by KanzakiSaki** [comment]
修正済みです！

https://twitter.com/ryota_yama/status/1072531590692175872?s=21
ハヤえもんiOS開発版、再生中画面のタイトル位置がおかしくなる事があった不具合を直した٩( ᐛ )و

**Comment by arigayas** [comment]
どのissueに該当するんでしょうか？それともissue登録されてない物でした？

**Comment by ryotayama** [comment]
対応したあとに後追いでうめちゃんがIssue登録してくれたってだけだよー٩( ᐛ )و

**Comment by arigayas** [comment]
なるほど。

**Comment by KanzakiSaki** [comment]
ごめん、ツイッターで「issue登録します！」って私が言って、issue登録よりも先に修正が終わってたのw

**Comment by arigayas** [comment]
良太さんが有能すぎたパターンでしたかww
