### ISSUE TITLE
イコライザの「デフォルトに戻す」の範囲が分かりにくい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#245]
ハヤえもん iOS ver.2.91

https://twitter.com/umeboshikantaro/status/1072486625794498561?s=21
あー開発版のバグ見つけました！！
フラットがオフに名称変更されたはずがされてないのと、
「各画面の設定を保持」した状態で再起動すると、イコライザもエフェクトも何も選択されていない…！？スクショの曲は「中音カット（最弱）」で保持してます…！

うめちゃん、ありがとー٩( ᐛ )و
‎まず１点目！
‎うめちゃんは「中音カット（最弱）」の並び順を変えた都合上、「プリセットを変更してる」って扱いになって、プリセット名と順番が全て保存されてる。
‎「デフォルトに戻す」をすればオフになるよ。

そうなのかぁー！！💦
これ使った事なかったけど名称とか順番も全部デフォルトに戻るのか…！範囲カスタマイズの中身だけかと思ってた…ありがとう…_(:3 」∠)_

〜〜引用ここまで〜〜

デフォルトに戻るのはプリセットの「カスタマイズ」の中身だけかなと思ってましたが、すべてのプリセットが初期化されるんですね…！

現行の「デフォルトに戻す」を「すべてのプリセットを初期化」に改めつつ、
新しく「プリセットの設定を初期化」という単体で初期化されるやつがほしい気がします。。

あと両方ともメニューを赤文字にした方がいいかも。。

ご意見頂戴したいです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
ありがとー、すごく良いと思う٩( ᐛ )و

**Comment by ryotayama** [comment]
Issueを２つに分けましたー！
このIssueでは、現行の「デフォルトに戻す」を「すべてのプリセットを初期化」に変更し、赤文字にするという部分を対応します٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.93でリリース予定٩( ᐛ )و
