### ISSUE TITLE
一時停止中、バックグラウンドにしてから再生ボタンを押すと次の曲が再生されてしまう 

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#25]
ハヤえもんiOS ver.2.65

https://twitter.com/piece_1120/status/1034004372475113473?s=21

ハヤえもん一回停止して、
ホームボタン押して閉じて
また再生したら次の曲に変わっちゃうようになってる...どうしたら...

https://twitter.com/umeboshikantaro/status/1034018435632488449?s=21

失礼いたします、ハヤえもんデザイナーのうめぼしと申します！
確認しましたが、これはバグですね💦
対応しますので、お待ちいただければ幸いです！🙏
一時停止中の曲名をタップすると、停止地点から再生を再開することができますので、対応までの間お使いただければと思います💦

〜〜引用ここまで〜〜

↑に動画を付けました。
一時停止後に一度バックグラウンドにした後で、上の▶︎で再生を再開しようとすると、次の曲が再生されてしまいます。
ご確認お願いします(´人･ω･｡)

**Comment by ryotayama** [comment]
対応しました！　ver.2.66でリリース予定です！
