### ISSUE TITLE
アートワークを自分で設定できるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#256]
ハヤえもん iOS ver.2.91

https://twitter.com/ryota_yama/status/1072465119844728834
ハヤえもんでアートワーク出るようになったけど、自分で画像設定はできない感じかな

https://twitter.com/ryota_yama/status/1072464733759029250
アートワークがカメラロールの画像に変更できるようになれば…

**Comment by KanzakiSaki** [comment]
https://twitter.com/honeydropkuu/status/1073434417761202177?s=21
いつも開発お疲れ様です。
アートワーク実装わーい！！(((o(*ﾟ▽ﾟ*)o)))ってなって設定してみよーってやろうとしたんですけど、これってiTunesの曲しか対応してないってことですかね…。自分で好きにアートワーク画像設定したいな…なんて（；^ω^）💦
要望ばっかでごめんなさい🙏

**Comment by KanzakiSaki** [comment]
音符マークの画像をタップしたら、アクションシートで「カメラロールから画像を選択」みたいな感じかなあ？？

**Comment by KanzakiSaki** [comment]
https://twitter.com/gamer_mikichan/status/1076606826194526208?s=21
ハヤえもんっていうアプリのアップデートがきたんだけど、アートワークっていうのがよくわからない…
自分の好きな画像とかって使えるのかな…？

**Comment by KanzakiSaki** [comment]
https://twitter.com/zqks9qpgkkxz471/status/1077428165734068224?s=21
アルバムに写真を変えるように出来たらいいです。お願いします。

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1080834450026418176
#ハヤえもんAppStoreでのやりとり
いつも愛用しています!! ★★★★★
投稿者: (･ω･*やひこ – 2019年1月3日
ちゃんと保存できるし、オフラインでも聞けるし、ナイスとしか言いようがありません…!!
ほんっとうにいつもありがとうございます<(_ _)>これからも使わせていただきます!!
そこでなのですが、1つ機能要望をしてもよろしいでしょうか…?曲を聞く時に下に曲目が表示されて一時停止とかができるバーが現れると思うのですが、あそこに表示される灰色の音符マークを好きなイラストに変更することなどはできるのでしょうか?もしできるのであれば、曲のジャンル事にわかりやすくしたいなーと思ったのですが…!!(長文失礼しました!!ひとつの参考程度になれば…!!と思っただけなのでそこまで気にしなくても大丈夫です!!)

**Comment by ryotayama** [comment]
https://twitter.com/nanakanen/status/1081569620819996672
私が1人目だと思います…(超小声)

**Comment by ryotayama** [comment]
DMでも何人か要望を出してくれてるので、リリース時の連絡を忘れない事。

**Comment by KanzakiSaki** [comment]
https://twitter.com/7777777n77/statuses/1080314180610121728
アプリいつも使わせてもらってます！
アートワークを自分で設定できるようになりませんか？？

https://twitter.com/MINAMI_VENUSs/statuses/1081504804164136960
こんばんは！いつもハヤえもんを愛用しております(*´ω｀*)
機能要望をお願いしたいのですが、音楽をかけた時に表示されるジャケットの写真をカメラロールから選べるようにすることは可能でしょうか？
ご検討の程、よろしくお願い致します！

**Comment by ryotayama** [comment]
対応しました！　バージョン2.99でリリース予定٩( ᐛ )و
