### ISSUE TITLE
再生中の再生リストタブが分かりにくい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#259]
ハヤえもん iOS ver.2.92

https://twitter.com/umeboshikantaro/status/1073440142348627969?s=21

これ、表示してる再生リストはタブの色が変わってるからわかるけど、実際に再生してる再生リストは分からんのよなー、、
再生中のリストタブも青い背景にした方がええんかな？？ 

![Image](https://i.imgur.com/X8GiLEj.jpg)

おぉ、どうだろー！
‎選択中と再生中の概念がパッと見分かりづらくなりそうな気もするけど、いったんやってみよーか？？٩( ᐛ )و

表示中と再生中が同じリストの場合、リスト名を太字にしたらどうかなー？？って思って…紛らわしいかなぁ？？

軽く実装してみよーと思ったらわりと難易度高かったから、またやってみるねー٩( ᐛ )و

わぁ！そうだよね！issue登録しとくー！👍

**Comment by ryotayama** [comment]
対応しました！　バージョン2.97でリリース予定٩( ᐛ )و
