### ISSUE TITLE
オフライン中にDropboxの曲を「保存／エクスポート」しようとすると、「セーブ中」のまま固まる 

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#26]
オフライン中にDropboxの曲を「保存／エクスポート」しようとすると、「セーブ中」のまま固まってしまうのを見つけました！

オフライン中は保存できない旨をメッセージとして表示させる必要があるかと思います。

加えて、

* 保存／エクスポート
* 別の再生リストに移動
* コピー
* 削除
* 曲順の並べ替え
* タイトルとアーティスト名を変更
* 歌詞を表示
* エフェクトの設定状態を保持

とありますが、「保存／エクスポート」以外にオフライン中だとできない項目はありますか？？
「歌詞を表示」も該当しますかね？？

**Comment by ryotayama** [comment]
歌詞はオフラインで管理してるから、「保存／エクスポート」だけだね。
ありがとう、対応しまーす٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　ver.1.66でリリースします٩( ᐛ )و
