### ISSUE TITLE
リストの罫線が左端までないのが気になる

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#260]
ハヤえもん iOS ver.2.92

https://twitter.com/ryota_yama/status/1073433497883181057?s=21
罫線が左端まで無いのはこれでいいかなぁ？？

![Image](https://i.imgur.com/oWTbeBm.jpg)

それ確かに気になるよねｗ
イコライザとエフェクトもそうなんだよなーやっぱ変えるなら合わせないと変かなー…

デフォルトがこうなんだけど、不思議だよねー！
‎全画面、左端までいくように対応しよーかな？٩( ᐛ )و

他の画面はさほど気にならないけど、曲順の桁が2桁以上になると罫線からはみ出してしまうから、どうしても不自然になるよね💦

そうそう、すごく気になる……！

**Comment by ryotayama** [comment]
対応しました！　バージョン2.94でリリース予定٩( ᐛ )و
