### ISSUE TITLE
「ノーマライズ適用中…」というダイアログが表示されないようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#265]
バージョン2.93

https://twitter.com/ryota_yama/status/1068510051428495360
これ何かと「ノーマライズ適用中…」が出るのなかなかウザいなー！　まぁいったんこれで行って、本対応は別途考えよーっと٩( ᐛ )و 

https://twitter.com/SanadamaruD/status/1071653222484328448
りょーたさん、音楽を再生すると同時に
ノーマライズを適用中と出て、動く時と動かない時があります。

おぉ、ご連絡ありがとうございます٩( ᐛ )و
「動かない時」というのは完全にフリーズしちゃいますか？？

はい、今そんな感じです。
操作不能ですが音楽は流れ続けます。

https://twitter.com/SanadamaruD/status/1072420442894462977
りょーたさん、やっぱりどうやら
ノーマライズ適用中で止まってしまいます。
電源落として再起動してもダメです。
何とか修正して頂けないでしょうか？

https://twitter.com/SanadamaruD/status/1072454729962274817
りょーたさん、やっぱりノーマライズ適用中でどうやらフリーズしてしまいます。
1度電源落としてもダメです。
どうにかなりませんか？

おぉ、申し訳ない(*ノﾉ)
いまだにこっちの環境で再現できてないんだよなー！
引き続きテストしてみまーす！

https://twitter.com/SanadamaruD/status/1072683202370711552
んにちは。
どうですか？
バグの連絡はありましたか？

https://twitter.com/SanadamaruD/status/1072695851112222720
りょーたさん、大変お忙しい中何度も申し訳ありません。
そもそも曲を再生する度に出るノーマライズを適用中
これはバグではないですよね？

現状は仕様扱いだけど、いちいちダイアログが出てきてウザい認識はあるから、いずれ改善しようと思ってる٩( ᐛ )و

https://twitter.com/SanadamaruD/status/1073942434537590784
りょーたさん、今度は
ノーマライズの途中で止まってしまい、フリーズしてしまうという
不具合が生じました。
どう思いますか？

あー、これ返信漏れてたごめん！
こっちで再現できないから対処の仕方が分からない以上、もう本格対応として「ノーマライズ適用中」のダイアログ自体出さなくする対応をします！
しばしお待ちあれ！

https://twitter.com/ryota_yama/status/1074348877732470784
#ハヤえもんAppStoreでのやりとり
ハヤえもん ★★★★★
投稿者: 谷口弘恭 – 2018年12月15日
どうも、谷口 弘恭です。ごく最近ハヤえもんがアップデートをしてから、少々使い難いところがあるので改善できるのであればこちら側としては嬉しいです。1つ目に音楽を聴いている時にノーマライズが適用されているのは良いのですが、他の曲を聴く時にノーマライズを適用中という画面が出たまま操作が出来ないので、エフェクトボタンの所でノーマライズの適用をして、他の曲を聴けるようにお手数をおかけしますが、改善をしていただけませんか？良い面で評価をすると、エフェクトボタンの中にノーマライズが入ったことによって音質が良く、リバーブ(広い部屋)に設定するとさらに音質が良くなりました。僕にとってはSONYのWALKMANよりも音質が良いなと思って、最近はハヤえもんのアプリを使って音楽を聴くのが多くなりました。

デベロッパの回答 – 2018年12月17日
谷口弘恭さん、どーも！　りょーたです٩( ᐛ )و
他の方からも「ノーマライズを適用中というダイアログが出ないようにしてほしい」というご意見をいただいておりますので、対応しますね！
対応完了までしばらくお待ちくださいませ。
ハヤえもんを気に入っていただけてとっても嬉しいです！
他にも気になる点などありましたら、いつでもご連絡くださいね。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

**Comment by ryotayama** [comment]
対応しました！　バージョン2.94でリリース予定٩( ᐛ )و

**Comment by arigayas** [comment]
これってクラシック曲とか長い曲(30分以上)で試すとどうなるのか気になりました。

**Comment by ryotayama** [comment]
バックグラウンド処理で初回だけ曲の最大値を取得しといて次回以降はそれを使うようにしたから、特にレスポンス上の問題は無さそう！
一応、２時間ぐらいの曲でも試したよ٩( ᐛ )و

**Comment by arigayas** [comment]
なるほど。
２時間ぐらいの曲で問題ないのなら大丈夫そうですね。

このissueだけに限ったことでは無いですが、
issueに対するやった内容が書かれると後から、
このissueが関連するかも？と考察出来るようになる気がします。
_意図的に書いてないのなら余計なコメントですが(汗)_

**Comment by ryotayama** [comment]
ありがとー！
開発に対するモチベーションを考えた時に、「情報を残す」って方向性よりも「先に進む」って方向性に気持ちが向くことが多くて、どうしても「残す」方向に対してはテンションが下がりがちなんだよねー。
ありさんの言ってる話はすごく良く分かるから、少しずつがんばりまーす٩( ᐛ )و

**Comment by arigayas** [comment]
>どうしても「残す」方向に対してはテンションが下がりがちなんだよねー。

わかりました。
