### ISSUE TITLE
「各画面の設定を保持」機能について、メニュー内に再生中の設定を保持できる機能を追加したい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#267]
バージョン2.93

https://twitter.com/UmeboshiKantaro/status/1070856839519039489
初期の頃みたく、左上メニューの中にもあった方がいいのかな？？
「再生中の曲のエフェクト状態を保持」だったっけ確か…？

おぉ、それはアリかも！٩( ᐛ )و
変更後の表記にあわせると「再生中の曲の各画面の設定を保持」になるのかなぁ（わりと長いw）

いったん再生リスト画面に移らないと使えないってのが、多分画面設計として欠陥があるんだと思うよね…
当時は下からのメニューだったから表示しきれなくて削っちゃったけど、今は入れた方がきっといいよね！

**Comment by KanzakiSaki** [comment]
https://twitter.com/UmeboshiKantaro/status/1074775964012302336
#267と#268、一旦こんな感じで組んでみたけどどうかなぁ、、　
![02](https://user-images.githubusercontent.com/32741225/50354926-69cd4300-0590-11e9-86a2-79acd2a8a755.png)

あ、スクロールするのは白い背景の部分だけです！歯車アイコンの部分は固定で

うぉー、素晴らしい！ メニュー名が長い問題を解決してる！ ありがとー٩( ᐛ )

**Comment by ryotayama** [comment]
対応しました！　バージョン2.98でリリース予定٩( ᐛ )و
