### ISSUE TITLE
保存／エクスポート機能について、左からのメニューに再生中の曲を保存／エクスポートできる機能を追加したい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#268]
バージョン2.93

https://twitter.com/UmeboshiKantaro/status/1070858454653329408
再生中の曲シリーズは保存／エクスポートも入れたいなーと思ってた！！

**Comment by KanzakiSaki** [comment]
https://twitter.com/UmeboshiKantaro/status/1074775964012302336
#267と#268、一旦こんな感じで組んでみたけどどうかなぁ、、　

![02](https://user-images.githubusercontent.com/32741225/50355030-b57fec80-0590-11e9-8254-168cd2d66f6c.png)

あ、スクロールするのは白い背景の部分だけです！歯車アイコンの部分は固定で

うぉー、素晴らしい！ メニュー名が長い問題を解決してる！ ありがとー٩( ᐛ )

**Comment by ryotayama** [comment]
@UmeboshiKantaro これ画像もらってなかったと思うから、もらい次第着手するねー٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
@ryotayama ごめーん！これPDFで出力しようと思ってて、既存のアイコン画像もPDFに統一したいんだけど、差し替えってお願いしてもいいかな？？

**Comment by ryotayama** [comment]
全然大丈夫ー٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
https://twitter.com/UmeboshiKantaro/status/1078923892029251584
こんな感じで最終調整しました！ PDFアイコン共有に上げてあります！ 確認お願いします🙏
![02_2](https://user-images.githubusercontent.com/32741225/50535256-8b7b8b00-0b8b-11e9-9634-bba25dffd67a.png)

**Comment by ryotayama** [comment]
対応しました！　バージョン2.98でリリース予定٩( ᐛ )و
