### ISSUE TITLE
どこの画面でも「現在の再生時間」が分かるようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#27]
- iOS版ver.2.65

https://twitter.com/ryota_yama/status/1034310588501876737

#ハヤえもんAppStoreでのやりとり
Windowsパソコンで楽しんで使ってました。 ★★★★★
投稿者: Silvia1235 – 2018年8月27日
まさかiPhoneでもこのアプリが使えるとは願っても無いことでした。とても感謝しております。
速攻で広告除去（課金）させてもらいました。
個人的には音楽再生中のシークバーと再生経過時間がどこの画面でも表示されたらいいなと思いました。
あとはメトロノームで、音楽のリズムに合わせてタップするとBPMが測れるような機能があれば面白いかなと思いました。

デベロッパの回答 – 2018年8月28日
Silvia123さん、はじめまして！
ハヤえもん開発者のりょーたと申します₍₍ (ง*ᐛ)ว ⁾⁾
わー、Windows時代からのユーザーさんですか！
課金まで……ありがとうございます！
シークバー欲しいですよね！
どういう形で対応するか検討しつつ、いずれ対応しますね！
メトロノームのタップによるBPM設定についても、前向きに検討してみますので、しばらくお待ちくださいませ。
他にも何かありましたら、いつでもご連絡くださいね。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

◆関連Issue
https://github.com/ryotayama/Hayaemon/issues/55
https://github.com/ryotayama/Hayaemon/issues/56
https://github.com/ryotayama/Hayaemon/issues/448

**Comment by ryotayama** [comment]
@UmeboshiKantaro これ「再生中画面」を作った事によって、いったんCloseして様子見しようかと思うけどどーかなぁ？？

**Comment by KanzakiSaki** [comment]
おお！closeしていいと思います👍

**Comment by ryotayama** [comment]
Closeします٩( ᐛ )و
