### ISSUE TITLE
iPadで再生ボタンと再生リストの表示を大きくできるようにしてほしい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#279]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/246

## ryotayama 2018.06.24
◆使用しているOS：iOS版
◆使用しているバージョン：2.53
◆内容（FacebookのMessagerにて頂いたご意見）
iPadにてハヤえもんiOS版をライブで使用したところ、再生ボタンや再生リストの表示が小さく、押し間違えのリスクが高いと感じたので、大きく表示させられるようにしてほしい。

## UmeboshiKantaro 2018.06.27
referenced issue to ryotayama/hayaemon/issues/257

## ryotayama 2018.07.18
referenced issue to ryotayama/hayaemon/issues/360

**Comment by ryotayama** [comment]
@UmeboshiKantaro これ「再生中画面」を作ったから、いったんCloseして様子見でどうかなぁ？？

**Comment by KanzakiSaki** [comment]
https://github.com/ryotayama/Hayaemon/issues/433
こちらのDynamic Typeとも関連付けしてからcloseでいいと思います👍

**Comment by ryotayama** [comment]
Closeします！
