### ISSUE TITLE
エコーが一律同じになってしまう事がある

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#280]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/248

## ryotayama 2018.06.25
◆使用しているOS：iOS版
◆使用しているバージョン：2.53
◆内容
https://twitter.com/meg__fairy/status/1010923380772519936?s=21
ハヤエモン、とても便利で使っています✨
ただスマホのエフェクトのボーカルエコーや他のエコーが、以前はちゃんときれいに違いがあるディレイエコーがかかったんですが、今はどれもやまびこみたいに後からついてくるだけになってしまいます！
改善していただきたいです(>_<)🙏

**Comment by ryotayama** [comment]
こちらのIssueについて、同様の不具合報告が無ければCloseしようかと思います٩( ᐛ )و

**Comment by arigayas** [comment]
報告者の人に最新バージョンを使って見てもらって、
「最新バージョンではどうですか？」と聞いてみるのはいかがでしょうか？

**Comment by ryotayama** [comment]
あ、たしかに！　聞いてみるね٩( ᐛ )و

**Comment by ryotayama** [comment]
リプ送ってみた！

https://twitter.com/ryota_yama/status/1080714580592975872
メグさん、明けましておめでとうございます！
こちらの不具合って、最新版でも発生しますでしょうか？
お時間のある時にでもご確認いただけたら嬉しいです٩( ᐛ )و

**Comment by arigayas** [comment]
良い返答があると良いですね！

**Comment by ryotayama** [comment]
返答なし＆他に事例もないのでCloseします！
他に事例が上がってくるようなら別途Issue立てます！
