### ISSUE TITLE
左のメニューをスワイプで出せるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#287]
バージョン2.94

https://twitter.com/UmeboshiKantaro/status/1074806350855589888

ハヤえもん左上のメニュー、画面左端スワイプで出てきて欲しさある？？って思ったけど、コントロール画面とかABループ画面もあるから扱い難しいな… 

![dup6ro2uyaafpmf](https://user-images.githubusercontent.com/32741225/50355675-dd704f80-0592-11e9-8ce2-b8740ee019ce.jpg)

出てきてほしい！
左端からスワイプされたらみたいな判定ができれば実装できるかも٩( ᐛ )و

エッジスワイプ ジェスチャーって言うのかな？？名称がよく分からなかった💦

**Comment by ryotayama** [comment]
対応しました！　バージョン2.98でリリース予定٩( ᐛ )و
