### ISSUE TITLE
イコライザのカスタマイズ画面のスライダーを、再生中画面のシークバーと同じデザインにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#288]
バージョン2.94

https://twitter.com/ryota_yama/status/1075350178612146177
iPad横画面はなかなかカオスだよw

![img_3674](https://user-images.githubusercontent.com/32741225/50368995-41663880-05d2-11e9-9f26-d08636b15d19.JPG)

あぁーこれか集合体恐怖症…！イコライザのカスタマイズ画面やべぇー😭

ヤバいでしょー。いったんシークバーのデザインを再生中画面と同じにするぐらいならサクッとできそうだから、やっちゃおっかなー٩( ᐛ )و

マジかぁ…！！ シークバー的な感じになるとだいぶスッキリするのと、動かしてる感が出ていいかも…！？！？

うんうん、つまみのサイズが可変になるから、動かしてる感めっちゃ出るよね٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
#11 と同じ画面なので関連づけておきます(*･ω･)ﾉ

**Comment by ryotayama** [comment]
対応しました！　バージョン2.97でリリース予定٩( ᐛ )و
