### ISSUE TITLE
一部の環境で、上部の「シャッフル」「リピート」ボタンが反応しない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#289]
バージョン2.95

https://twitter.com/crazy_345/status/1076503810619494401

はやえもんリピートできねえじゃねあかゴミか

https://twitter.com/ryota_yama/status/1076613296415895557

うぉー、ごめんなさい！！
どういうシチュエーションでリピートできませんでした！？

右上のシャッフルもリピートも押しても切り替わらないですねぇ…

うぉー、まじですかごめんなさい！！
押すとこんな感じで選択状態にならず、無反応って事ですよね？？

そういうことになりますね
バージョンは最新だと思うんですが自分だけですかね…？

はじめて聞きました！！
こちらのボタンも無反応ですか？？

無いですね()

無い……！！
お使いの端末ってiPhone SEですか？？

そうです！iPhoneはアップデートしてなかったと思います

ふむふむ、iOSのバージョンも教えてもらえますか？？
（設定→一般→ソフトウェア・アップデートというところから見れます）

（iOS12.1.2のスクショ）

ありがとうございます！
原因究明して修正しますが、現在アップルがお休み中なので公開までにしばらく時間がかかりそうです！
お待たして申し訳ありませんが、しばらくお待ちくださいませ！

**Comment by ryotayama** [comment]
◆メモ
画像の比較をする際、直接比較している為、メモリ上の別の領域に確保された場合に動作しないと思われる。
実際の実装方法はこちらを参照。
https://stackoverflow.com/questions/11342897/how-to-compare-two-uiimage-objects/11342977

**Comment by arigayas** [comment]
issue登録のコメントにスクリーンショットを2枚添付しました。

**Comment by ryotayama** [comment]
対応しました！　バージョン2.96でリリース予定٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/crazy_345/status/1076625000797327360
右上のシャッフルもリピートも押しても切り替わらないですねぇ…

**Comment by ryotayama** [comment]
https://twitter.com/dosukebenomai/status/1076654034902106112
ループシャッフル再生ボタンが押せません

**Comment by ryotayama** [comment]
https://twitter.com/MMMMJKI/status/1076677808913403904
ハヤえもんリピート出来なくて投げた

**Comment by ryotayama** [comment]
https://twitter.com/mikuta0407/status/1076665121513005056
ハヤえもん、ウニ買おうとバージョンアップしようとしたらバグあるっぽくて(´･ω･`)ってなってる

**Comment by ryotayama** [comment]
https://twitter.com/amachan_mori/status/1076787608787726338
あれ？ハヤえもんのリピート使えない…？

**Comment by ryotayama** [comment]
https://twitter.com/sdvx_rsig/status/1076774810519187457
お、ハヤえもん不具合かな？
リピートやシャッフルが機能してないかも

**Comment by ryotayama** [comment]
https://twitter.com/Pokari1260/status/1076843373976117248
ハヤえもん
アイポン6だとシャッフルとかリピート出来ないおﾟ(ﾟ`ω´ ﾟ)ﾟ
アイポン8は大丈夫なりなりヽ( 'ω' )ゝ三ｼｭｯ
アイポン6で音楽聴いてるからﾃﾝﾔ \(; ºωº \ Ξ / ºωº ;)/ ﾜﾝﾔ

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077011169947205633
#ハヤえもんAppStoreでのやりとり
最新アップデート ★☆☆☆☆
投稿者: かみこう – 2018年12月23日
シャッフル、リピートボタンが押しても反応しません…

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077011344652566528
#ハヤえもんAppStoreでのやりとり
アップデート不具合 ★★★☆☆
投稿者: コウキ73 – 2018年12月23日
音楽を聴いてるとアプリが落ちます。
あと、ランダム再生や連続再生のコマンドが反応しません。

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077012804723367937
#ハヤえもんAppStoreでのやりとり
おしい！ ★★★★☆
投稿者: ぽてpote – 2018年12月23日
動画やYoutubeなどのいろいろな音楽がきけていいのですが、アップデートしてから全音楽でのシャッフルが出来なくなったり、停止ボタンがなくなったりと、操作方法がイマイチ分からなくなったのでアップデートする前の方がよかったんじゃないかと思います。出来ればでよろしいのですがアップデート前に戻して頂けたら嬉しいです。

**Comment by ryotayama** [comment]
https://twitter.com/mjadtpmqmmt/status/1077037867342282752
すいません。
画面上のシャッフル・リピートボタンを幾ら押しても反応しなくなりました。
最新のアップデートでボタンの設定が変更されたみたいですが、
これは不具合なのでしょうか。

https://twitter.com/ryota_yama/status/1077038510350057473
ごめんなさい、不具合です！
年末か年明けにはリリースできるよう対応を進めていますので、しばらくお待ちくださいませ(ノ_ _)ノ

先程質問させて頂いた者です。
そうなんですね。安心しました。
早急に応答していただき、ありがとうごさいます！

※１つ目のリプと２つ目のリプでIDが変わっている為、連絡時注意！

**Comment by ryotayama** [comment]
https://twitter.com/NoMUtmK6e4kAQ5a/status/1077137682386407424
ハヤえもんさん！こんばんは
いつもお世話になってます！
アプリについつなのですが、以前みたいに一曲リピートや全曲リピートなどの設定の仕方がわからないのですが、教えていただけませんか？

**Comment by ryotayama** [comment]
https://twitter.com/7_DOLPHINSAN/status/1077185342346690560
使用機種iphone6S
使用os ios12

リピート、ランダム再生ボタンが機能しない+クラッシュによるアプリの強制終了が発生しています。

**Comment by ryotayama** [comment]
https://twitter.com/hasse520/status/1077384715387035649
いつもありがとうございます！
今までシャッフル等の機能が使えていたのですが、現在使用できません。
アップデート済みです。
何が原因でしょうか？

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077390396269817856
#ハヤえもんAppStoreでのやりとり
アプデ後 ★★★★★
投稿者: ジャックサマワン – 2018年12月24日
いつも利用させてもらってます。

アプデ後シャッフル、リピートが機能しなくなりました。
改善できればお願いしたいです。

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077396630637142017
#ハヤえもんAppStoreでのやりとり
シャッフル機能をください ★★★★☆
投稿者: Pachouli.K – 2018年12月24日
音楽プレーヤーとして毎回とても助かっております
ただ、アップデートしてからシャッフル機能とリピート機能が消えるということでとても切なくなっております

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077397517728280576
#ハヤえもんAppStoreでのやりとり
良き ★★★★★
投稿者: C38H69NO13 – 2018年12月24日
手軽に再生速度や音程を変えられる機能がとても便利。具体的な用途としてはnightcore mixにして曲のテイストを変えたいときに使用しています。ドライブが一段と楽しくなりました。
車で使用する際iPhoneを横向きで使うのでiPhoneでの横画面に対応してもらえると嬉しいです。
【追記】
アップデートしたら、シャッフル機能とリピート機能が使えなくなりました。
ボタン押しても反応なし。
残念です。

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077398387580760064
#ハヤえもんAppStoreでのやりとり
コントロールボタンを戻して欲しい… ★★★☆☆
投稿者: ori.or – 2018年12月25日
アップデート後からリピート機能やシャッフル機能が使えなくなってしまったのが残念です。前の方が使いやすかったので戻して欲しいです…

**Comment by ryotayama** [comment]
https://twitter.com/Yoshiki_trick/status/1077403520834273281
ランダム再生、リピート再生の指定ができません

iPhone6s

**Comment by ryotayama** [comment]
https://twitter.com/ui_ui_ii/status/1077553794353848321
愛用させていただいております。
リピート再生できません(´･ω･`)

**Comment by ryotayama** [comment]
https://twitter.com/chaco0310/status/1077566571550101504
数日前にインターフェースが一新されてから、リピート、シャッフルを押しても(機能が)オンにならなくて、通常再生しかされません。年内に修正アプデはありますか…？

**Comment by ryotayama** [comment]
https://twitter.com/26ChHumB/status/1077754375794176000
リプライ失礼します
iPhoneSE,iOS11.3.1で利用させてもらってます！
どうもリピート・シャッフルができなくなったようです。アプリ、iPhone再起動も試しましたがダメでした。いつからリピートとかができなくなったのか正確に把握できてなくて申し訳ないですが、良ければお返事お願いします

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077875583931936769
#ハヤえもんAppStoreでのやりとり
シャッフルが… ★★★★☆
投稿者: ( ^ω^ )(￣▽￣)^o^ – 2018年12月25日
シャッフルができなくなって
しまいました

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1077876806743511041
#ハヤえもんAppStoreでのやりとり
愛用しているのに… ★★★★☆
投稿者: Ballet Egg – 2018年12月26日
とても愛用させて頂いてます！
でも、アップロードをしてからでしょうか。1曲ループが出来なくなってしまいました(´･_･`)悲しいです(´･_･`)

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1078277267057332224
#ハヤえもんAppStoreでのやりとり
音楽アプリとして使っています（＾ν＾） ★★★★★
投稿者: グラタンストック – 2018年12月26日
テンポを早くできたりエコーをかけたりできて、音楽をより楽しく聞けるので私はこれで音楽を聴いています(^^)逆にこのアプリ以外で聞けなくなります))笑笑
不具合などもすぐ対応してくれていると思います。ありがとうございます（＾_＾）
アップデートしてシャッフルができなくなりました、シャッフルマークを押しても反応しません(T . T)

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1078277658851475457
#ハヤえもんAppStoreでのやりとり
シャッフル ★★★★☆
投稿者: aimarl5623 – 2018年12月27日
いつも楽しく使わせていただいてます。先日アップデートさせていただいたところ、シャッフル再生ができなくなってしまったようです。上部の矢印交差ボタンを押してますが合っていますか？？
教えていただけると嬉しいです

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1078278117074948096
#ハヤえもんAppStoreでのやりとり
リピートボタンとシャッフルボタンが… ★★★★☆
投稿者: まふくんかわいいつらい – 2018年12月27日
いつもお世話になっております。
大変充実した機能でとても楽しく使わせて頂いおりますが、リピートボタンとシャッフルボタンを押しても全く反応がないので改善して頂ければと思います。

**Comment by ryotayama** [comment]
https://twitter.com/sprinter_kokuto/status/1078532957663420417
りょーた様、
ハヤえもん、いつも便利に
使わせて頂いております。
ありがとうございます。
ipod touchで使っているのですが
以前できていたリピートと録音が
最近できなくなりました。
これについても
次回のアップデートで
改善して頂けるのでしょうか？
それとも機器のOS等の
問題なんでしょうか？
