### ISSUE TITLE
ボイスオーバー環境での挙動を考慮できていない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#290]
バージョン2.95

https://twitter.com/ijokuzuy/status/1076703105222291456

ハヤえもんって無料なのにどんな音楽アプリよりも使いやすくて機能が多いよね
長年使ってるけど飽きないよ
開発者さんの丁寧さも世界一！

…だけど、今回のアプデで要望があるんです
開発者さん、見てくださいましたら改善お願いします！

私は視覚障害者なのでiPhoneのボイスオーバーという画面読み上げ機能使っています
今でこそ慣れてきましたが、ボイスオーバーでうまく読み上げてくれないアプリは結構多いんです
しかしハヤえもんは違うんです
今までのどのアプリよりもこのボイスオーバーを使っての操作がしやすいんです

そこで改善してほしいところがあります
今回のアプデで変わったデザインを元に戻してください
これは私のわがままかもしれません
でも、開発者さんに甘えて言わせていただきます
シャッフルとリピートのボタンは分けないでください
再生モードがボタンを押しても変わりません

メニューは画面のスライド形式からボタンのタップ形式に戻してください

長々とすみません
いろいろな意見があるので、かなわないかもしれないということは分かっているつもりです
できれば少し考えていただけないでしょうか

ご迷惑をおかけして申し訳ありません！
再生モードがボタンを押しても変わらないというのは最新版で埋め込んでしまった不具合です！
現在、緊急で修正版を開発しておりますので、今しばらくお待ちくださいませ！
なるべく早く修正版をリリースできるように、します！

メニューなどの挙動についてもボイスオーバー環境の事を考慮できておらず誠に申し訳ありません！
こちらについても改善します！
もうしばらくお待ちくださいませ！

**Comment by KanzakiSaki** [comment]
https://twitter.com/umeboshikantaro/status/1077451714221924352?s=21

ハヤえもん最新開発版をVoiceOverで使ってみた

これ画面録画したけど、音声入らないんだなー💦

問題点

①上部コントロールボタンと左メニューのオプション設定ボタンにラベルがないため、画像名が読み上げられている？

②左メニューを閉じるエリア（グレーになっている部分）が正しく選択できない

③左メニューとアクションシートのメニュー選択エリアが狭い（テキストのみしか選択されない）

**Comment by KanzakiSaki** [comment]
今回初めてVoiceOverを触ったけど、実際に使ってる人がどんなふうに不便かって、なかなかわからないなー💦

**Comment by ryotayama** [comment]
うめちゃん、色々研究してくれてありがとー！
自分も試してみよーっと٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
ラベルのないボタンへの読み上げ対応は優先度高そう…
HTMLの画像みたく、alt属性的なやつがあるのかな？？

**Comment by ryotayama** [comment]
そうだね、2.97でやろー！٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
![Image](https://i.imgur.com/I0EwjlT.jpg)
テスト配信試してみてるけど、この左メニューを閉じるのはどう操作したらいいんだろう？？

**Comment by ryotayama** [comment]
閉じるボタンが存在しないから、フォーカスが当たらないね……！
別で課題管理が必要かなー！

**Comment by ryotayama** [comment]
画面右下に仮想ボタンを作る事により、閉じられるように対応した٩( ᐛ )و
![ios](https://user-images.githubusercontent.com/6075785/50471286-4a527200-09f7-11e9-9b65-f854ac1c4cad.png)

**Comment by ryotayama** [comment]
対応しました！　バージョン2.97でリリース予定٩( ᐛ )و
