### ISSUE TITLE
確認ポップアップの「OK／キャンセル」の文言を見直したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#293]
ハヤえもん iOS ver.2.95

https://twitter.com/yu_45_tym/status/1076836264932855810?s=21
こんばんは。今までに使わせて頂いていて感じたのですが、プレイリストを保護（保護解除するまで消せない）するような設定は追加出来ませんか？専ら私の不注意なのですが、よく削除してしまいます…可能でしたら宜しくお願い致しますm(_ _)m

こんばんはー！！
おぉ、なるほど！！
ご参考までにお聞かせいただきたいのですが、どういう時に誤って削除してしまいますか？？

プレイリストの名前を変更する場合です。一般的にあまり頻度は多くないと思われますが、私の場合よく触る場所なので誤操作をしてしまう事があります。
再確認の画面も出ますが、セッカチなのでついOKしてしまいます…w

https://twitter.com/umeboshikantaro/status/1076851047044280321?s=21
ウニの購入確認画面、自分なりに「OK／キャンセルは使わない」という意志のもと、文言を考えました。
この「OK／キャンセル」は昔からユーザーの操作ミスを招く、欠陥のあるデザインだと感じています。
やはり他の確認画面も文言を変えた方がいいでしょうか…？？ 
![Image](https://i.imgur.com/rdVHaMA.jpg)

なるほどね、ぜひぜひ٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
* 再生リスト削除の確認ダイアログ
![Image](https://i.imgur.com/ATk3i4n.jpg)
やめる／削除する

* 曲の削除確認ダイアログ
![Image](https://i.imgur.com/SO32DJO.jpg)
やめる／削除する

* イコライザ初期化の確認ダイアログ
![Image](https://i.imgur.com/27DarJm.jpg)
やめる／初期化する

でどうでしょうか？？
配置は右と左どちらの方がいいのかな…


ちなみにイコライザ削除は確認ダイアログそのものが表示されないまま削除が実行されてしまいました…
別issueを登録かな？？

**Comment by arigayas** [comment]
> ちなみにイコライザ削除は確認ダイアログそのものが表示されないまま削除が実行されてしまいました…
別issueを登録かな？？

別issueで登録した方が良いと思います。

**Comment by ryotayama** [comment]
ありがとー、別Issue立てた！
うめちゃんの文言良いと思うから、実装するね！
（多言語対応がんばろーっと）

**Comment by KanzakiSaki** [comment]
うぉっ！ありがとう！！

あとこれ「削除する」「初期化する」のテキストカラーを赤とかにできないかな？？
警告色にした方がより操作ミスを防げるかなと思ったけどどうだろう？？

**Comment by ryotayama** [comment]
赤文字できたはずだから、そうするね！！٩( ᐛ )و
あ、右手の親指で操作する人が多いから、決定は左側にあったほうが良いのかなぁ？？

**Comment by KanzakiSaki** [comment]
そうそう、右か左かって大事よね…！
私も質問が「削除しますか？」だから、「削除する」は先に持ってきた方が自然な気がするなー

**Comment by ryotayama** [comment]
それで行こー٩( ᐛ )و
また画面作ったら見せるね！

**Comment by ryotayama** [comment]
対応しました！　バージョン2.98でリリース予定٩( ᐛ )و
