### ISSUE TITLE
一部環境で上部メニューの位置がズレている

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#294]
ハヤえもん iOS ver.2.95

https://twitter.com/pokari1260/status/1076843373976117248?s=21

![Image](https://i.imgur.com/bRKsRTX.jpg)

![Image](https://i.imgur.com/m8wGJoQ.jpg)

https://twitter.com/umeboshikantaro/status/1076988740491345921?s=21

ありがとうございます😇🙏✨✨
そして写真見る感じ上のメニューがズレてるけど大丈夫かな…💦

うう（ ᵒ̴̶̷̥́_ᵒ̴̶̷̣̥̀  ）
アイポン6だと重なりますね( ˘ω˘ ) ｽﾔｧ…

ありがとうございます！iPhone6ですね！確認してみたいと思います…！🙏

**Comment by yuri-regulus-25** [comment]
タイトルに誤字があったため修正しました( ˘ω˘ )

**Comment by KanzakiSaki** [comment]
ゆっきーありがとー！
なんかCodeHubで打ち込むと変になるんだよねー(*ﾉﾉ)

**Comment by KanzakiSaki** [comment]
スレッドの続き↓

https://twitter.com/ryota_yama/status/1077001707832324096?s=21
うぉー、ポカリさん申し訳ないです！！(ノ_ _)ノ
ちなみにiOSのバージョンっていくつですか？？

( 'ω')ｷﾞｬｧｧｧｧｧｧ！！！ごめんなさい(´இωஇ｀)
アップデートが出来なくなってバージョン10.2.1です((((  '-'   ))))ｶﾀｶﾀすみません

いえいえ！　こちらで再現する際のとても有益な情報になるのです！
‎そして、おかげさまで原因が分かってきた気がします！
‎とっても助かりました、ありがとうございます٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.96でリリース予定٩( ᐛ )و
