### ISSUE TITLE
「再生範囲」を指定して再生できるようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#3]
- iOS版ver.2.64

Bボタンの右あたりにループのオンオフを切り替えるボタンを追加したいなと。

デフォルトはオンになっていて、オンの状態でA位置、B位置を設定した場合は、今まで通りAB区間を無限ループ。

オフの場合は、A位置からB位置まで再生し終わったら次の曲に進むって仕様にしようかなと。

何が嬉しいかというと、いろんな曲のサビだけをひたすら聴いたりとか、そういう「再生範囲の指定」的な事ができます。

**Comment by KanzakiSaki** [comment]
この件に関するクローズドのやり取りを公開しておきます(*･ω･)ﾉ↓

これだれか意見くれると嬉しいです₍₍ (ง*ᐛ)ว ⁾⁾

ナイスアイデアやんって思ったよ！！
画面上の再生リピートの設定に従うのはどうかな？？

おぉ、うれしい！！
画面上の再生リピートの設定とは……？？
次の曲に進む時の挙動が「ランダム再生だったら、無作為に次の曲が決まる」的な話だったらそのつもり！！

おお、それのオンオフが切り替えられるボタンをつけるってこと？？

![Image](https://i.imgur.com/BMGJzDg.jpg)

ここにボタンがあって、オンの時はB位置まできたらA位置に移動する、オフの時はB位置まできたら次の曲に進むって挙動を考えてる！

今までABループ設定したら無条件で1曲リピート扱いになっていたもんね

そうそう！

オンオフの切り替えはオプション設定画面ができたらそこに入れた方がスマートかも？？
ABループ画面に入れるとなるとボタンのデザインはちょっと考えなきゃだなぁ

これ、「エフェクトの設定状態を保持」をしたときに、曲ごとに設定できるってところにメリットがあって、曲によってはABループさせたいし、曲によっては再生範囲として機能させたいと思うんだよね。
そう考えるとオプション設定画面じゃなくて、ABループ画面にあった方がいいのかなーと。

曲によってかあ。。
同じ再生リスト内で曲ごとに挙動が変わっちゃうけどそれっていいのかなぁ？？混乱しそうな気もするなぁ。。

混乱を避ける為の通常の発想でいくと、エフェクト画面に「再生範囲」ってエフェクトを付けるってのが自然なんだけど、それだと波形ベースで再生範囲を決められないんだよね。（その画面にも波形を出すって案もあるんだけどね）
何が実現したいかっていうと、別の曲として保存することなく、再生リスト内の曲をひたすらサビだけ聴くみたいなことをしたい。
ちなみにWindows版は「再生範囲」って機能を作ることによって解決してる。

再生リスト内で曲のサビだけをAB区間を指定しておくことでサビだけのいわゆる「メドレー」みたいな聞き方ができるってことだよね？？

それ自体は画面右上の再生モードに従うだけではダメなのかな？？
曲単位に設定できるメリットがあんまよくわかってなくて。。

再生モードに従うってどーいうこと？？

全曲ループだと再生リスト内のAB区間を順番にひたすら再生してくれるんだよね？？
1曲ループにしておけば今までのABループと同じになると思うんだけど。。
仕様が急に変わるからユーザーさんが混乱しそうって話でデフォルトオンで、オフにもできるようにしたいって感じなら、オプション設定画面に設けたらいいかなーって。
曲ごとにオンオフが切り替えられるっていうのがちょっとよくわかってないんだよね。。

ゼロから話をすると、ABループってループの為の機能だから、現状「A位置」または「B位置」が設定されてたらループをするって挙動にしていて、それ自体は特におかしくはないと思ってるんだけど、どーだろ。

そうなんだよね、ABループはループのための機能。だからデフォルトで1曲ループになってていいと思うし、実際使いやすいと思う

そこが共有できたら次は、じゃあそこに「再生範囲」を指定できるような機能を付けたいとなると、どこに付けるのが最適かなぁ？？

まずWindows版の「再生範囲」ってのを触ってみたほうがいいかな？？

ゼロベースで考えてくれていいよ。

うーん。。
例えばだけど、再生リストの中で1曲だけABループオンになっていたら、
右上の再生モードが全曲ループやランダムになっていたら、ABオンになってる曲の番が来た時にいきなり上の再生モードを無視してABループし始めると思うんだけど、認識あってるかな？？

現状の話だよね？　あってる！
A位置またはB位置のどちらかがオンの場合は、右上の再生モードは一切無視されるっていうのが、現状の仕様だね。

再生範囲の話は、他の人でも意見があったら教えてねー！

**Comment by KanzakiSaki** [comment]
「メドレー」みたいな聞き方ができるのは画期的なアイディアだなーと思ったけど、個人的にはオンオフの切り替えをABループ画面で行うところで一気に機能が複雑になるなーという印象を受けました。
他の方のご意見も頂戴したいです(´人･ω･｡)

**Comment by ryotayama** [comment]
まぁ、「ABループ」って名前が付いてる機能を「再生範囲」に転用しようとしてる時点で複雑だよねー。
だとすると、やっぱエフェクト画面に「再生範囲」機能を追加なのかなぁ。
それか、再生モードのところに「範囲指定」ってのを追加……うーん、
これもどこで範囲指定するのかって問題になってくるなぁ。むずい。

**Comment by ryotayama** [comment]
この話とちょっとズレるんだけど、ABループ中は右上の再生モードボタンが「ABループ」を示すアイコンに変わるってのもアリかもなーと思った。

**Comment by ryotayama** [comment]
https://twitter.com/AlyssumHeart/status/1033296064126709760
ハヤえもんでループ設定中。
ふと思ったけど、こうやってABで指定した区間をループするのではなく「B地点に来たら次の曲(のA地点)に飛ばす」とかできないかなー。

https://twitter.com/ryota_yama/status/1033306287465852928
関係者の中でも話題になって結論が出ていないんですが、「再生範囲」のような機能があったらいいかなーと思っていて、ただ現状の画面は「ABループ」なのでそこに「範囲指定」の機能まで盛り込んでしまうと複雑すぎて混乱を招くという事もあり悩んでます！
ご意見募集中٩( ᐛ )و

再生範囲、個人的にはめっちゃ欲しいです〜！でも、仰る通り『ループ』と書いてある場所ですしねぇ。これらを同居させるとなると『再生範囲』をベースに、そのページ内のチェックボックスのオンオフで『ループ』の切り替え……ちょっと煩雑な見た目になりますね……_(:3」∠)_

それ僕と同じ発想ですw
デザイナーのうめちゃん @UmeboshiKantaro から複雑性が高いと言われ、確かになぁとなって議論が止まりましたw

あぁ〜〜ですよね〜〜！！とはいえ、
(よりゴチャつくので)ループの隣に機能ページを増やす訳にはいかないし……今一度画面とにらめっこしましたが、やっぱチェックボックスしか思い浮かびませんですｗ
でも再生範囲は欲しい……！需要は……さ、最低一名分あります……_(:3」∠)_

２名分はありますよw僕もやりたいからw
うーん、うーん、もうちょっと悩んでみますね！
思い切って、ABループ画面を「波形」って画面に変えちゃってそこに機能を盛り込むってのも案としてはあるか。。うーん。。悩ましい。。

ヤッターこれで需要が二倍だ！ｗ
ループしたいだけやぞ！という方には誠にすんませんが、『再生範囲指定(ループなし)』は、可能であれば、とっても……欲しい！『波形』ページにまとめる案は、個人的には大賛成ですが……いや、悩みの種増やしてしもうて申し訳ないですホンマに！_(:3」∠)_

２倍wwポジティブww
これができると、サビだけメドレーみたいな聴き方もできるし、いいんですよねー！
あとは、社交ダンスの人とかは「最初の２分だけ曲を再生して止める」みたいな事を手動でやってるらしくて、ループ無しで再生範囲を指定できると嬉しいみたいですね（Windows版開発してた頃の知識）

母数の小ささを全面的に活かしたフレーズですｗｗ
私の場合は、あるゲームのサントラで『イントロとメイン部分が別トラック』というのがありまして。普通に連続再生すると、ゲーム内のように綺麗に繋がってくれないんです。再生範囲を切れれば、これを違和感なく繋げられるかも……という感じです。

なるほどねー！　それならなおさら、なんとか付けたいなぁ！
検討含めて時間がかかるかもしれないけど、待っててくださいね٩( ᐛ )و

もう用途からして完全にニッチ需要なんですけど、実現したら、ほんまに嬉しい……！
いやもう検討して頂けるだけでもありがたいです！お手数かけますが、よろしくお願いします……！！

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1061815260514926593

#ハヤえもんAppStoreでのやりとり
便利すぎ ★★★★☆
投稿者: ぼぼぽんち – 2018年11月10日
カメラロールにある動画を音楽ファイルに出来る機能がとても便利です！
音楽を途中だけ切り取って音楽ファイルにできたら、すごくありがたいです。
（例えば、サビだけ切り取ってメドレーみたいに聴きたい、みたいな。）

デベロッパの回答 – 2018年11月12日
ぼぼぽんちさん、はじめまして！
ハヤえもん開発者のりょーたです٩( ᐛ )و
おぉ、カメラロールからのインポート機能を喜んでいただけて嬉しいです！
現状だとABループ画面からAB区間を指定しておき、再生リスト画面の「・・・」メニューから「ローカルに保存」を選ぶと、AB区間だけが保存されますので、サビだけを切り取ったりする事ができます！
ぜひぜひお試しくださいね。
いずれもう少し手軽にサビだけメドレーのような事ができないか検討中ですので、こちらも楽しみにしていてくださいね。
他にも気になる点などありましたら、いつでもご連絡くださいませ。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

**Comment by ryotayama** [comment]
メニュー下部から遷移できるオプション設定画面を作成し、「AB地点を設定したら1曲リピート」というオプション項目を追加する対応をしました！　バージョン2.93でリリース予定٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
これ長かったね…！シンプルに解決できてよかった、読み返したら泣きそうw
