### ISSUE TITLE
広告削除に月額制を選べるようにしてほしい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#311]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/317

## UmeboshiKantaro 2018.07.07
広告削除について、現在では買い切り方式の2000円しかないですが、
ユーザーによっては「高い」という声もたまにあるので、月額制も選択できるようになると嬉しいです。

現在、App Storeでの最低販売価格が120円なので、1年で1440円です。それだけでもう17ヶ月以上使う人にとっては買い切りのが得になります。

こうした計算ができるユーザーにとっては、2000円で足踏みしていた広告削除に踏み切る可能性があります。

また、結果的に高くついても、月120円の方が支払いやすい、というタイプのユーザーもいるかもしれないので、そういったニーズを満たすのも大事かなと思っています。

ぜひ一度ご検討ください(*･ω･)ﾉ

## ryotayama 2018.07.07
いいと思いまーす₍₍ (ง*ᐛ)ว ⁾⁾
画面的にはメニューの「広告を非表示にする」ってとこから２分岐する感じになるのかな？？

## UmeboshiKantaro 2018.07.07
「広告を非表示にする」
の次のアクションシートで
・月額120円
・買い切り2000円（←もう少し適切な表現があると嬉しい）
と選べるといいんでしょうか？？

ryotayama/Hayaemon/issues/275 とも関連付けしておきますね(*･ω･)ﾉ

## ryotayama 2018.07.07
金額出すの多言語化の観点からできるかどうかちょっと分かんないや！
また調べとく！

## UmeboshiKantaro 2018.07.07
あー、ドルとかになっちゃうからか…！
よろしくお願いします！

## ryotayama 2018.07.07
メモ。いけそうだね。
https://qiita.com/kyasusoft/items/28e48f60f46c32483061

## ryutaro 2018.07.08
買い切り=>ライフタイム

2ヶ月に1回とかも確かできたので(本当か？)
調整が必要ですね

## ryotayama 2018.07.08
個人的には月額120円はわるくないなぁと思った！

## ryutaro 2018.07.08
120円がというより ライフタイム2000円との兼ね合い？

**Comment by KanzakiSaki** [comment]
ゆっきーissue移行ありがとう！

進展がありましたので貼っておきます(*･ω･)ﾉ

https://twitter.com/umeboshikantaro/status/1077786650359427072?s=21

こんな感じで一旦組んでみたけどどうかなー？？

最初150円って言ってたけど、120円の上が240円からしか設定できないとの事なので、ここは120円でいいのだろうか？？

![Image](https://i.imgur.com/nrCtn10.jpg)

文言はここを参考にしたよ！

https://support.apple.com/ja-jp/HT202023

2000円の方の文面…
｢他のデバイスに転送できます｣だと転送？ってなりそうだから｢他のデバイスでも適応できます｣とかの方がいいかもーぬん( ˘ω˘ )

ゆっきーありがとー！！
そこまさにコピペだったｗ

Appleﾊﾟｲｾﾝ…分かりにくいやろがいっ…

多分このページの英語版はナチュラルなんじゃないかな？ｗ

おぉ、すげーいい感じ！
‎作るの楽しみ٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
参考：iOSアプリで自動継続課金をリジェクトされないためのチェックリスト（iPhoneの定期購読サブスクリプション）
http://umenon.com/2017/09/21/subscriptionscheck/

* 有料版の概要
* 有料版の価格
* 復元について
* 解約方法について
* 自動継続課金について
* 注意点
* プライバシーポリシーのリンク

**Comment by KanzakiSaki** [comment]
https://twitter.com/UmeboshiKantaro/status/1141282307417858048
![広告削除画面02](https://user-images.githubusercontent.com/32741225/59757082-f057a880-92c5-11e9-8e4c-f08f489e8218.png)

これ作ってみたー！かなりスクロール必要になっちゃったけどボタン下の方がいいかな？と思って下にしておいた！ プライバシーポリシーはどこもリンクになっていたのだけど、開発者ブログの中に固定ページを作るのがいいかな？？

〜〜〜〜
広告非表示
アプリ内のすべての広告を非表示にすることができます。広告の非表示には、現在2種類の方法があります。
【買い切りプラン】2,000円
1回のみ購入が必要で、それ以降はお使いのApple IDに関連付けられている他のデバイスでも適用できます。
【月額プラン】120円
「広告非表示に2000円は高い」といった声が数多く寄せられたため、新たに月額プランを設けました。
月単位の定期購入で、広告非表示が適用されます。
月額プランの購入後、買い切りプランに変更することも可能です。（※買い切りプランを購入する際は、月額プランの解約手続きを行ってください。）
【解約方法】
1. 「設定」>「[ユーザ名]」>「iTunes と App Store」の順に選択します。
2. 画面上部に表示されている Apple ID をタップし、「Apple ID を表示」をタップします。サインアウトしている場合は、Apple ID でサインインする必要があります。
3. スクロールして「登録」を表示し、タップします。
4. 変更または解約したい登録 (サブスクリプション) をタップします。この画面から次回の自動更新タイミングの確認や、自動更新の解除/設定ができます。

【自動継続課金について】
月額プランは自動更新されます。期間終了の24時間前までに登録のキャンセルがなかった場合、次の期間に自動更新され課金されます。
【注意点】
•当月分のキャンセルについては受け付けておりません。
•iTunesアカウントを経由して課金されます。
〜〜〜〜

**Comment by KanzakiSaki** [comment]
https://twitter.com/ryota_yama/status/1141597284515213312
ハヤえもんiOS版、「広告非表示に2,000円は高すぎます」という声を受け、次は広告非表示機能に月額プランを追加する予定٩( ᐛ )و

わーーありがとう！！これ確認したら「おすすめ」なくなってた！！ 文言どうしよ💦「Today」でいいのかな💦
https://t.co/Hb8ibydvtr
これでいいのかなひょっとして…！？

おぉ、ほんとだー！
それでいけそうだね！
調べてくれてありがとー٩( ᐛ )و

いやコピペでマジごめん😭 こんな感じで書き直した！！
![広告削除画面03](https://user-images.githubusercontent.com/32741225/59836358-5441a600-9386-11e9-8cef-0c4ea2151434.png)

おぉ、素晴らしい！
ありがとー！٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
![広告削除画面04](https://user-images.githubusercontent.com/32741225/59896206-96202a00-9422-11e9-82cd-1d9a1a95fe51.png)
150円の選択肢があったらしいので金額を差し替えました！

**Comment by ryotayama** [comment]
◆開発時のメモ
- 自動更新サブスクリプション
https://developer.apple.com/jp/app-store/subscriptions/

- iOSアプリで自動継続課金をリジェクトされないためのチェックリスト（iPhoneの定期購読サブスクリプション）
http://umenon.com/2017/09/21/subscriptionscheck/

- 自動購読課金について
https://ameblo.jp/principia-ca/entry-12071724382.html

**Comment by ryotayama** [comment]
◆Auto-renewable subscriptions for iOS
https://medium.com/swift-india/auto-renewable-subscriptions-for-ios-c17eee19e322

◆How to Set Up and Test an Auto-Renewable Subscription for an iOS App
https://savvyapps.com/blog/how-setup-test-auto-renewable-subscription-ios-app

**Comment by ryotayama** [comment]
対応した！　バージョン3.28でリリース済み！٩( ᐛ )و
