### ISSUE TITLE
各種ボタンについて、タップ時の挙動を統一する

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#312]
バージョン2.97.3（開発版）

https://twitter.com/UmeboshiKantaro/status/1078522387094679552

これプラマイボタンって押しても色変わったりしないっけ？？

これ、「ハイライトの方針を決めて全画面統一する」ってIssue立てた方が良さそう٩( ᐛ )و
たぶん大きいやつは「タップ時に縮小する」、小さいやつは「薄くなる」の２種類に統一で良さそうな気がするけどね！

**Comment by ryotayama** [comment]
@UmeboshiKantaro これやっぱハイライト時の画像を用意してもらう必要がありそう！　また時間のある時にでも対応よろしくー٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
どれどれー？？
＋－とLRボタンかな？？ほかにもありそう？？

**Comment by ryotayama** [comment]
ループ画面の各ボタンが縮小ボタンでよければ、これだけかな٩( ᐛ )و
・再生リストの左矢印ボタン
・＋ボタン
・－ボタン
・Lボタン
・Rボタン

**Comment by KanzakiSaki** [comment]
なるほどなるほど！
44×44ptで作れば大丈夫かな？？
そしてそれぞれオンオフの色違いを作った方がいいのかな…？？

**Comment by KanzakiSaki** [comment]
あ、縮小の方がいいのかな…？？どうだろ？？

**Comment by ryotayama** [comment]
そう！　44x44pxでオン／オフの色違い！٩( ᐛ )و
個人的には、上に書いた５種類の小さいボタンは薄くなるハイライトがいいかなーと思ったけどどうだろう？？

**Comment by KanzakiSaki** [comment]
そうよね！元のボタンが小さいから縮小より明るくなるのがいい気がする！
ちょっと作ってみますー(o`･ω･)ゞ

**Comment by ryotayama** [comment]
対応しました！　バージョン2.99でリリース予定٩( ᐛ )و
