### ISSUE TITLE
コントロール画面の「リセット」ボタンのデザインを角丸に変更する

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#314]
ハヤえもん iOS ver.2.97.3

https://twitter.com/umeboshikantaro/status/1077899058688053250?s=21

「リセット」もボタン風のデザインにした方がいいのかもなぁ…🤔

リセットそうだよね！
‎何でこっちだけテキスト！？って感じするもんね！٩( ᐛ )و

青文字はそのままで、こういう角丸デザインにしたらだいぶ良いかもしれん…🙏

![Image](https://i.imgur.com/hgnVGby.jpg)

おぉ、なるほど٩( ᐛ )و
‎iPhone SEって今どれぐらい余白あるっけ？？

スクショとってみたけどこんな感じ！

![Image](https://i.imgur.com/oKOOhiT.jpg)

おぉ、全然いけそうだね！
‎ありがとー٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.97でリリース予定٩( ᐛ )و
