### ISSUE TITLE
再生中バーを下方向にスワイプしたら、×ボタンを押した時と同じ挙動をするようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#324]
バージョン2.96

https://twitter.com/ryota_yama/status/1075188357586546688

これ下方向にスワイプしたら、×ボタンを押した時と同じ動きしてほしいなー٩( ᐛ )و
![duvwfk3uuaav8qo](https://user-images.githubusercontent.com/6075785/50534309-22414b00-0b7e-11e9-97da-d2e16e28ca2e.jpg)

**Comment by ryotayama** [comment]
@UmeboshiKantaro うめちゃーん、これ半分以上下にスライドされたら「×」ボタンと同じ挙動にしようと思ってるけど、特に反対意見とか「こうした方がいいんじゃない？」とか無いかなぁ？？

**Comment by KanzakiSaki** [comment]
おお！いいと思うよ！
細かい部分は触ってみないとわかんないかも💦

**Comment by ryotayama** [comment]
ありがとー、また対応できたらTestFlightで配信するね٩( ᐛ )و

**Comment by ryotayama** [comment]
対応しました！　バージョン2.98でリリース予定٩( ᐛ )و
