### ISSUE TITLE
イコライザの紐付けを改善したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#334]
ハヤえもん iOS ver.2.98.3

現状ではプリセット名に対して設定が紐付けされているため、ユーザーが「オフ」や「ランダム」という名称でプリセットを追加すると値が保存されなかったり、
外国語に設定変更された際に正常に機能しなくなるケースがあります。

https://twitter.com/umeboshikantaro/status/1079334870327865344?s=21
iPhone英語にしたらプリセットのランダムが反応しなかった…
「プリセットの初期化」したら反応するようになった

いま日本語に戻しましたが…やっぱりランダム反応しなかったです…！

うんうん、各言語ごとの「プリセット名」を元に判定してる！

おお！仕様扱いってことかな？？

そうだねー、改善できるならしたいけど、今んとこ改善方法が無いって感じかな！！

そっかそっか💦
cssみたく共通のクラス名で処理を紐付けできたりしたらいいなぁ。。

そもそもこれ、「iOSの言語設定を変えた時に連動して変わらない」って部分に問題がある気がしてきた……！

あーーそっち…！
確かに現状上書き保存がないから、新しく追加されたプリセットだけ弾いて言語切り替えできそう…？？

これ、そもそもユーザーさんが追加したやつなのかどうかすら分かんないのも問題だよね！
例えばユーザーさんが「ランダム」って名前のプリセットを作ったらランダムになっちゃう(*ノﾉ)

あーーそういうことかぁ…！
多言語じゃなくても危ういねそれは…💦
なんかいい方法があるかもしれないからいったんissue登録しとく？？

うんうん、そうしよー٩( ᐛ )و

データベースの通し番号みたいなので管理して言語が変わっても大丈夫な仕組みに大きく変えないと動かなくなるパターン？

そうだなぁ、そもそも画面上はイコライザのプリセットとして「各スライダーの値を覚えておくだけ」って機能に見えるんだけど、「オフ」と「ランダム」だけ特殊な機能を組み込んでるから、そこらへんの整理からかなー！

**Comment by KanzakiSaki** [comment]
https://twitter.com/ryota_yama/status/1124850175770415107?s=21
↓ひとまず例を出してみる！
![Image](https://i.imgur.com/wmGlfbB.jpg)

あー確かに上のタブわかりにくいよね…！私も最初そこが対応してるって気がつかなかったもんな…！
かなりいいのでは…！？！？
エフェクトと同じで［ｉ］はいらないかも…？？🤔

うぉー、うめちゃんにいいって言ってもらえたー、嬉しい！٩( ᐛ )و

いやベースがいいからわしちょこちょこ手を加えてるだけで、今まであんま構造的な部分はいじってないからなぁ…ｗ
ちょっとそれベースでボタンとか作ってみようかな？？
でも内部的には結構な大改造になるんじゃないかなこれ？？

ありがとー、嬉しい！٩( ᐛ )و
‎中改造ぐらいかな！w

https://twitter.com/ryota_yama/status/1128663764562108418?s=21
流れを考えると順番的には、イコライザ画面に上書きの概念追加→リバーブも詳細画面で一覧化→その他エフェクトも→効果音もって感じかなぁ！٩( ᐛ )و

ああー！イコライザね！
これすごくいいんだけどオフはリストじゃなくてボタンにした方がいいかも？？
流れ的にすごくいいと思う！！
![Image](https://i.imgur.com/43M0dWv.jpg)

おぉ、いいね！　分かりやすい٩( ᐛ )و
‎たしかにオフまで並べ替えられちゃってわけわからんみたいなのもあったから、これでその問題も回避できるね！

ありがとー！
あとはランダムの扱いが難しくてな…💦
新規作成の時にランダムボタン何回か押して選べる感じがいいのかな…
![Image](https://i.imgur.com/2vSoI56.jpg)

おぉ、めっちゃいいじゃん！
‎新規作成にも既存の変更にもランダムボタンあっていいんじゃないかなぁ！٩( ᐛ )و

変更もたしかに！！ありがとう…少しずつ見えてきたね…！

ありがとー、出てきた中だとは 少なくとも追加ボタンはうめちゃんに作ってもらう必要がありそうかな！　また落ち着いたら……！٩( ᐛ )و

**Comment by ryotayama** [comment]
◆開発時用のメモ
①テンプレートに「ｉ」ボタンを追加して、カスタマイズ画面に遷移できるようにする
②「ｉ」ボタンから遷移した場合は、「上書き保存」ができるようにする（保存しない時用にキャンセルボタンもいるかも）
③テンプレート画面右下に「＋」ボタンを追加して、カスタマイズ画面に遷移できるようにする
④「＋」ボタンから遷移した場合は、「新たに保存」ができるようにする
⑤イコライザ画面上部の「テンプレート」「カスタマイズ」スイッチを削除
⑥「オフ」をボタンに変更し、テンプレートからは削除
⑦「ランダム」をカスタマイズ画面のボタンとして追加し、テンプレートからは削除

**Comment by KanzakiSaki** [comment]
こんな感じかなっていうのを書き起こしてみました

**イコライザ一覧画面（オフ）↓**

![イコライザ一覧画面01_1](https://user-images.githubusercontent.com/32741225/58460112-e8459680-8167-11e9-9adf-9155760cf997.png)
　
　
**イコライザ一覧画面（ベースの耳コピ）↓**

![イコライザ一覧画面02_1](https://user-images.githubusercontent.com/32741225/58460158-fa273980-8167-11e9-91ce-4136436604f3.png)
　
　
**イコライザ詳細画面（ベースの耳コピ）↓**

![イコライザ詳細画面（ベースの耳コピ）](https://user-images.githubusercontent.com/32741225/58461237-2479f680-816a-11e9-9aa1-b43f89d50378.png)

上書き保存が右上の「完了」、キャンセルが左上の「戻る」になっています。
（オプション設定画面の「速度の表示範囲」「音程の表示範囲」と合わせた形）
「別名で保存」があるといいのかも？？
もしくは一覧のアクションシートから「テンプレートの複製」機能があると親切かも。
　
　
**イコライザ新規作成画面↓**

![イコライザ詳細画面（新規）](https://user-images.githubusercontent.com/32741225/58461286-41aec500-816a-11e9-958d-401e6016c3c0.png)
　
右上の「保存」ボタンを押すと名称を設定するポップアップが出る仕組み。

**Comment by KanzakiSaki** [comment]
#539 にイコライザのアクションシートに関するissueを登録しました！

**Comment by ryotayama** [comment]
対応しました！　バージョン3.20でリリース済み٩( ᐛ )و
