### ISSUE TITLE
複数選択モードに選択中の再生リスト名を表示したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#348]
ハヤえもん iOS ver.2.98

https://twitter.com/UmeboshiKantaro/status/1081206316725547008
これ使ってて気が付いたけど、表示中の再生リスト名を上に表示した方がわかりやすいかな？？
でもこれはまた次の段階でもいいかも…？？ 

![Image](https://i.imgur.com/0dqo84p.jpg)

![Image](https://i.imgur.com/O7eP32m.jpg)

おぉ、それめっちゃいいね٩( ᐛ )و
‎よし、次の段階で！👍

**Comment by ryotayama** [comment]
関連Issue: #375 複数選択モードに「すべて選択」ボタンがほしい

**Comment by ryotayama** [comment]
対応した！　バージョン3.04でリリース予定٩( ᐛ )و
