### ISSUE TITLE
複数選択モードへの移行時の曲名長押しをもっと短い時間にしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#354]
バージョン2.99

https://twitter.com/UmeboshiKantaro/status/1083331306946060288
操作性みてたらGoogleフォトの方が長押し判定が短いみたい？
こういう部分も調節できれば、もう少し気付かれやすくなるかも？？ 
（動画あり）

おぉ、長押し時間は簡単に調整できるよー！
合わせてみるね👍

**Comment by KanzakiSaki** [comment]
ありさんからの質問、転記しておきます〜
https://github.com/ryotayama/Hayaemon_iOS/issues/372#issuecomment-454640959

**Comment by ryotayama** [comment]
対応した！　バージョン3.04でリリース予定٩( ᐛ )و

**Comment by arigayas** [comment]
何秒から何秒に変化したのか気になりました。

**Comment by ryotayama** [comment]
おぉ、ありさんごめん！
質問見落としてた！
0.6秒だったのを0.2秒に変更したよ！

**Comment by arigayas** [comment]
三分の一の長さにしたのなら大分違いますね。
