### ISSUE TITLE
複数選択モードへの移行をメニューからできるようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#355]
バージョン2.99

https://twitter.com/gakihure/status/1083322600204320768
✔︎付ける感じで選択削除出来たらいいかなーと

それはあるよ、曲名長押しで👍

あぁ…
その機能忘れてた…

やはりわかりにくいのでは…？

ツイッターかLINE@か忘れちゃったけど、他にも「複数選択モードの存在に気づかなかった」って人いたなー！
長押し気づかれにくい問題だね……！

操作性みてたらGoogleフォトの方が長押し判定が短いみたい？
こういう部分も調節できれば、もう少し気付かれやすくなるかも？？

おぉ、長押し時間は簡単に調整できるよー！
合わせてみるね👍
とはいえ、Googleフォトにも「写真を選択」メニューはあるし、VoiceOverユーザーさんの事まで考えると明示的なメニューもあった方がいいのかもね！
（iPhone SE画面の事を考えると縦幅が収まらないっていう別の問題にぶち当たるけど💦）

ありがとー！
縦幅はスクロールさえできれば問題ないよ👍
アイコン作ってみようかな！

おぉ、まじか嬉しい……！٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
#366 に実装方法がありますのでリンクしておきます〜！

**Comment by ryotayama** [comment]
対応した！　バージョン3.02でリリース予定٩( ᐛ )و
