### ISSUE TITLE
表示中の再生リストタブに「…」ボタンをつけてメニューを出せるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#366]
ハヤえもん iOS ver.2.99

https://twitter.com/UmeboshiKantaro/status/1083751369276674049

再生リストタブをもう少しタブっぽくしたいなーという妄想です。。

![Image](https://i.imgur.com/cAKwkhA.jpg)

https://twitter.com/UmeboshiKantaro/status/1083925707481219072

これ今再生リストタブの長押しでメニュー出てくるんですけど、
表示中のタブだけ明示的に「…」ボタンをつけてあげたらその中に「曲を選択」ってメニューを入れたらいいんではと…

そしたら「曲順の並べ替え」メニューもこの中の方が自然なのでは…？？

あっアートワークの一括設定（）

![Image](https://i.imgur.com/c49klQe.jpg)

![Image](https://i.imgur.com/XkzxZuI.jpg)

https://twitter.com/UmeboshiKantaro/status/1084006567224066048

①表示中の再生リストタブの「…」からアクションシートを出す
②それに伴って再生リスト一覧の「…」のメニューも統一
③表示中の再生リストタブの「…」に機能を追加

という段階を考えてみた。。

![Image](https://i.imgur.com/U7OcxAo.jpg)

![Image](https://i.imgur.com/f8buR3H.jpg)

![Image](https://i.imgur.com/rMQw7fZ.jpg)

![Image](https://i.imgur.com/IJJ8RBv.jpg)

なんか色々説明したりてないけどごめん／(^o^)＼（再生リストコピー実装されてるやんとかもろもろ

とりあえず並べ替えと曲の選択はここから出した方が、曲からのメニューよりもしっくりきそうな気がした…！

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1084008204399333377
うんうん、だいたい分かるけど、「再生リストのコピー」が選ばれたら右隣にコピーする感じでいいかなぁ？？٩( ᐛ )و

「だいたいわかる」ってすごくない…！？！？

コピーは右隣めっっっっちゃいい…！！

再生リスト作成時に出てくる感じで、入力欄の末尾に「のコピー」って自動で入ってたりしたら神…！！！！
![dwss4kduuaaylmp](https://user-images.githubusercontent.com/6075785/51781247-7a597600-2159-11e9-92ff-192917574f14.jpg)

おっけー٩( ᐛ )و
あとこっちは削除でいいかなぁ？？
![dwsv_fqucaazota](https://user-images.githubusercontent.com/6075785/51781250-86453800-2159-11e9-98db-a4dcf71da142.jpg)

そこね…！毎回「このメニューはどこに行ったの！帰して！」って言われると思って悩むけど、なくしてもらえると…嬉しいです…すぐじゃなくてもいいので🙏😭

んうん、とはいえ消すタイミングを逃しそうだから、再生リストの「・・・」メニューに並べ替え機能付けた時点で消しちゃおーかな！٩( ᐛ )و

ありがとう…😭🙏
私もっとハートを強く持つことにします…💪💥💗

**Comment by ryotayama** [comment]
対応した！　バージョン3.02でリリース予定٩( ᐛ )و
