### ISSUE TITLE
再生モード長押しでスライド選択できるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#367]
ハヤえもん iOS ver.2.99

https://twitter.com/ryota_yama/status/1083591749249884160?s=21
ここ、長押ししたらニョキッと出てきてそのまま指をスライドして変更したい感あるなぁ٩( ᐛ )و

![Image](https://i.imgur.com/UJSS8NQ.jpg)

https://twitter.com/umeboshikantaro/status/1084728999647924225?s=21
とりあえず再生モードの方はこんな感じで作ってみてるよ！
でも今どこが選択中でどこが指で押さえてるやつかわかりにくいなー💦

![Image](https://i.imgur.com/xupuMK5.jpg)

![Image](https://i.imgur.com/5Rht4Ld.jpg)

![Image](https://i.imgur.com/onLm1wJ.jpg)

おぉ、そういう感じか！！
いま選択中じゃないやつが下に２つ出てくるのをイメージしてたけど、分かりづらいかなぁ？？

全部出してあげたいなーと思ったのは、長押しから「やっぱり今のモードでいいや」ってのができるようにかな？

選択中が常に1番上で、下に選択してないのが出ると嬉しい…
から、こうかな？？

![Image](https://i.imgur.com/BHhHtrW.jpg)

![Image](https://i.imgur.com/O68j9Mg.jpg)

![Image](https://i.imgur.com/v5wSwn2.jpg)

あれ、やっぱイメージ合ってるのかなぁ？？
‎せんせー、全曲ループがオンになってる状態から長押しするとどうなりますか？？٩( ᐛ )و

ボタンの並びが変わるよね！！あってる気がするごめんｗ

あー、並び変わるよね！！
‎ごめんごめん勘違いしてた！！
‎フォーカス状態も含めてめっちゃいい感じ٩( ᐛ )و

これ選択中のブルーのアイコンいるのかな…？？グレーのままでいいか…？？

ブルーは無しでいいかもね！！
ちょっと気になるのはリピート無しが下に来たときのフォーカス（指が上にある状態）をどう表現するかかなー！！
これも枠線が付くのかなぁ？？

こんな感じ？？
１曲リピートの時は真ん中、全曲リピートの時は一番下かな？

![Image](https://i.imgur.com/XNiCgu0.jpg)

![Image](https://i.imgur.com/ZJzwptc.jpg)

あー、とても良い！　天才……！٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.02でリリース予定٩( ᐛ )و
