### ISSUE TITLE
再生ボタンの長押しで「逆回転再生」が選べるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#368]
ハヤえもん iOS ver.2.99

https://twitter.com/ryota_yama/status/1084397916687458309?s=21
‎「逆回転再生」は再生の方向を逆にするんだけど、エフェクト画面の下の方からしかアクセスできない。
‎これに対して、エフェクトの並べ替え機能を付けるってアプローチを取ろうとしてるんだけど、再生ボタン長押しで「逆回転再生」ってボトムメニューが出てきてくれてもいいかもと思い始めた٩( ᐛ )و

![Image](https://i.imgur.com/vxCIndg.jpg)

![Image](https://i.imgur.com/fVHXBsw.jpg)

それ懐かしのやつ！
https://twitter.com/UmeboshiKantaro/status/875916096804536320

わお、まじか全然覚えてないww
‎長押しからボトムメニューで変えれる分にはデメリットないから付けとこーか٩( ᐛ )و

https://twitter.com/umeboshikantaro/status/1084739937176453120?s=21
せっかくだから逆回線再生の長押しも画像作ろうかと思ったけど、さすがにラベルないとわかりにくいかな…？？

![Image](https://i.imgur.com/nGIe4oq.jpg)

たしかにこれはムズイねー！！
こっちはボトムメニューかなぁ？？

そっかぁ〜そしたらアクションシート用のアイコン作ってみようかな？？

わーい、嬉しい٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
https://twitter.com/UmeboshiKantaro/status/1085133374165925888
再生ボタン長押しのアクションシート、アイコンを作ってみた！ ここまではいらないかな？どーだろ？？

![default](https://user-images.githubusercontent.com/32741225/51225939-53988400-1990-11e9-9d6a-de4836db939b.png)

あー、思いつかなかった！
めっちゃいいと思う٩( ᐛ )و

これアクションシートのいいタイトル思い浮かばないなー、、 「再生／停止」 …どうだろう？？

![02](https://user-images.githubusercontent.com/32741225/51225962-75920680-1990-11e9-8d49-cfbf193ffde8.png)

**Comment by KanzakiSaki** [comment]
関連issue #284

**Comment by ryotayama** [comment]
対応しました！　バージョン3.01でリリース予定٩( ᐛ )و
