### ISSUE TITLE
再生リストのテーブル内にそれぞれの曲の長さを表示させたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#369]
ハヤえもん iOS ver.2.99

https://twitter.com/r_121_n_7/status/1084649041189756929?s=21
こんにちは！
あの、
この画面で、何分あるか分かるとすごく便利です…

![Image](https://i.imgur.com/rUdUPOA.jpg)

ふむふむ！
再生中の曲の時間っていうよりも、再生リスト内のそれぞれの曲の長さが分かると嬉しいって感じですかね？ 

あーーそれわかります！
前に自分も要望出したことあります…
こういう感じですよね？？（別アプリのスクショ

![Image](https://i.imgur.com/v8H4GzB.jpg)

そうですそうです！！
うめぼしさんのおっしゃる通りです✨

いろはさん、ありがとうございます！
‎うめちゃんもありがとー٩( ᐛ )و
‎これ実装したいね……！

実装されたら飛び跳ねそう…！
そして再生リストの一覧にもトータルの長さが出るとまじで嬉しい（通勤通学の時間に合わせてリスト作れる（もう通勤通学しないけど

![Image](https://i.imgur.com/NskCDwj.jpg)

おっけー、こっちはレイアウト的にはここでいいのかなぁ？٩( ᐛ )و

![Image](https://i.imgur.com/FjZNolX.jpg)

曲の長さは…そんな無茶苦茶な桁にならないよね？？
mm. ssでいいよね…？？
そしたら🔒の右側で大丈夫だと思う！

はーい٩( ᐛ )و
‎ちなみに２時間ぐらいのオーディオブックを聴いてる人はいそうだから、mmの部分は３桁あった方が良さそう！

あーーオーディオブックなるほど…！！
ちょっと組み合わせてみて判断しないとな💦
003.15とか書いてあるとキモチワルイし…ちょっと配置してみます💪

わーい、よろしくー٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/RknCtfh6FPzJJ2U/status/1095291024077803520
機能要望です。
曲ごとに演奏時間が表示して欲しいです。

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1096311606655385601
先月要望の上がっていた、再生リストに曲の長さを表示したレイアウトを作成中。
なるべく省略文字数を増やしたくないので、端末内／クラウドマークは縮小してアーティスト名の段に入れてみるなど。。
![dzbhdqkvsaadggl](https://user-images.githubusercontent.com/6075785/52921358-85b75000-3359-11e9-9087-ab99c10cf360.jpg)

ABループ画面の再生時間の表示や、コントロール画面の速度音程連動ボタンなどもそうだったけど、画面に一つ要素が増えるというのはなかなか大変💦

おぉ、いいね٩( ᐛ )و
100分以上の時にどうなるかだけ気になった！

それなのだけど、以前遊んでいたゲームアプリで、限られた横幅に対して桁が変動する数値の場合、動的にフォントサイズが変わる、というのを見たことがありまして…
こういうことって可能なのでしょうか？？
![dzbm3hiuwaaqssz](https://user-images.githubusercontent.com/6075785/52921363-9962b680-3359-11e9-8eab-a51132268280.jpg)
![dzbm3hiuuaebvpx](https://user-images.githubusercontent.com/6075785/52921364-9bc51080-3359-11e9-85c4-515bc30b7fd8.jpg)

ぜんぜんできるよー٩( ᐛ )و

うぉー、そうなんだね！！Σ(ﾟДﾟ )
そしたらアイコンを修正しようと思うのだけど、端末アイコンとクラウドアイコンかなり小さい気もするけどどうかなー💦

わーい、楽しみ٩( ᐛ )و
今回はボタンじゃないから44ptルールは気にしなくていいよね！！
ここらへんのアイコンと同じぐらい存在感があれば問題ないんじゃないかなぁ？？
![dzcxzkuuyaardpf](https://user-images.githubusercontent.com/6075785/52921373-aed7e080-3359-11e9-873f-67250d497bb9.jpg)

なるほどー、それはわかりやすい指標！
作ってみます〜💪

わーい、一応Appleのガイドライン系ザッと目を通してみたけど、画像サイズに関するガイドラインは無さそうだったよ！
よろしくー٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.08でリリース予定٩( ᐛ )و
（再生リスト単位の合計時間を表示させる対応は別Issue対応）
