### ISSUE TITLE
複数選択モードの長押し判定時間を短くしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#372]
ハヤえもん iOS ver.2.99

https://twitter.com/gakihure/status/1083314784634777600?s=21
ハヤえもんって一括削除あったっけ…？

これがMAXで、全再生リストの一括削除的なのは無いね！

そかー
あったら良さそうなのは✔︎付ける感じで選択削除出来たらいいかなーと

それはあるよ、曲名長押しで👍

あぁ…
その機能忘れてた…
やはりわかりにくいのでは…？

ツイッターかLINE@か忘れちゃったけど、他にも「複数選択モードの存在に気づかなかった」って人いたなー！
長押し気づかれにくい問題だね……！ 

https://twitter.com/UmeboshiKantaro/status/1083331306946060288
操作性みてたらGoogleフォトの方が長押し判定が短いみたい？
こういう部分も調節できれば、もう少し気付かれやすくなるかも？？
（動画あり）

おぉ、長押し時間は簡単に調整できるよー！
合わせてみるね👍

関連issue #366

**Comment by arigayas** [comment]
ソースコード上では今何秒なのだろう？

**Comment by KanzakiSaki** [comment]
ありさんごめん、#354 と重複していたのでcloseするね💦

**Comment by arigayas** [comment]
Don't worry. (ATOKさんが「どんまい」と入れたら表示された)
