### ISSUE TITLE
複数選択モードに「すべて選択」ボタンがほしい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#375]
ハヤえもん iOS ver.3.00

https://twitter.com/satoupawapuro12/status/1086577866882465793?s=21
こんばんは。
ハヤえもんを使ってて感じたのですが、曲名長押しで出てくる選択項目で全部選択ってできるんですか？

やるとしたらこんな感じで下につけるかなーって考えてました！
でも再生中との兼ね合いが悩ましいからどうだろう？？

![Image](https://i.imgur.com/RHkvsib.jpg)

うぉー、ありがとう！
なるほどね…！
たしかに帯二重は悩ましいねー！
「すべて選択したい」って事は再生リストの曲全部を対象に操作したいって事だから、再生リストに付ける予定の「・・・」メニューから同じ操作（アートワーク設定とか、各画面の設定を保持とか）ができればOKだったりするかなぁ？

#366 
これだね！

確かにこれならアートワークや各画面の設定保持はできるけど、
リストの中身全部を別のリストに丸ごとコピーしたり移動することはできないから、何かしら考えたいなー。

あとはドラッグしながら複数選択できるようになると、多少近づけるって感じかな？？

**Comment by ryotayama** [comment]
https://twitter.com/satoupawapuro12/status/1086611883065372672
こんばんは。
なるほど。これはいいですね。でも帯2つはちょっと...。素人の僕が提案するのもアレですが、こんな風にするのはいかがでしょう？
![dxrrvr8v4aawmle](https://user-images.githubusercontent.com/6075785/52218346-d486d380-28dd-11e9-938d-034ab891834b.jpg)

ありがとー、そこ使う予定なんだよねー👍
https://twitter.com/UmeboshiKantaro/status/1081206316725547008

すべて選択の件、Googleフォトにならうなら、再生リスト名の左側にチェックできる欄をつけて、それがタップされたらすべて選択って扱いにするのもアリかもね٩( ᐛ )و
![dx-r0byvsaypq41](https://user-images.githubusercontent.com/6075785/52218400-ecf6ee00-28dd-11e9-879e-5e9bcc894a70.jpg)
![dx-r0bzvaaahb6m](https://user-images.githubusercontent.com/6075785/52218406-eff1de80-28dd-11e9-9d6b-788b6691e687.jpg)

おー！なるほど！確かにこれだと「あ、ここで全部選べるんだ」っていうのが直感的にわかりますね。実装楽しみにしてます。

https://twitter.com/UmeboshiKantaro/status/1090076408733347840
これ見落としてたけど、めちゃくちゃええやん！びっくり！
https://twitter.com/ryota_yama/status/1089778553262989312

ねー、いいよねー！
また落ち着いた時にでもボタン画像作ってくれたら嬉しいな٩( ᐛ )و

おお、最初に標準パーツあると思ってなくて用意してた「select_button」ってやつ使えないかな？？
でもデザイン違うと違和感あるか！トレースして作り直した方がいいかな…？

うんうん、テーブルの方をiOS純正にしたから、それに合わせた方が違和感は無さそうな気がする٩( ᐛ )و

了解です！(o`･ω･)ゞ

「汎用ボタン」の中にPDFで入れておきました〜〜！確認お願いします🙏

おぉ、ありがとー٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1090870930115416064
全選択ボタンなんとか詰め込んでみたけど
再生リスト名、iPhoneSEだと2文字か…

あっ下の×ボタンも丸フチなしにしよう
![dyomtjov4aatxtz](https://user-images.githubusercontent.com/6075785/52218576-4d862b00-28de-11e9-8396-c45ae510f2e0.jpg)
![dyomuktuwaapz_8](https://user-images.githubusercontent.com/6075785/52218582-4eb75800-28de-11e9-8866-18079ccefef5.jpg)

うぅ、２文字……スクロール……は変か、なんでもないっす(*ノﾉ)w

スクロールしないでいいよｗｗ
ボタン類の両脇詰めれるなら多少は増やせるかもしれんけど、それでも3文字が限界かもｗ

おっけー、これそんなに実装難しくないと思うから、次のバージョンで付けてみるねー٩( ᐛ )و
あ、そっか、アプデ申請したから次のバージョン開発できるんだ！　ワクワク！

うぉー嬉しい！！
×ボタンもあとで書き出しますね！！

わーい、ありがとー٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.05でリリース予定٩( ᐛ )و
