### ISSUE TITLE
曲の長押しスワイプで複数選択が一気にできるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#376]
ハヤえもん iOS ver.3.00

https://twitter.com/ryota_yama/status/1082180129932042245?s=21
ハヤえもんの複数選択、まとめて選択するときに不便だからもっと楽にできるようにしたいなーと思ったら、Googleフォトはちゃんとそうなってたね！
‎よし、パク……参考にしよう٩( ᐛ )و

まさか…スワイプ 選択が実装に…！？！？

もちろん！
‎これ絶対いるでしょー٩( ᐛ )و

〜〜

#375 に関連して↓

https://twitter.com/umeboshikantaro/status/1086622823718633472?s=21
あとはドラッグしながら複数選択できるようになると、多少近づけるって感じかな？？

うんうん、ドラッグ複数選択の操作性がすごく良ければ（最下部まで持っていくとスピードが上がるとか）、それで良さそうな気もするよね！
そこらへんは実装してみないとどこまで追求できるか分かんないから、色々また落ち着いた時に実験してみるね👍

**Comment by ryotayama** [comment]
対応した！　バージョン3.10でリリース予定٩( ᐛ )و
