### ISSUE TITLE
iTunesのファイル共有で表示されるアプリ内のファイル名を曲のタイトルにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#377]
ハヤえもん iOS ver.3.00

https://twitter.com/satoupawapuro12/status/1086492617888526341?s=20
早速ファイル共有試してみました。一覧にハヤえもんのアプリが出てきたときは感動しました！
早速提案なのですが、右側の一覧の名前のところがアプリ内の曲名と違うので同じくして欲しいです。あと、できればフォルダに対応して欲しいです。フォルダを入れたら新しく再生リストができるみたいな？

![Image](https://i.imgur.com/Wyla6RQ.jpg)

うぉー、前向きな提案ありがとー！
考えてみまーす👍

https://twitter.com/ryota_yama/status/1087003919476154369?s=21
iOSの仕様がとてもいけてない事が発覚w
‎ただ、少なくともタイトル／アーティスト名をちゃんと引き継げるようにするのと、「recorded」っていう無機質な名前をタイトルにするようにするのはやりたいな٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1090111795849682944
#ハヤえもんAppStoreでのやりとり
さらに最高！ ★★★★★
投稿者: あーぼ2 – 2019年1月28日
先日ついに、ABループ画面での、経過時間表示が可能となり、感謝感激です！
…あとは、itunesでのファイル共有を待つばかりです。
開発速度が上がってきているとのこと、期待しておりますです。

と書いたのはつい先日…

早くもitunesでのファイル共有への対応、ありがとうございます！
もう完璧、と思ったのですが…

Windows10パソコンで、iTunes を開いて、iPhoneをつなぎ、ファイル共有を選ぶと、入っている音のファイルが「recoreded1.m4a」
というファイルになっています。
(数字は、連番で1から順に勝手に付いています)
これでは、なんのファイルだか分からないので実用になりませ〜ん。
ハヤえもんのファイル名変更で名前をつけた、日本語も含めたファイル名で表示されて、しかもmp3で転送されるようにはできないものでしょうか？

パソコンの方からファイル共有を使って転送したmp3ファイルの方は、そのままのファイル名で、mp3として転送されているのでとてもいいのですが、ハヤえもんのループ画面で切り取ったファイルは、m4aという拡張子になるようです。

あと、タイトルに加えてアーティスト名も書き出せるとなお嬉しいのですが…

うーん…惜しいっ！
σ(^_^;)
もうひと息！

デベロッパの回答 – 2019年1月29日
あーぼ2さん、どーも！　りょーたです٩( ᐛ )و
おぉ、早速お試しくださって嬉しいです！
そして色々と改善点をあげてくださってありがとうございます！
順次対応していきますね。
ちなみにM4Aについては、iOSの標準的な形式なんですよねー。
他の形式でも書き出せるように考えてみますね！
他にも気になる点などありましたら、いつでもご連絡くださいね。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

**Comment by ryotayama** [comment]
対応した！　バージョン3.08でリリース予定٩( ᐛ )و
