### ISSUE TITLE
全く加工してない音源のエクスポートをもっと速くしてほしい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#378]
ハヤえもん iOS ver.3.00

https://twitter.com/lukuon/status/1077248213197873159?s=21

すみません、ちょっとしたことなんですが、音源をおすそ分けというかメンバー内で共有することが多くて、エクスポート機能をよく使うんですが、その時素の音源を送るときにもエンコードしてる風のプログレスバーがでて少々待ち時間が出てしまうのをどうにかしていただけないでしょうか！

おぉ、たしかに٩( ᐛ )و
‎エフェクトが何もかかってない時はもっとスピーディーに書き出せそうな気がしますね！
‎ありがとうございます、考えてみますね！

**Comment by arigayas** [comment]
タイトルの漢字を変えました。

**Comment by ryotayama** [comment]
対応した！　バージョン3.54でリリース予定！
