### ISSUE TITLE
アートワークを拡大表示したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#388]
ハヤえもん iOS ver.3.00

https://twitter.com/maddnes40227162/status/1085436985504817153?s=21

アートワークについてですが、

通常タップで表示
長押しで変更

みたいな機能が欲しいです。↓

![Image](https://i.imgur.com/LM0yUix.jpg)

**Comment by ny-yamana** [comment]
アートワークの大きさを自由に変えられるようにしたいのですが...
https://mobile.twitter.com/maddnes40227162/status/1130449253057191936?s=21

**Comment by ny-yamana** [comment]
アートワーク変更が出来るようになってから、誤タップで｢アートワークを変更｣の表示を出してしまうことがあります
(キャンセルを押せばいい話じゃないかといわれたらそこまでですが…)
アートワークをコロコロ変えることはあまりないと思うので、長押しで、もしくは別画面から変更、というふうにして頂けたらうれしいです
https://mobile.twitter.com/i/web/status/1097154454804082689

**Comment by ny-yamana** [comment]
私としては、長押しメニューよりも、タップして拡大した時に編集ボタンが出てきてくれるといいかなーって思ってます(*･ω･)ﾉ
ツイッターのアイコン編集がそんな感じです↓
https://mobile.twitter.com/umeboshikantaro/status/1097157538468945920

**Comment by ryotayama** [comment]
対応した！　バージョン3.66でリリース予定！
