### ISSUE TITLE
iTunesのファイル共有からのフォルダの追加に対応してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#390]
バージョン3.01

https://twitter.com/satoupawapuro12/status/1086492617888526341?s=20
早速ファイル共有試してみました。一覧にハヤえもんのアプリが出てきたときは感動しました！
早速提案なのですが、右側の一覧の名前のところがアプリ内の曲名と違うので同じくして欲しいです。あと、できればフォルダに対応して欲しいです。フォルダを入れたら新しく再生リストができるみたいな？
![68747470733a2f2f692e696d6775722e636f6d2f57796c613652512e6a7067](https://user-images.githubusercontent.com/6075785/51885385-8c901a00-23ce-11e9-89bb-868ca1174efe.jpeg)

うぉー、前向きな提案ありがとー！
考えてみまーす👍

**Comment by arigayas** [comment]
#377 の重複？かと思ってしまったw

**Comment by ryotayama** [comment]
「Issueはなるべく細かく分けろ！」っていう鉄則を守ったよw

**Comment by ryotayama** [comment]
対応した！　バージョン3.16でリリース済٩( ᐛ )و
