### ISSUE TITLE
速度と音程をもっと変えられるようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#393]
バージョン3.01

https://twitter.com/ZeroP2525/status/1090269916454768640
慣れは恐ろしく、1時間程度の音源(例えばラジオ)から特定の音を探すとき(音楽探しやCM飛ばし)は10倍でも遅く感じるかも。高速にしても音楽と会話は明確に違うので、多分60倍(周波数も60倍)でも探せます。
カセットテープの時代の早送り再生は10倍程度だったけどイラつきました。

この用途のためには専用の操作(カセットみたいに時々逆再生とか)が必要になってくるので、なんかの時にでも。
案外こう言う高速検索のための操作できるソフトが少ないのも事実。

了解です！　ハヤえもんでは、やろうと思えば速度は最大5000%、音程は♯/♭60まで上げる事ができるので、また折を見てもっと変更できるようにする事を考えてみますね٩( ᐛ )و

**Comment by arigayas** [comment]
ひろや/ZeroP @ZeroP2525 さんからのリプライを追記。

ありがとうございます。よろしくお願いします。#♯/♭60 が限界だと3200%に抑えたほうがいいかもですね。(試さないと分からないけど鳴らない音が出ると高速のなかうまく探せるかよく分からない)

**Comment by ryotayama** [comment]
対応した！　バージョン3.03でリリース予定٩( ᐛ )و
