### ISSUE TITLE
コントロール画面に速度と音程を連動できるボタンをつけたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#396]
ハヤえもん iOS ver.3.02

https://twitter.com/UmeboshiKantaro/status/1090150905935126529
エフェクトの「再生周波数」が初心者にとってはわかりにくいので、なんとかコントロール画面で表現できないか模索している…

要するに速度と音程が連動して表現されればいいのではと思い、
トグルボタンなど設置してみるが、コレジャナイ感がすごい

![Image](https://i.imgur.com/DL09LMv.jpg)

![Image](https://i.imgur.com/4BHWic9.jpg)

![Image](https://i.imgur.com/W2lwG8m.jpg)

こうか！？！？

速度が設定されている場合は、速度に対して音程を連動。

![Image](https://i.imgur.com/CcwS0yN.jpg)

![Image](https://i.imgur.com/DxeKmxC.jpg)

おぉ、いいじゃん٩( ᐛ )و
‎上の鍵マークがタップでオン／オフ切り替える方式だから、標準コントロール無しでもいいかもね！
‎あとは再生周波数を変えつつ速度／音程を変えたいって人もいそうだから、エフェクト画面の再生周波数は消さずにこの連動機能を付けた方がいいかも！

今続きを書いてたとこだったｗ
どうかな？？
https://twitter.com/umeboshikantaro/status/1090156851709112321?s=21

あぁ、いいじゃん！！
ちなみにこれ左右の位置は中央揃えなのかな？？
iPadだと結構ポツンとある感じになっちゃうのかなぁ？？

真ん中のつもりだったけど微妙かなー？？
エフェクトの「再生周波数」は残す方向で自分も賛成です(o`･ω･)ゞ

なんか画面がでかすぎて、そもそも違和感を感じるのはそこだけじゃない気がしてきたからいったん良いと思う！٩( ᐛ )و
![Image](https://i.imgur.com/QMuRkKn.jpg)

でかいなーｗｗ
そもそも感があるね…これはこれで全体的に考えないとだわぁ😅
じゃあ一旦位置はこんな方向で、パーツ作ってみようかな！

ありがとー！
‎連動機能楽しそう٩( ᐛ )و

これって速度／音程どちらかの数値が動かされたら、そっちに連動して動いてくれるのを想定しているのだけど、仕様として大丈夫かな？？

ドラムロールやボタンタップはそれでいいと思う！
‎グラフの部分は横方向の指の動きに追従するのか、縦方向の指の動きに追従するのかは決めといた方がいいかな！٩( ᐛ )و

たしかに！
速度がロックされてたら音程に合わせて、音程がロックされてたら速度に合わせて…
どっちにもロックがかかってない時はどうなるのがいいのかしら。。

「ロック」の意味が複数生まれちゃうから、連動ボタンが押された時点でロックは自動的に両方解除かなーと思ったけどどうだろ？？

おーそうか！なんか混乱してくるなぁｗ

これ実物ありきで「もっとこうした方が……」って語り合った方が話が噛み合うと思うから、次のバージョンでいったん付けてみて操作感ベースで話しあうのはどうかなぁ？٩( ᐛ )و

それもそうだね！ｗ
ありがとー！ボタン作ってみる！💪

はーい、よろしく٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
https://twitter.com/ryota_yama/status/1091737526665076736?s=21
コントロール画面に謎のボタンが現れた٩( ᐛ )و

![Image](https://i.imgur.com/EGOlO15.jpg)

https://twitter.com/ryota_yama/status/1091737865002745856?s=21
押すとこんな感じ٩( ᐛ )و

![Image](https://i.imgur.com/TkvMhDs.jpg)

うぉおおスゲエ！！( ﾟωﾟ；)これつけてくれたんだ！！ありがとう！！

うんうん、いったんボタンだけねー٩( ᐛ )و
‎速度と音程の相関関係が難しくて、ひたすら勉強してる(*ノﾉ)
https://ja.m.wikipedia.org/wiki/2%E3%81%AE12%E4%B9%97%E6%A0%B9

2の12じょうこん…！？！？わからなすぎる…😂

でしょ？ww
200%の時は♯12って事は150%の時は♯6かな！とか思ってたんだけど、どうやら違うらしくてパニックww

https://twitter.com/recarendraven/status/1091896334905307137?s=21
12 Root 2の計算方法なら知ってるーよん

乗根は変形すると巾乗にできる。それをうまく使ってやれば良い。
たとえば、平方根(2 Root ◯)
これは、巾乗で表すと◯ ^ (1/2)になる
四乗根(4 Root □)も同じ。巾乗だと□ ^ (1/4)

じゃあ、今回は12 Root 2
これを当てはめると、2 ^ (1/12)
計算するとこう

![Image](https://i.imgur.com/QfJ9ZIV.jpg)

ありがとう、なんか累乗根とかもはや記憶が皆無だな！
‎powって関数使って実装してみてる٩( ᐛ )و

https://twitter.com/12guitar21/status/1091897826064293888?s=21
ギターで考えたらめっちゃわかりやすいですよ。

ふむふむ！
フレットが半音単位で分かれてるからかな？
半音階から速度を割り出そうとしたら、pow(2.0, semitone / 12.0)で速度が求まる感じで合ってるかなぁ？

semitoneって半音階ってことだと思うんですけど、値は周波数ですか？
とりあえず2の12乗根なので
pow(2.0, 1.0/12.0)なのはわかりますが、
semitone* pow(2.0, 1.0/12.0)じゃないのかなって思いました

https://twitter.com/hone1221/status/1091901609938890752?s=21
A(440Hz) = 0, A♯=1,...
として、
音程(n)[Hz]=440*2^(n/12) (音程(0)=440,音程(12)=880)
っていう感じの指数関数なのに対し、
再生速度と音程は比例しているから、
再生速度2倍 <=> 音程2倍 <=> n += 12
という感じになります(平均律(440Hz)の場合)。
物理的にはこんな感じだと思います。

https://twitter.com/ryota_yama/status/1091902326648893446?s=21
みんなさすが理系……！
https://twitter.com/hone1221/status/1091901609938890752?s=21
Kくんのこの理論から、まさにpow(2.0, semitone / 12.0)で再生速度が求まるのかなーと思ったんだけど、違うかなぁ？ 

音速[m/s]、波長[m]、周波数[Hz]の関係式として、
音速=波長*周波数
で、音速を一定とすると波長(1/n)倍に対して周波数はn倍しないといけません。
再生速度n倍というのはn倍速く進むわけだから、波長が(1/n)倍されます(RT元で音程n倍と書いてしましましたが正しくは周波数n倍でした)。(続く)

よって再生速度n倍<=>周波数n倍となります。
なので、元が再生速度1倍であるときならば、音程+x(♯方向で+1、♭方向で-1)したときの再生速度n倍は
n=2^(x/12)
で求められます。しかし、再生速度自体は元が何倍であったかわからないと求めにくいです。

うぉー、超勉強になる！
たしかに差分単位で求めるのは難しそうだから、常にゼロ（音程0／再生速度100%）を基準に求めた方が良さそうって事かなぁ。
ありがとう、ちょっと実装してみる！

https://twitter.com/hone1221/status/1091909647416487938?s=21
ところで、
pow(2,x/12)=2^(x/12)
x*pow(2,1/12)=x*2^(1/12)
なので、たぶんりょーたさんの方で正しい気がします。
なお、即興で考えたので特に上ツイートは間違っている可能性がありますw

ありがとー、ウェブ上に実装例が無いかも合わせて当たってみるね！

**Comment by KanzakiSaki** [comment]
過去のやりとりも掲載しておきます(*･ω･)ﾉ

〜〜

https://twitter.com/kazucchi_DTMer/statuses/988697719869923329
おお、フォローありがとうございます！
いつも耳コピや速度及び音程の編集で使わせて頂き、とても感謝しております！(>_<)
突然の質問で申し訳ないのですが、PCでは再生周波数を変えることは出来るのですが、iOSでは再生周波数の項目が見当たりません。
iOSにはまだ搭載されていないのでしょうか(・・?

未搭載です！　iOS版では横軸をスピード、縦軸を音程というインターフェイスにして直感的な操作を優先させたんですよね。再生周波数の指定についてもデザイナーのうめちゃん  とともに考えてみますね！

https://twitter.com/ryota_yama/statuses/988700856869502976
「Windows版に付いている再生周波数の機能をハヤえもんiOS版にも付けてください」って要望が最近増えてる。なんか分かりやすいUIにできたらいいけど、横軸／縦軸の画面に入れるのは厳しいからエフェクト画面かなぁ？

https://twitter.com/ryota_yama/statuses/992313411915546626
ほんとはコントロール画面に入れられると収まりがいいんだろうけど、あれはあれで縦軸横軸の直感的な画面設計にできてるから、再生周波数はシステム側の設定的な扱いでエフェクト画面にしようかと……！

https://twitter.com/ryota_yama/statuses/1057140273430507520
#ハヤえもんAppStoreでのやりとり
耳コピに便利 ★★★★☆
投稿者: S.R.V – 2018年10月29日
左だけとか、右だけとかギターソロのコピーに便利です。
カセットテープの音源の速度調整ができると助かるので、音の高さと再生速度を同時に動かせると星5個ですね

デベロッパの回答 – 2018年10月30日
S.R.Vさん、はじめまして！
ハヤえもん開発者のりょーたと申します٩( ᐛ )و
嬉しいコメント、ありがとうございます！
エフェクト画面から「再生周波数」というのを調整いただくと、カセットテープのような速度調整（速度を上げれば音程も上がる）をする事ができます！
ぜひぜひお試しくださいね。
他にも何かありましたら、いつでもご連絡くださいませ。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

こういうのもったいないよね💦
私も「再生周波数」って聞いても最初ピンとこなかったんだよね…(´･ω･`;)

これ、一般的な言葉って何なんだろうねー！
Windows版からの流れで再生周波数でずっときちゃってるけど、これもともとは使ってる音声ライブラリでFrequencyって英語で表現されてて、直訳すると「周波数」なんだけど訳わからんから「再生」を付けてみたってだけなんだよね(*ノﾉ)

そういう経緯があったのか…！
例えばコントロール画面で、音程上げると速度も連動して上がるみたいな表現ってできたりしないかな？？
コントロール画面に項目を設置して、チェックを入れると連動するようになるとか。
無知だから難しいこと言ってるかもしれないごめん💦

既存の再生周波数を残す前提ならアリじゃないかな？？
ちょっとUIのイメージが付いてないけど。
再生周波数を200にしといて、そこから音程を下げたいみたいなニーズもあるから、独立した設定項目は必要だと思うんだけど、それとは別に連動させられるってのはすごく良いと思う！

エフェクトの名称もあるんだけど、コントロール画面とも分かれてるから、できないんだーって思われるのもあるだろうなと思って。
画面ちょっと考えてみようかなぁ。。

ぜひぜひ٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.03でリリース予定٩( ᐛ )و
