### ISSUE TITLE
速度のローラーを分ける

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#398]
ハヤえもん iOS ver.3.02

https://twitter.com/ryota_yama/status/1091010759016951808?s=21
iPhone SEのエミュレータで試した限りでは特に問題なく動きそうだけど、実機で試してみたいからうめちゃんに頼んでみよーっと！
あとは、5000%まで1%単位で変更できる必要があるか（1000以降は2000、3000、4000、5000だけでも良い？】とか、ホントに5000%（および♭/♯60）まで対応する？とか要検討！

呼ばれた！？！？
あー、操作性ね…！
確かに1000％の時点でかなりスクロールしないといけなかったなｗ
5000％とかものすごい大胆な数字だなぁｗ

いったん1000、2000、3000、4000、5000バージョンで試してみてくれるかなぁ？？
‎iPhone SE実機でカクついたりしないかが気になってて。
‎5000%は自分でも色々試してみたけど、前にいた何の曲か当てるクイズ界隈の人からは喜ばれそう٩( ᐛ )و

おお、試す試す〜〜！ヾ(*ﾟ▽ﾟ*)ﾉ
曲当てクイズ楽しそうねｗ

ありがとー、色々落ち着いたら配信するね٩( ᐛ )و

あ、これ、♯、♭ボタンの事を考えるといきなり1000から2000に変わったら変かなぁ？
いったん1刻みにしてみよーかなぁ！

あー、ローラーなんだけど、位ごとに分けれたりしないかな？？
今、小数点の上と下としかローラーが分かれていないけど、
1の位、10の位、100の位、100の位で別々に設定できると嬉しいなって…！

![Image](https://i.imgur.com/Nsna293.jpg)

100の位ふたつあるけど1000の位の間違い😂

あー、それだ！
‎面白い、ありがとー٩( ᐛ )و

おお！実装できそう！？
めっちゃ嬉しい…！

ただねー、これ小数点が入らないんだよねー！　ここにコロンが無いのと同じような感じで。

![Image](https://i.imgur.com/LYDnyAF.jpg)

おお、そうなんだね！
TimeTreeも見てみたけど、反映されてどこの値かわかる感じだった！
大丈夫じゃないかな？？

![Image](https://i.imgur.com/CGodE5P.jpg)

うんうん、そうだよね！
‎それならいける٩( ᐛ )و

〜〜

関連issue #393

**Comment by ryotayama** [comment]
対応した！　バージョン3.03でリリース予定٩( ᐛ )و
