### ISSUE TITLE
音程のローラーを分ける

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#399]
ハヤえもん iOS ver.3.02

https://twitter.com/umeboshikantaro/status/1091894423485538304?s=21
これって音程の方は分けなくてもいいかな？？

ぜったい分けた方がいいと思う٩( ᐛ )و
‎だって♯と♭で音程を反転できたりするんだよね、めっちゃ楽しそう！
‎ただ、意外と難易度高そうだから別Issueで！笑

おお！！♯と♭もローラーを分けるということか…！？
そしたらissue登録しておくね！！

そうそう！
‎それが分かれてるとめっちゃ楽しいなーと思って٩( ᐛ )و
‎ありがとー、嬉しい！

〜〜

関連issue #398

**Comment by ryotayama** [comment]
対応した！　バージョン3.04でリリース予定٩( ᐛ )و
