### ISSUE TITLE
波の音などの効果音系エフェクトが曲の再生停止後に使えない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#4]
- iOS版ver.2.64

アプリ起動時は曲を再生していなくても波の音などの効果音系エフェクトが使えるのに、一度曲を再生／停止してからは、音が出なくなってしまうのを修正します٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
これ、別のアプリに移ってバックグラウンドになっても消えちゃうんだね…！(*ﾉﾉ)
例えばツイッター見ながら雨の音を流したりとかはできないんだ…！

**Comment by ryotayama** [comment]
うめちゃん、ありがとう！！
それも一緒に直すね！！

**Comment by ryotayama** [comment]
対応しました！　ver.2.65でリリース予定です٩( ᐛ )و
