### ISSUE TITLE
歌詞へのアクセス性を高めたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#408]
バージョン3.02

https://twitter.com/ryota_yama/status/1092250486109949952
#ハヤえもんAppStoreでのやりとり
最高です。 ★★★★★
投稿者: ☆★ACE★☆ – 2019年2月1日
自分が探していた機能が全部詰まっていて最高です！！
曲のイメージ画像をタップで歌詞表示
長押しで画像変更みたいにしてくれたら完璧です
歌詞出すときにパッと出せないのだけちょこっと残念です
他は完璧です愛用してます

デベロッパの回答 – 2019年2月4日
☆★ACE★☆さん、はじめまして！
ハヤえもん開発者のりょーたです٩( ᐛ )و
「最高です！！」と言ってくださって、とっても嬉しいです！！
たしかに歌詞にアクセスする為に何タップかしないといけないので、もう少し歌詞へのアクセス性を高めたいですね。
ありがとうございます、考えてみますね！
他にも気になる点などありましたら、いつでもご連絡くださいね。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

**Comment by ryotayama** [comment]
https://twitter.com/small_hinotori/status/1138217465614180352?s=21
歌詞の表示をタップ一回だけでできるようにしてほしいです😅

**Comment by KanzakiSaki** [comment]
https://twitter.com/umeboshikantaro/status/1226314518181097472?s=21
ハヤえもん、スワイプで削除できるならスワイプで歌詞表示できるのもいいかもしれないと考えてみた。
左側にも確かつけれたはず？気付かれにくいかなぁ…

![スワイプで歌詞表示](https://user-images.githubusercontent.com/32741225/74094643-fd145f80-4b27-11ea-837f-c270d7db0ff6.png)

**Comment by ryotayama** [comment]
https://twitter.com/meme_3319/status/1226334572184363008?s=20
そんなすばらしい機能実装されたら余計カラオケ練習捗るじゃないですか☺️

**Comment by ryotayama** [comment]
https://twitter.com/kokowa0748/status/1226329287772364800?s=20
これいいやんっ！

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1226321592063389696?s=20
ありがとー、↓右方向へのスワイプは再生リスト整理画面に遷移させたいって話もあったからそれと競合するかも…？？

あーそっかぁ、その話忘れてた😅
やっぱアイコンで表現した方がいいかなぁ、この画面にも歌詞ボタンあった方がいいような気がしてきた、、
振り出しに戻る😖

まだちゃんとは調べてないけど、テーブルを右から左にスワイプした時にメニューを２個出したりもできるっぽいよ？（画像も使える？）
https://qiita.com/eKushida/items/bf02d0b44eca14cfbfdc

うんうん、再生中画面にも歌詞表示ボタン欲しいね！👍

こんな感じで見たことある！
右側でもいいのかな？？
でもこれだとアイコンより文字で「歌詞」「削除」って書いてある方が視認性が高い気がするかな…うーむ。。

おぉ、やっぱあるんだ！　すごい！👏
文字の問題点は多言語化した際に幅が変更する事だけ…（特にロシア語が幅を取りがち💦）

軽く翻訳してみたけど、「歌詞」「削除」ぐらいなら右側に２個並べてもいけそう！💡

うぉお！マジかぁ翻訳早速ありがとう！

アイコンにするとこんな感じなんだけどどうだろ？？
なんかスワイプの右側は削除が染み付いてて…って感じするなぁどうしても…慣れるのだろうか💦

分かるー、慣れって超大事だよね！💡
アイコンにしたら↓こっちとの整合性も気になってきそうだし、ひとまず文字でいいような気もするけどどうかなぁ？？

うんうん！アイコンに変えるとイコライザやエフェクトテンプレートも変えなきゃだもんね…！いいと思うよー🙆‍♀️

おっけー、じゃあ↓こんな仕様で対応してみるね👍
・右から左へのスワイプ時に「歌詞」「削除」メニューを並べる
・フルスワイプ時は削除の挙動にする（可能？　要確認）

じゃあこんな感じかな？？

ちなみに緑はiOS System Greenってやつを使ってる（♯4cd964

うぉー、とてもいい！　ありがとう🙏
ん……あっ、コントラスト比がぁー！😱
（赤の方は太字にすればセーフっぽい）

あらあら、iOSのカラー使ってるのにだめなんだ？？
私のみてるやつだとAAかAAAなんだけどな…
iCloudバックアップボタンのグリーンならどうだろ？？

いつものツールで巨大文字でもNGだったよ💡
iCloudバックアップの方は文字に影がついてるから視認性が確保されてそう…！

あー下の方見てた！
結果が違うのなんなんだろうね…！？

うんうん！文字にドロップシャドウつける方向でやってみたいな！

単に見方を間違えてたのか…😩ごめーん

おぉ、なるほど！💡
おっけー、「純正機能のそこにドロップシャドウを付けれるのか…？」って不安があるから、また対応する時に無理そうだったら相談させてー！🙏

付けれるかどうかね！了解👌

なんか黒文字なら達成らしいんだけど…合わなさすぎて無理…だった…😭

ありがとー！👍
こ、これは厳しいね😱

試しにiOS System purple （♯5856d6）ってやつにしてみたー！
これならドロップシャドウなしでいけるしどうだろ？？
![EQToHiaUEAAD6YP](https://user-images.githubusercontent.com/6075785/74096502-47570a00-4b43-11ea-9007-cb9b7c2b32f5.jpeg)

おぉ、めっちゃいいじゃん！
ありがとー！٩( ᐛ )و

おお、良かったありがとう！！
再生中画面はまた別で考えてみるね…！(o`･ω･)ゞ

わーい、ありがとー！👍👍

**Comment by KanzakiSaki** [comment]
https://twitter.com/furiespure/status/1226331302946717697?s=21
それは便利すぎるw
もし実装されたらめっちゃ使いますよw

**Comment by ryotayama** [comment]
対応した！　バージョン3.61でリリース予定！
