### ISSUE TITLE
コントロール画面のグラフ範囲をユーザー側で設定できるようにしたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#423]
ハヤえもん iOS ver.3.04

https://twitter.com/ryota_yama/status/1093005059829358593?s=21
あとはグラフの範囲が自分的には400%もいらなくて速度は50〜200%、音程は♭6〜♯6ぐらいで十分だから、グラフの範囲がカスタマイズできたら嬉しいなー！
‎すげー雑に描いたけど、こんな感じで歯車を押すと表示範囲がカスタマイズできるとか……？

![Image](https://i.imgur.com/gTuR6LZ.jpg)

それ私も範囲狭くしたいなーって思っていて、ちょっと考えていたんだけど、オプション設定画面につけるのはどうかな？？

![Image](https://i.imgur.com/KZ2e9Dp.jpg)

そっか、オプション機能分散させない方が分かりやすいから、オプション設定画面の方が良さそうだね٩( ᐛ )و

あれなんか表示おかしいな💦
こっちです！

![Image](https://i.imgur.com/qZ7Dzg2.jpg)

うんうん、♯と♭は逆の方が分かりやすいかなー！（小さい値〜大きい値）
これタップするとこういう画面に遷移する感じ？？

![Image](https://i.imgur.com/oooW5QU.jpg)

そうなんだ？？
グラフの上下、左右って感覚で配置してみたけど、音程も下からの方がわかりやすいかなー？

そうそう、ローラーで選べたらいいなって！
速度に関してはそこまで厳密じゃなくて、10単位でいいと思うよ👍

速度は「最小値〜最大値」、音程は「最大値〜最小値」ってのが個人的にしっくりこないから、「最小値〜最大値」で統一したいな٩( ᐛ )و
‎ローラーね、おっけー👍

これ普通に考えたらどっちなんだろう？？
自分はコーディングする都合上もあって、速度は最小値〜最大値、音程は最大値〜最小値ってのがどうしても気持ちわるく思えちゃうんだけど、ユーザーさんからするとそんな事は関係ないから、使う事だけを考えたら#12〜♭12の方がいいのかなぁ？？

ん〜そうだなぁ。。
私が視覚的な感覚が強いからそう感じるだけかも？？
言い出すと、速度と音程の位置が逆の方がわかりやすいなーって思ってたりする。視線の流れ的にどうしても♯が先に来るんだよね。でもこの辺まで変えちゃうと混乱しそう。。

![Image](https://i.imgur.com/WBbbUsE.jpg)

うぉー、なるほどね！
‎勉強になるなぁ！
‎よし、オプション設定は♯12〜♭12にするよ！
‎自分のコーディングする時の気持ちわるさが強く出ちゃってごめん！
‎そして、速度と音程もいずれ入れ替えよう٩( ᐛ )و

そうなの！？！？Σ（・□・；）

漫画のコマ割りやDTPの知識なんだけど、縦書きは右上から左下へ、横書きは左上から右下へ向かう視線の動線があって、それに沿ってレイアウトを組むと読む人がストレスなく自然に読めるっていう。

なのでさっきの番号を書き直すとこうかな？？

![Image](https://i.imgur.com/U3vriwe.jpg)

あー、面白い面白い٩( ᐛ )و

いやでも確かに、数値だけ見るとなんで大きい方から並んでるの？っていう違和感は私にもわかるから、最終的にはりょーたさんの好みでいいと思うよ！ｗ

うぉーなんてうれしい事を！
‎じゃあ触ってみた時の気持ち良さで決めさせてもらうね٩( ᐛ )و

了解です(o`･ω･)ゞ
とりあえず設定画面作ってみますね！

わーい٩( ᐛ )و

今使ったことのあるパーツでいったん組んでみたけどどうかなー？？

![Image](https://i.imgur.com/LChhhqy.jpg)

![Image](https://i.imgur.com/qEiwFTd.jpg)

おぉ、これならめっちゃ実装しやすい！
‎ありがとー٩( ᐛ )و

ちょっと野暮ったいけど実装しやすさを優先した(ﾉω`*)ﾉ

短時間でできるとは思うけど、全然デザイン性を優先してくれていいよー٩( ᐛ )و
‎今後、オプション設定で値を入れる時にこれを踏襲する事になりかねないからさー！

まぁ確かにそうね…！
あとはアラームに見られるような、こういうタイプのコントロールかな？
これって値の間に「〜」とか入れられるのかしら…？

![Image](https://i.imgur.com/Q0WeO3P.jpg)

うんうん、さっきのやつで自分は野暮ったいとは思ってないんだけど、うめちゃんが野暮ったいと思うんならその野暮ったさが拭えたら嬉しいな٩( ᐛ )و

‎アラームのやつは、下から出てくるかの違いだけで、これと同じコントロールだから、「.」みたいに無理やりねじ込む事はできるけど、「〜」分の余白をあけるとかは難易度高そうだった！

![Image](https://i.imgur.com/sFQNEnL.jpg)

‎あとはこれみたいにコントロール自体を分けてしまえば、間に「〜」のラベルを入れる事はできるはずだよ٩( ᐛ )و

![Image](https://i.imgur.com/YnrKQNY.jpg)

おお〜なるほど！そうなのね！詳しい説明ありがとう！！🙏

そしたら、上の階層でプレビュー？出るようにしたいから、調節画面ではローラー回すだけの方がいいかも…！

「上の階層でプレビュー？出るようにしたいから、調節画面ではローラー回すだけ」

ギブミー理解力(*ノﾉ)w

ごめんごめん、「オプション設定」画面で値が見れるようにしてあるから、最初のやつだとタップ数が増えすぎちゃうと思ったの💦（1枚目）

私も部品が微妙に理解できてないんだけど、こういう感じであってるかな？？（2枚目）
この画面は一覧になってないから、高さが広い方が回しやすいだろうなーって

![Image](https://i.imgur.com/sTnl4Sg.jpg)

![Image](https://i.imgur.com/2XVtzkQ.jpg)

おぉ、なるほど！
‎分かりやすい説明ありがとう٩( ᐛ )و
‎これめっちゃいいね！
‎速度の方も数値を１きざみにせずある程度絞れば、カラカラするのが大変って問題も回避できそうだし、すごく良いと思う！

おお！！ありがとう！！
これ実装できたらかなり嬉しいなー！
私はiPhoneSEで狭いからちょっと動かすと変化量が大きくて💦
iPadとかなら広くてもいいと思うから、ユーザーの環境に合わせられるの大事よね…！✨✨

だよねー！　はやく付けたいなー٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.07でリリース予定٩( ᐛ )و
