### ISSUE TITLE
コントロール画面のポインター移動を整数にスナップさせたい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#424]
ハヤえもん iOS ver.3.04

https://twitter.com/ryota_yama/status/1093018392586379264?s=21
あとはキリのいいところで吸着するようなオプション？ができたら、自分的にはコントロール画面はだいぶ満足だなー！

あー近似値まできたらスナップしてくれるやつね！あるとすごい嬉しいなそれ！✨✨
今って小数点の端数が出ちゃうからなぁ…！

そうなのー、めっちゃ欲しい٩( ᐛ )و
‎ただ結構激しくスナップしちゃいそうで、連続的に変更したい人もいるだろうから、これもオプションなのかなぁ？？

フォトショップやイラレの中にも、スナップのオンオフ切り替えあるよ！
それと同列に扱うのも変な気がするけどｗ

それで行こう！
‎子供たちは言わば楽器みたいな感じでコントロール画面のグラフをひたすら触ってるからたぶんスナップしてほしくなくて、自分はキリのよくない値が気持ちわるいからスナップしてほしいんだよね！
‎めっちゃ楽しみ٩( ᐛ )و

耳で聞いた時の自然さはシームレスな方がいいよねー！
楽しみ楽しみヾ(*ﾟ▽ﾟ*)ﾉ

そうなんだよねー！
‎また余裕のある時にでも画面考えてくれたら嬉しいな٩( ᐛ )و

こっちはこんな感じでどうかな？？
![Image](https://i.imgur.com/l89Kq5o.jpg)

おっけー、ありがとう٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.07でリリース予定٩( ᐛ )و
