### ISSUE TITLE
保存系の処理が完了した際に動画広告を出すようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#432]
バージョン3.04

開発陣のDMでのやりとりより
保存系の処理が完了した際に、動画広告を出すようにします。

処理の流れとしては、こんな感じ。
①セーブ中のゲージが全て溜まる
②動画広告が表示される
③動画広告を閉じると、「保存しました」というダイアログが表示される（ダイアログには、OKボタンが必要）

**Comment by ryotayama** [comment]
#311 の後に対応しようかと考えています！

**Comment by KanzakiSaki** [comment]
自分が使っている動画編集アプリを観察してみました！

![Image](https://i.imgur.com/YpuPm0o.jpg)

①書き出し中、プログレスバーとともに「アプリを閉じないでください」のメッセージ。

![Image](https://i.imgur.com/YjA5JhE.jpg)

②100％になるとそのまま③に切り替わる。

![Image](https://i.imgur.com/sDwWDty.jpg)

③動画広告。右上に残り秒数。

![Image](https://i.imgur.com/5RhpVF9.jpg)

④広告が終わると、×印の閉じるボタンが出るので押す。

![Image](https://i.imgur.com/nZ7GXGr.jpg)

⑤保存完了画面。「完了」ボタンを押すと編集画面に戻る。

こんな流れです！

**Comment by ryotayama** [comment]
- [x] 動画広告視聴中に保存が終わっていたら「保存しました」ダイアログが出るようにする
- [x] Dropboxへの保存時にも動画広告が出るように対応
- [x] ２回目の広告を読み込むように対応
- [x] エフェクトを変更した状態でアプリ内に保存をキャンセルすると保存中ダイアログが２回表示されるのを修正
- [x] 起動時に機内モードだった場合、その後オンラインになっても動画広告が表示されないのを修正
- [x] アプリ内に保存、カメラロールに保存、Dropboxに保存、他のアプリにエクスポートの挙動をそれぞれ確認（左メニュー、ライブラリ画面それぞれ）
- [x] 広告が読み込めない場合の挙動も確認
- [x] 複数選択からの保存時の挙動も確認
- [x] Dropboxから読み込んだ曲の保存時に保存中ダイアログが出ないのを修正
- [x] 広告を閉じてから進捗に変化があるまでの間、保存中ダイアログが出ないのを修正
- [x] 広告非表示の場合は動画広告が出ないようにする
- [x] 広告IDを本番に修正

**Comment by ryotayama** [comment]
↓のケースについて、それぞれ動作確認予定✍️

# 再生リスト画面
## ミュージックライブラリから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## カメラロールから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## Dropboxから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## 他のアプリからインポート
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## 録音
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## 複数選択
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
# アーティストごとのアルバム画面
## ミュージックライブラリから追加
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
# アーティストごとの曲一覧画面
## ミュージックライブラリから追加
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
# アルバム画面
## ミュージックライブラリから追加
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
# 全曲画面
## ミュージックライブラリから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## カメラロールから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## Dropboxから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## 他のアプリからインポート
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## 録音
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
# 左メニュー
## ミュージックライブラリから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## カメラロールから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## Dropboxから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
## 他のアプリからインポート
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## 録音
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
# 再生中画面
## ミュージックライブラリから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## カメラロールから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## Dropboxから追加
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
## 他のアプリからインポート
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）
## 録音
- [x] アプリ内に保存（保存中に広告閉じる）
- [x] アプリ内に保存（保存後に広告閉じる）
- [x] アプリ内に保存（オフライン）
- [x] カメラロールに保存（保存中に広告閉じる）
- [x] カメラロールに保存（保存後に広告閉じる）
- [x] カメラロールに保存（オフライン）
- [x] Dropboxに保存（保存中に広告閉じる）
- [x] Dropboxに保存（保存後に広告閉じる）
- [x] Dropboxに保存（オフライン）
- [x] 他のアプリにエクスポート（保存中に広告閉じる）
- [x] 他のアプリにエクスポート（保存後に広告閉じる）
- [x] 他のアプリにエクスポート（オフライン）

**Comment by ryotayama** [comment]
カメラロールに保存する際、保存中ダイアログが出ないケースを直した！
あとはDropboxから読み込んだ曲で保存中ダイアログが出ないのを直したらテストに戻る予定✍️

**Comment by ryotayama** [comment]
Dropboxから読み込んだ曲で保存中ダイアログが出ないのを直した！
よーし、テストに戻ろーっと！

**Comment by ryotayama** [comment]
複数選択からのカメラロールへの保存時に、インタースティシャル広告を閉じるタイミングによっては進捗ゲージがいきなり100%になってしまうのを発見✍️

**Comment by ryotayama** [comment]
直した！　よーし、続き！

**Comment by ryotayama** [comment]
複数選択からのDropboxへの保存時に、インタースティシャル広告が２回表示されてしまうケースを発見✍️

**Comment by ryotayama** [comment]
複数選択からのDropboxへの保存時に、インタースティシャル広告が２回表示されてしまうケースを直した！

**Comment by ryotayama** [comment]
複数選択からの保存時、インターネットへの接続エラーが出た後でもう一度保存しようとするとセーブ中のダイアログが出ないのを発見✍️

**Comment by ryotayama** [comment]
複数選択からの保存時、インターネットへの接続エラーが出た後でもう一度保存しようとするとセーブ中のダイアログが出ないのを直した！

**Comment by ryotayama** [comment]
広告非表示機能をオフにした場合に動画広告も出るようになっているのを確認する事✍️

**Comment by ryotayama** [comment]
アーティストごとのアルバム画面で保存中に広告を閉じると挙動がおかしくなる？　要調査📝

**Comment by ryotayama** [comment]
あー、これ違うわ。ブレイクポイントを入れたままのバージョンを動かしてるからだわ。という事でテスト継続。

**Comment by ryotayama** [comment]
didFinishSavingWithErrorよりも前にadDidDismissFullScreenContentが呼ばれると保存中ダイアログも保存しましたダイアログも出ない✍️（カメラロールに保存を選んで、すぐに広告を閉じると再現）

**Comment by ryotayama** [comment]
↑直した！

**Comment by ryotayama** [comment]
Dropboxへの保存時に保存中ダイアログが出ないケースがあったのを直した！
