### ISSUE TITLE
逆回転再生時にトリミングがうまくいかないケースがある

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#444]
バージョン3.06

https://twitter.com/UmeboshiKantaro/status/1095885426269741056
通常再生の書き出しは大丈夫だったけど、逆回転再生のAだけ設置とBだけ設置した場合の書き出しが変なので、確認いただきたく…！🙏

Aだけだと範囲が意味不明なところで切られてて、Bだけだと1秒未満になってしまいます！🙇‍♀️
![Uploading DzVd_A-U8AQBRKH.jpg…]()

**Comment by arigayas** [comment]
良太さんのissue登録コメントで うめさんの画像が上手く貼れていなかったので貼ります。
![dzvd_a-u8aqbrkh](https://user-images.githubusercontent.com/11251874/52929597-68e64100-3388-11e9-82ca-64b4d18f2783.jpg)

**Comment by arigayas** [comment]
文字起こししてみる。

## 通常再生
AB保持なし アプリ内→○
AB保持なし カメラロール→○
AB保持なし Dropbox→○
AB保持なし エクスポート→○

A保持なし アプリ内→○
A保持なし カメラロール→○
A保持なし Dropbox→○
A保持なし エクスポート→○

B保持なし アプリ内→○
B保持なし カメラロール→○
B保持なし Dropbox→○
B保持なし エクスポート→○

AB保持 アプリ内→○
AB保持 カメラロール→○
AB保持 Dropbox→○
AB保持 エクスポート→○

A保持 アプリ内→○
A保持 カメラロール→○
A保持 Dropbox→○
A保持 エクスポート→○

B保持 アプリ内→○
B保持 カメラロール→○
B保持 Dropbox→○
B保持 エクスポート→○

## 逆回転再生
AB保持なし アプリ内→○
AB保持なし カメラロール→○
AB保持なし Dropbox→○
AB保持なし エクスポート→○

A保持なし アプリ内→×
A保持なし カメラロール→×
A保持なし Dropbox→×
A保持なし エクスポート→×

B保持なし アプリ内→×
B保持なし カメラロール→×
B保持なし Dropbox→×
B保持なし エクスポート→×

AB保持 アプリ内→○
AB保持 カメラロール→○
AB保持 Dropbox→○
AB保持 エクスポート→○

A保持 アプリ内→×
A保持 カメラロール→×
A保持 Dropbox→×
A保持 エクスポート→×
(設置してないはずのB地点が書き出される？)

B保持 アプリ内→×
B保持 カメラロール→×
B保持 Dropbox→×
B保持 エクスポート→×
(範囲指定が機能せず1秒以下の音声ファイルとして書き出される？)

**Comment by ryotayama** [comment]
対応した！　バージョン3.07でリリース予定٩( ᐛ )و
