### ISSUE TITLE
Siriショートカットに対応してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#446]
バージョン3.06

https://twitter.com/ryota_yama/status/1096205183829172224
#ハヤえもんAppStoreでのやりとり
Siriショートカット機能ほしい！ ★★★★★
投稿者: Freneza321 – 2019年2月9日
このままでも優秀ですけど、Siriショートカット機能の追加と、
曲が4桁ある人のために、端末内の曲を一括で追加する機能があればとっても良くなると思います！

デベロッパの回答 – 2019年2月15日
Freneza321さん、はじめまして！
ハヤえもん開発者のりょーたと申します！٩( ᐛ )و
おぉ、嬉しいコメントありがとうございます！
Siriショートカット機能は具体的にどんなショートカットがあると嬉しいですか？
端末内の一括追加機能については、いずれ対応しますね！
他にも気になる点などありましたら、いつでもご連絡くださいませ。
ツイッター（@ryota_yama）からご連絡いただく事もできます！

https://twitter.com/ryota_yama/status/1096205424280231936
Siriショートカットは自分が使ってないのもあって、普段から使いこなしてるような人から意見もらえたらめっちゃ嬉しい٩( ᐛ )و 

https://twitter.com/UmeboshiKantaro/status/1096263560487788544
調べてみた！！これは実際に使ってみないと分からないやつだ…！！　■【iOS12】Siriショートカットってなにができるの？使い方解説 入門編 - iPhone Mania 
https://iphone-mania.jp/news-228494/

**Comment by arigayas** [comment]
これが使えたら、hogehogeという再生リストを1曲目から再生するとかランダム再生することを
声で出来るようになるって事ですよね？

**Comment by ryotayama** [comment]
ありさん、そうだねー！
初期段階からどこまでできるようにするかは要検討だと思う！

**Comment by ryotayama** [comment]
https://twitter.com/FrenezaP/status/1156708051635675137?s=20
ハヤえもん、いまはiphoneユーザーではないのですが、音楽を再生してーとかキーを上げ下げとか○○のエフェクトかけてーとかが音声で操作できればいいと思いました。レビューでの返信でなくて申し訳ないですが
Googleアシスタントにもあっていいと思いますよ〜 まる

**Comment by ryotayama** [comment]
バージョン3.34でひとまず対応した！　ここから先は個別リクエストがあり次第Issueを立てて対応します！٩( ᐛ )و
