### ISSUE TITLE
未対応のはずの拡張子midファイルがDropboxから追加できてしまう

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#455]
ハヤえもん iOS ver.3.06

https://twitter.com/umeboshikantaro/status/1098520277737062401?s=21
あと拡張子midのファイルがDropboxから読み込めてしまった…けど再生されなかった💦

**Comment by ryotayama** [comment]
対応した！　バージョン3.08でリリース予定٩( ᐛ )و
