### ISSUE TITLE
バックアップ機能が欲しい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#46]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/36

2017.11.05
アンインストールした場合でも再生リストなどを復活できるバックアップが欲しい。

https://twitter.com/ryota_yama/status/927005248270385154

Windows版以外だね。Windows版は内部にファイルを貯めたりしないから。

2018.06.04
macOS 版にもバックアップ機能が居ると思うのでラベルを追加しました。

2018.07.11
Dropboxにバックアップできるといいという意見が出ましたのでコメント残しておきますね(*･ω･)ﾉ

https://twitter.com/marron_nn_/status/1016971330095230976?s=21
ハヤえもんの再生リストファイルのバックアップ(Dropbox)できる機能、それを書き出す機能欲しいと思った(iPadお絵描きの作業用BGMにしたかった)

2018.07.11
うめちゃん、ありがとー！
これちょっと仕様を考えないといけなくって、再生リストだけを保存したとしても音声ファイルが無いとハヤえもんに読み込めないんだよね。
例えば、端末Ａの再生リストをDropboxに保存して、端末Ｂで読み込んだとしても端末Ａの曲が端末Ｂに入ってなかったら再生できなかったりする。
ここら辺の仕様整理をどうするかってのを検討しないといけないんだけど、自分の中ではまだ答えが出てない感じ！

2018.07.11
ありがとうございますpray

ななすけさんのコメントに続きがありますので載せておきますね。

https://twitter.com/marron_nn_/status/1016973601168244736?s=21
ありがとうございます！
１曲ずつの書き出しは大変なのでリストごと行きたいというそれだけです…(´`)

https://twitter.com/umeboshikantaro/status/1016986289864732672?s=21
わかります…！！
ただ、曲のボリュームによって時間がかかってしまうかもしれないです…！その辺も含めて検討してみますね！！pray

https://twitter.com/marron_nn_/status/1016990798347317248?s=21
時間かかってもいいのでとりあえずはあるとうれしいですね！
もう改善リスト沢山あってめちゃくちゃ大変なのは分かってるので、ほんと休み休み頑張ってください…！！！

以上です。
既存の一曲ごとの保存やエクスポート機能の、再生リストバージョン、というイメージのようです。

もし実装できるなら、私も返信しましたが曲のボリュームによってはかなり時間がかかる可能性がありますよね。
現在の曲の保存やエクスポートは、一度実行して保存中やエクスポート中のバーが表示されると「キャンセル」を選択することができませんが、「キャンセル」できるようにするのも大事になってくるかと思います。

ご検討ください(*･ω･)ﾉ

2018.07.11
ふむふむ！
だとすると拡大解釈すると、「複数曲をまとめて保存する機能が欲しい」にも近いのかなぁ？？

2018.07.12
たしかに、複数曲の選択ができるようになったらまとめて保存／エクスポートできるのもいいかもしれないですね。
ななすけさんの話的には、再生リストの一覧画面の「…」ボタンのアクションに保存／エクスポートを追加できないかなーという感じですね(*･ω･)ﾉ

**Comment by ryotayama** [comment]
https://twitter.com/ISIN2404/status/1041335940768124935
こんばんは。
利用させていただいてます。
とっても便利で重宝させていただいているのですが、保存/エクスポートをする際に、iPhoneでも一括でできるようにしていただけると大変ありがたいです。改善を期待しています。

ISINさん、はじめまして！
ご連絡ありがとうございます٩( ᐛ )و
ＯＫです、いずれ対応しますね。
今、「Android版をiOS版に追いつかせる」ってのを最優先に開発を進めているので、ごゆっくりお待ちいただけるとうれしいです！

**Comment by ryotayama** [comment]
https://twitter.com/kento825uotami/status/1095231987839754240
曲のバックアップ機能欲しいです…

**Comment by ny-yamana** [comment]
引き継ぎをできるようにしてもらえたらいいなと思ってます！
https://mobile.twitter.com/ryota_yama/status/1137121961195126784

**Comment by ryotayama** [comment]
https://twitter.com/kamie_dake/status/1213493463364165637?s=20
ハヤえもんアカウント機能ないんかなー

こんばんは、ハヤえもん作者です！🙏
アカウント機能……というとどんな機能でしょう？

あっ手違いでもしアプリ消した時にデータ全部消えてかえってこないの嫌だなーっておもってて！スマホ変える時もどうしよっかなって思ってました！

おぉ、詳細ありがとうございます！🙏
データのバックアップ機能という事ですね！

はい！そうです！

ありがとうございます、考えてみますね🙏
現状だとMacをお持ちならiTunesのファイル共有機能からバックアップ、お持ちでないならハヤえもんからエクスポートしてDropboxやiCloudにバックアップというのが手軽かもしれません（ただし、各画面の設定を保持した内容やアートワークなどは復元されません）

Macは持ってませんね、私のiPhone壊れてるのかよくわからないんですがiCloudに繋げなくてバックアップがとれないんです、
結構な量があるので、
ぜひ機能追加よろしくお願い致します、、！

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1101879631987109888?s=20
ハヤえもんバックアップ機能、クラウドマークで大丈夫かなー、、
![D0qpDz7VsAEEyPp](https://user-images.githubusercontent.com/6075785/73014032-ca4a4600-3e5c-11ea-8db7-58a683f4a739.jpeg)

作りかけぇー。
ボタンの角丸はウニの購入ボタンと同じ比率にした！
これを押されたら復元ボタンも出るようにしなくてはね。。
あとファイルサイズかな…？
![D0z2JLdU8AEJQ5d](https://user-images.githubusercontent.com/6075785/73014060-d930f880-3e5c-11ea-99b0-9716be60d1a1.jpeg)

作成と復元の色マジで悩みどころなんだよなー；；

あと最終更新とファイルサイズの位置な…微妙…
![D04lnCaVAAE8-7v](https://user-images.githubusercontent.com/6075785/73014078-e6e67e00-3e5c-11ea-8355-9d1b30e73ba8.jpeg)

https://twitter.com/UmeboshiKantaro/status/1118105946838880256?s=20
てかその前にバックアップ機能‼️

この緑色やっぱダメだー😂なおそ😂

色変えた！
![D4RTuCDUIAAEb1Z](https://user-images.githubusercontent.com/6075785/73013279-578c9b00-3e5b-11ea-8043-6e2134dcce01.jpeg)

→鍵垢の方から「バックアップを作成」「バックアップを復元」だと視認性が低いので、「バックアップ」「復元」にしては？との意見あり。

https://twitter.com/ryota_yama/status/1118315889760190465?s=20
うんうん、「バックアップ」「復元」は分かりやすいかもね！

そうよねーこういうアドバイスほんと助かる。。！

**Comment by ryotayama** [comment]
- iOSでデータを永続化する方法
https://gist.github.com/y-takagi/9f2cea659fb3f55b56aa04530bf0af39

各種変数を保存するにはKey-value storage（最大容量：1アプリ1MBまで）、実際の音声ファイルを保存するにはiCloud Documents（最大容量：ユーザーのiCloudアカウントに依存）を使うと良さげ。

**Comment by ryotayama** [comment]
こんな感じでいけそうな気配。

◆バックアップ
```
NSString* libraryDir = [NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES) objectAtIndex:0];
NSString* filepath = [libraryDir stringByAppendingPathComponent:[NSString stringWithFormat:@"/Preferences/%@.plist",[[NSBundle mainBundle] bundleIdentifier]]];
if([[[NSFileManager defaultManager] attributesOfItemAtPath:filepath error:nil][NSFileSize] longLongValue] > 1024 * 1024) {
	UIDialogViewController *dialog = [[[UIDialogViewController alloc] initWithTabBarController:self.vc] autorelease];
	dialog.modalPresentationStyle = UIModalPresentationCustom;
	[dialog setTitleWithText:@"アプリ内の使用容量が大きい為、バックアップできません" message:@""];
	[dialog addMenuWithText:@"OK"];
	[self.vc presentViewController:dialog animated:YES completion:nil];
	return;
}

for(NSString *key in [[[NSUserDefaults standardUserDefaults] dictionaryRepresentation] allKeys])
	[[NSUbiquitousKeyValueStore defaultStore] setObject:[[NSUserDefaults standardUserDefaults] objectForKey:key] forKey:key];
[[NSUbiquitousKeyValueStore defaultStore] synchronize];

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
	NSString *strDirectory = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
	NSURL *documentURL = [[[NSFileManager defaultManager] URLForUbiquityContainerIdentifier:nil] URLByAppendingPathComponent:@"Documents" isDirectory:YES];
	if([[NSFileManager defaultManager] fileExistsAtPath:documentURL.path]) {
		for(NSString *strFileName in [[NSFileManager defaultManager] contentsOfDirectoryAtPath:documentURL.path error:nil])
			[[NSFileManager defaultManager] removeItemAtURL:[documentURL URLByAppendingPathComponent:strFileName] error:nil];
	}
	else [[NSFileManager defaultManager] createDirectoryAtURL:documentURL withIntermediateDirectories:YES attributes:nil error:nil];
	for(NSString *strFileName in [[NSFileManager defaultManager] contentsOfDirectoryAtPath:strDirectory error:nil])
		[[NSFileManager defaultManager] copyItemAtURL:[NSURL fileURLWithPath:[strDirectory stringByAppendingPathComponent:strFileName]] toURL:[documentURL URLByAppendingPathComponent:strFileName] error:nil];
});
```

◆復元
```
[[NSUbiquitousKeyValueStore defaultStore] synchronize];
for(NSString *key in [[[NSUbiquitousKeyValueStore defaultStore] dictionaryRepresentation] allKeys])
	[[NSUserDefaults standardUserDefaults] setObject:[[NSUbiquitousKeyValueStore defaultStore] objectForKey:key] forKey:key];

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
	NSString *strDirectory = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
	NSURL *documentURL = [[[NSFileManager defaultManager] URLForUbiquityContainerIdentifier:nil] URLByAppendingPathComponent:@"Documents" isDirectory:YES];
	for(NSString *strFileName in [[NSFileManager defaultManager] contentsOfDirectoryAtPath:strDirectory error:nil])
		[[NSFileManager defaultManager] removeItemAtPath:[strDirectory stringByAppendingPathComponent:strFileName] error:nil];
	if([[NSFileManager defaultManager] fileExistsAtPath:documentURL.path]) {
		for(NSString *strFileName in [[NSFileManager defaultManager] contentsOfDirectoryAtPath:documentURL.path error:nil])
			[[NSFileManager defaultManager] copyItemAtURL:[documentURL URLByAppendingPathComponent:strFileName] toURL:[NSURL fileURLWithPath:[strDirectory stringByAppendingPathComponent:strFileName]] error:nil];
	}
});
```

**Comment by ryotayama** [comment]
↑のコードだと別端末で復元した際にうまくいかない模様。

- How to copy file in iCloud to app sandbox using File Manager
https://stackoverflow.com/questions/17775970/how-to-copy-file-in-icloud-to-app-sandbox-using-file-manager

- Copy iCloud file to sandbox
https://stackoverflow.com/questions/22954215/copy-icloud-file-to-sandbox

- Method for downloading iCloud files? Very confusing?
https://stackoverflow.com/questions/9760236/method-for-downloading-icloud-files-very-confusing

- startDownloadingUbiquitousItemAtURL:error: - NSFileManager | Apple Developer Documentation
https://developer.apple.com/documentation/foundation/nsfilemanager/1410377-startdownloadingubiquitousitemat

**Comment by ryotayama** [comment]
対応した！　バージョン3.58でリリース予定！
