### ISSUE TITLE
再生カーソル位置でループが適用されない

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#463]
https://twitter.com/umeboshikantaro/status/1111594999982907392?s=21
カーソル位置でループが適用されないのを見つけた…！（リンク先に動画あります）

カーソルがマーカーを通り越したらループ範囲も切り替わるのが仕様としていいかなー、と思うのですがどうでしょう？？

**Comment by ryotayama** [comment]
対応した！　バージョン3.14でリリース予定٩( ᐛ )و
