### ISSUE TITLE
マーカー再生画面のループ範囲外の色が変わらない

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#465]
https://twitter.com/umeboshikantaro/status/1111589773037047811?s=21
マーカー再生を保持すると、次にその曲を再生した時に、ループエリア外の色が変わってないのを見つけた！

![Image](https://i.imgur.com/K6YXsBF.jpg)
↑各画面の設定を保持した上で1度停止して再生した画面

![Image](https://i.imgur.com/DQ0aLIG.jpg)
↑一旦ループを解除して再度オンにした画面

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1123493698556153856
これ手元の環境（iPhone 7 Plus、ハヤえもんver.3.13、iOS 12.2）で再現しなかったー！
「こうしたら再現するよ！」みたいな情報があれば大歓迎です！٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.14でリリース予定٩( ᐛ )و
