### ISSUE TITLE
ダブルタップ＋長押しで選択されてない複数選択モードになる

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#467]
https://twitter.com/umeboshikantaro/status/1111840902194946049?s=21
ダブルタップの長押しをすると選択されてない複数選択モードになるんだけど、これって元からだっけ…？？
（リンク先に動画があります）

おぉ、なんにも変えてないから元々だと思うよ！
‎なかなかマニアックだから別途Issue立てて対応しよーかな！٩( ᐛ )و

**Comment by ryotayama** [comment]
直した！　バージョン3.19でリリース予定٩( ᐛ )و
