### ISSUE TITLE
リスト最後の曲の再生が終わる時に、再生中画面の消え方が不自然になる

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#468]
https://twitter.com/umeboshikantaro/status/1116381071820541953?s=21
「1曲のみ」でリスト内の最後の曲が終わる時の、再生中画面の消え方が変な風になってるのを見つけた！（リンク先に動画あります）

ありがとー、再現できた！٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
https://twitter.com/umeboshikantaro/status/1128589885013520384?s=12
リスト最後の曲が再生終わると再生中画面が変な消え方になるやつ、1曲のみじゃなくてもなりました〜

ありがとー、こっちでも再現できてる٩( ᐛ )و

**Comment by ryotayama** [comment]
直した！　バージョン3.16でリリース予定٩( ᐛ )و
