### ISSUE TITLE
録音中にエフェクトをかけて再生しようとすると曲が再生されず、落ちるケースがある

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#469]
https://twitter.com/umeboshikantaro/status/1120881058000412672?s=21

録音→ボーカルキャンセル→再生
という手順だと再生されず、一時停止するとハヤえもんが落ちてしまうのを見つけた！
再起動すると録音されずに残った「hayaemon_record」というファイルが追加されてるっぽいです…！（リンク先に動画あり）

おぉありがとー、再現できた！٩( ᐛ )و

全部は試しきれてないんだけどボーカルキャンセル以外の他のエフェクトでもなるっぽい…！
よろしくです🙏

はいよー、ありがとー！٩( ᐛ )و

これなんか録音の後からエフェクト選択じゃなくて、エフェクト選択された状態で各画面の設定保持されていてもなるっぽい…！

おぉ、なるほどね！
‎りょーかい、ありがとー！٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.19でリリース予定٩( ᐛ )و
