### ISSUE TITLE
コントロール画面の速度音程変更ボタンを押しっぱなしで別のタブに切り替えると、速度音程変更が強制長押し状態になって解除できなくなる

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#470]
https://twitter.com/chiimasuxu/status/1121363476323033088?s=21
めちゃめちゃ笑ったんですが、コントロールでの丸いボタン押したまま別画面行くと止まらなくなる(　^ω^)ﾌﾞﾌｫww
（※リンク先に動画あり）

うぉー、裏技！
‎「だんだん高くする」機能まだ無いのにww
‎ありがとー、直しとくね！٩( ᐛ )و

https://twitter.com/chiimasuxu/status/1121368905211994113?s=21
唐突な思いつきでした…
この状態で歌下手やった時のウニのいやいや感がジワジワきますよ
（※リンク先に動画あり）

https://twitter.com/chiimasuxu/status/1123019786273710080?s=21
もはや地震(前報告した方法で速度遅速高低やった) 
（※リンク先に動画あり）

**Comment by ryotayama** [comment]
対応した！　バージョン3.19でリリース予定٩( ᐛ )و
