### ISSUE TITLE
スワイプ削除の時も確認ダイアログがほしい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#471]
https://twitter.com/chiimasuxu/status/1118769290298023936?s=20
(∩ω∩*`)ハヤえもん、この削除の時も確認欲しいな…

https://twitter.com/ryota_yama/status/1118770892283072512?s=20
ちーますさん、ありがとー٩( ᐛ )و
これも賛否両論ありそうなパターンかも！？

これ思ったんだけど、削除の時確認ダイアログを出すなら出すで統一しちゃった方がいいかも？？
操作方法によって出る出ないの違いが出るのはあまり親切な設計じゃないのかも。。

うん…………よし、そうしよっか！٩( ᐛ )و

「今までサクサク消せてたのに！」ってクレームを危惧したけど、それに対しては「長押しから複数選択モードに移行してサクサク消せますよ！」ってサポートができるから今なら大丈夫だと思う！

それかこっちをタップされた時だけダイアログを出すとかできればどうかな…？？
スワイプで左端まで行く誤操作ってあんまないと思うけど、タップの方の誤操作はありそう？
![Image](https://i.imgur.com/vzcRweb.jpg)

あら、自分は逆のイメージを持ってた……！
スワイプ→削除ボタンをタップはツーアクションだけど左端までスワイプするのはワンアクションだから、誤操作が多いのかな……と！

アクションが複雑か単純かどうかってのもあるけど、確かにアクション数が多いか少ないかってのもありそうよね…！
複数選択モードから削除してくださいってサポートができるのはかなりいいと思う！👏

おっけー、じゃあ削除確認は常に出すって方向で対応しとくよ！
いずれは「ごみ箱」の概念を付けたいなーとも思ってる！

ありがとう！「これひょっとしてそのまま消えちゃうのかな？」って恐る恐る試してたから助かる🙏
ゴミ箱いいよねー！作るとしたら再生リスト一覧画面の1番下とかかな？？

うんうん、そうだねー！
将来的に作る予定のもう一個上の階層（すべての曲とかアーティストとかあるところ）の一番下なのかもしれないけど、まだその画面が無いから想像しづらいなw

ああー確かに！そっちの方が分かりやすいね！
端末シェイクしたら削除を取り消しますか？とかもあるといいよね…！

あー、それも必要だね٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.14でリリース予定٩( ᐛ )و
