### ISSUE TITLE
「キャンピングカー」購入時の挙動不具合［不具合］

### ISSUE THREAD

**Issue by chiimasu** [ryotayama/hayaemon_ios_issues#472]
https://twitter.com/chiimasuxu/status/1121916099899973632
①キャンピングカーの購入時
appleIDで支払う（私の場合はTouchIDで支払いました）
↓
読み込み
↓
「購入完了しました」の表示が出る

この直後に、ハヤえもんのホーム画面に戻ってきたところ、「変更しますか？」のメッセージが出ず、購入がされていない状態の画面になっていました。

②その後、「購入する」→「購入済み」と押したところ、通常通りできたのですが（請求されることなく）、「ばふん」を設定しますか？の画面になりました。

**Comment by ryotayama** [comment]
対応した！　バージョン3.14でリリース予定٩( ᐛ )و
