### ISSUE TITLE
下の再生画面を閉じている途中で、別の曲を選択すると起きるバグ

### ISSUE THREAD

**Issue by chiimasu** [ryotayama/hayaemon_ios_issues#473]
https://twitter.com/chiimasuxu/status/1112025226559127552
（リンク先動画）
検証過程で出た不具合です
閉じてる間にほかの曲をタップするというマニアック操作で出来ました(真顔)

うぉー、ちーますさん！
すごい、ありがとー！
できたできた！٩( ᐛ )و
![image](https://user-images.githubusercontent.com/50126690/56939195-035dc000-6b42-11e9-84ab-3106e3fb8d3e.png)

**Comment by ryotayama** [comment]
直した！　バージョン3.19でリリース予定٩( ᐛ )و
