### ISSUE TITLE
画面不具合 1.再生中画面からⅩ以上の端末でタスク一覧 2.ハヤえもんタップで画面復帰、同時に下スワイプで閉じようとする

### ISSUE THREAD

**Issue by Himana365** [ryotayama/hayaemon_ios_issues#476]
https://twitter.com/ryota_yama/status/1121429816958263296?s=21
ハヤえもんiOS版ユーザーさんからDMもらった方法試してみたら、画面がおかしくなるの再現できた嬉しい！

◆再現方法
①ハヤえもんの再生中画面にした状態で、iPhone X以上の端末でタスク一覧を出す
②ハヤえもんをタップして画面を復帰させると同時に下にスワイプして、再生中画面を閉じようとする

**Comment by ryotayama** [comment]
対応した！　バージョン3.19でリリース予定٩( ᐛ )و
