### ISSUE TITLE
音をトランシーバー風にするエフェクトを追加してほしい

### ISSUE THREAD

**Issue by Himana365** [ryotayama/hayaemon_ios_issues#477]
https://twitter.com/ryota_yama/status/1124169868939370497?s=21
神アプリです！
★★★★★
白麗靈夢
去年から愛用させていただいてますが、色々なことに使えて超便利です。日常生活が忙しい中でこんな素晴らしいアプリを開発して下さりありがとうございますm(_ _)m
これからもアプリ開発頑張って下さい！
このアプリはずっと使い…

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1124285943169540096
ハヤえもんでトランシーバー風にするイコライザ、SonoCaさんが他のソフトを参考に考えてくれましたー！
これめっちゃいい！　もうこのまま採用しようかなと！
考えてくれたSonoCaさんに感謝！
![D5pEGYiUIAUUyzN](https://user-images.githubusercontent.com/6075785/57175741-2d88e800-6e8a-11e9-9c4c-da56331ef46b.jpg)
![D5pEGYhV4AAAwfU](https://user-images.githubusercontent.com/6075785/57175744-337ec900-6e8a-11e9-9f03-c64b064e8b12.jpg)
![D5pEGdcV4AAlpGK](https://user-images.githubusercontent.com/6075785/57175746-35e12300-6e8a-11e9-9b5a-faab92d5b3da.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.54でリリース予定！
