### ISSUE TITLE
課金アイテムを購入前にプレビューできるようにしたい

### ISSUE THREAD

**Issue by Himana365** [ryotayama/hayaemon_ios_issues#478]
バージョン3.13

https://twitter.com/ryota_yama/status/1124172426366017536?s=21
課金アイテム機能、やっぱプレビュー機能（実際にコントロール画面に適用してみたらどうなるのかを確認できる機能）があった方が良さそうだね！　いずれ！٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1135673582418243584
↑こちらのやりとりで仕様が決まった為、転記します٩( ᐛ )و

![D8K5Gb0XsAYdrxX](https://user-images.githubusercontent.com/6075785/58845563-ad3aea00-86b6-11e9-8c54-1d9418e37abb.jpg)
![D8LCCC5XYAAlHdB](https://user-images.githubusercontent.com/6075785/58845569-b035da80-86b6-11e9-9fbe-b6e70a9639ae.jpg)

•用意するのは日本語版と英語版
•プレビューサイズは元の80％表示
•動きはのの字×∞ループ

**Comment by ryotayama** [comment]
対応した！　バージョン3.22でリリース予定٩( ᐛ )و
