### ISSUE TITLE
[要望]ベースの耳コピ（オクターブ上げ）をオンオフする際、速度は変えないようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#480]
夜遅くにすみません、
速度変えてても、ベースのオクターブやると速度が戻ってしまうのって認知済みでしたっけ………🤔
https://twitter.com/chiimasuxu/status/1117455489502023680?s=09

**Comment by ryotayama** [comment]
対応した！　バージョン3.54でリリース予定！
