### ISSUE TITLE
長押し可能な小ボタンについて、長押し中に指を離す前からハイライトが戻ってしまう

### ISSUE THREAD

**Issue by Himana365** [ryotayama/hayaemon_ios_issues#485]
あーそうだった、プラマイボタン長押しの時ハイライトが戻ってしまうのもあった💦 指離した時に濃い青に戻すこととかできますか…！？！？
https://twitter.com/umeboshikantaro/status/1126471575778127873?s=21

**Comment by ryotayama** [comment]
対応した！　バージョン3.27でリリース予定٩( ᐛ )و
