### ISSUE TITLE
イコライザのカスタマイズやリバーブ（カスタマイズ）画面のスライダーについて、曲の再生中に値を変更すると画面表示がカクつく

### ISSUE THREAD

**Issue by Himana365** [ryotayama/hayaemon_ios_issues#486]
イコライザのカスタマイズやリバーブ（カスタマイズ）画面のスライダーについて、曲の再生中に値を変更すると画面表示がカクつく
https://twitter.com/umeboshikantaro/status/1126701398614142979?s=21

**Comment by ryotayama** [comment]
対応した！　バージョン3.18でリリース予定٩( ᐛ )و
