### ISSUE TITLE
iTunesのファイル共有で再生リスト単位でフォルダを分けてほしい

### ISSUE THREAD

**Issue by Himana365** [ryotayama/hayaemon_ios_issues#487]
Android版にリバーブ（カスタマイズ）を付けたら、iOS版の方で長旅にでる予定٩( ᐛ )و

‎①iTunesのファイル共有で、再生リストをフォルダ単位で管理できるようにする

‎→iTunesのファイル共有上、どの再生リストの曲なのかが分かるようになり、特定の再生リストに曲を追加できるようになる💡
https://twitter.com/ryota_yama/status/1126805883596361728?s=21

**Comment by ryotayama** [comment]
対応した！　バージョン3.16でリリース予定٩( ᐛ )و
