### ISSUE TITLE
「リバーブ（カスタマイズ）」の設定内容をテンプレートとして保存する機能がほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#490]
しかもこれ、「テンプレートとして何種類もの設定を保存しておきたい」ってニーズが出てきそうだなー。まぁ、少しずつやっていこー！٩( ᐛ )و 
https://mobile.twitter.com/ryota_yama/status/1125838342069743616

**Comment by ny-yamana** [comment]
リバーブ(カスタマイズ)の保存機能が欲しいです(小声)
https://mobile.twitter.com/fuwa_kagari/status/1127185256551870466?s=21

**Comment by ryotayama** [comment]
ver.3.24でリリース済み٩( ᐛ )و
