### ISSUE TITLE
リバーブ（カスタマイズ）でパラメータを初期状態にリセットする機能がほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#491]
カスタマイズリバーブのリセット的なものがほしいです
https://mobile.twitter.com/tappi_otomad/status/1127158287588216832?s=21

**Comment by ny-yamana** [comment]
カスタマイズの保存機能が云々って話が上がってると思うんですが、自分的にはリセット機能が欲しいです(現状だとタスクキルするしか方法がないので…)
https://mobile.twitter.com/_72_55_78_/status/1127188880686493702?s=21

**Comment by KanzakiSaki** [comment]
https://twitter.com/umeboshikantaro/status/1127750856407863296?s=21
リバーブのリセットはこんな感じかな？？　コントロール画面と同じパーツを使ってみた
![Image](https://i.imgur.com/93V0Oen.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.16でリリース予定٩( ᐛ )و
