### ISSUE TITLE
iPadの画面分割機能に対応してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#492]
ハヤえもんがiPad Proの分割画面に対応していないことが判明
改善をお願いします（；＿；）
https://mobile.twitter.com/senseinoohanash/status/1110793151004827653

**Comment by ny-yamana** [comment]
ipadのSplit Viewに対応していただくことは可能でしょうか？
https://mobile.twitter.com/hatena_hanata/status/1127601788461256704?s=21

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1138243317940940802?s=21
#ハヤえもんAppStoreでのやりとり
最近iPadを使うようになって・・・
★★★★☆
MarsIarc
iPhoneやiPod touchの要望はほかの方に任せるとして・・・
iPadのsplitviewに対応してほしい！
アプリを隣に表示しながら、ほかのアプリで採譜や記録、検索などができれば、利用の範囲がまた１段階広がるよう…

**Comment by ryotayama** [comment]
対応した！　バージョン3.29でリリース予定٩( ᐛ )و
