### ISSUE TITLE
「各画面の設定を保持」機能について、コントロール画面の連動ボタンをオンにした時点で保持内容が更新されない

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#495]
多分エフェクトとかは関係ないと思うんですけど、
速度変更してから一緒に動くやつ付けるとハヤえもんタスクキルした時に音程が保持されないっぽいです
https://mobile.twitter.com/chiimasuxu/status/1128479199247736832

**Comment by ryotayama** [comment]
対応した！　バージョン3.16でリリース予定٩( ᐛ )و
