### ISSUE TITLE
リバーブ（カスタマイズ）画面にランダムボタンを追加したい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#498]
うぉー、こうなってくるとリバーブ（カスタマイズ）とかもランダム機能欲しくなってきた！٩( ᐛ )و
https://mobile.twitter.com/ryota_yama/status/1128700496422637568

**Comment by arigayas** [comment]
うめさんのスクリーンショットを。
![D6nazqCUUAEIQR0](https://user-images.githubusercontent.com/11251874/57825324-5342b500-77d9-11e9-9075-c182178e7c35.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.21でリリース予定٩( ᐛ )و
