### ISSUE TITLE
再生中画面から再生バーに切り替えると再生ボタンの表示がおかしくなってしまう

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#499]
ああー！！最新版アプデ後なんですけど再生中バーの再生ボタンがでかくなってしまうのを見つけた…！
再生中でも一時停止ボタンじゃなくて再生ボタンになってます…！
https://mobile.twitter.com/umeboshikantaro/status/1129261525019926531

**Comment by arigayas** [comment]
動画のあるツイート
https://twitter.com/Maddnes40227162/status/1129996654042537984
@ryota_yama 
バグってるので報告します。

**Comment by ryotayama** [comment]
修正しました！　バージョン3.17でリリース予定٩( ᐛ )و
