### ISSUE TITLE
iPhone機能追加：再生リストの画面

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#50]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/53

2017.11.08
![image](https://user-images.githubusercontent.com/33012932/44827869-2bfa8680-ac50-11e8-96db-a098231f08dd.png)
# 再生リスト一覧画面で必要な機能：
## 再生リスト一覧画面ヘッダー部分：
- ソート(再生リスト名、発売日)-
- 単語検索欄
-- 単語検索欄では何を検索の対象にするのでしょうか？
--- 対象は曲名、アーティスト名、再生リストの作成日、再生リスト名の全部？
## 再生リスト一覧画面リスト表示部分：
- 再生リスト名を表示
-- 再生リスト名をタップすると「再生リスト個別画面」を開く
- 再生リストの曲数
- 画面右下に「新規作成」ボタンを表示
--「新規作成」ボタンをタップすると「再生リスト個別画面」を開く
# 再生リスト個別画面で必要な機能：
## 再生リスト個別画面ヘッダー部分：
-「再生リスト一覧画面」に 戻る ボタン

- 再生リスト名を表示
- 再生リスト名をタップすると再生リスト名を編集出来るようになる

## 再生リスト個別画面リスト表示部分：

- リストの何番目かを表示
- 各曲が収録されているアルバムのジャケット画像
- 各曲の曲名を表示
- 各曲が収録されているアルバム名
- 各曲に対して歌詞データがあれば歌詞カードアイコンを表示する
- 各曲の長さを[分分分:秒秒]表示
- 画面右下に「曲を追加」ボタンを表示
--「曲を追加」ボタンをタップすると「iTunes/Dropbox/カメラロール」などから選択できる

2018.06.04
再生リストで関連すると思うのでコメント追加： #188

**Comment by ryotayama** [comment]
バージョン1.58で再生リストの並べ替え画面を作りました！
今後の機能追加は別途Issueを立てる事とし、このIssueはClose扱いとします٩( ᐛ )و
