### ISSUE TITLE
Dropboxから読み込んだ曲を再生しようとすると「インターネット接続がオフライン」というエラーが出るケースがある

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#501]
iOS verの最新版ですがネット接続されていてもオフラインの旨msgが表示されます。iOSは12.2です。
https://mobile.twitter.com/tomezaemon/status/1129630221139828736

**Comment by ny-yamana** [comment]
普段からアプリを愛用させて頂いていますが、突然オフライン扱いになり再生出来なくなりました！モバイル通信でも3つあるWiFiを切り替えても変わらず、携帯を再起動しても変わりません。
https://mobile.twitter.com/Itgpo/status/1129765461573423106

**Comment by arigayas** [comment]
### 良太さんのリプライ
>「再度Dropboxから読み込み直したら再生できた！」という声もありましたので、お試しいただけたら嬉しいです！」

何かしらのフラグの処理が間違えていたのかな？

**Comment by arigayas** [comment]
わんこさんが詳細な報告してくれたようですね。
https://twitter.com/wnk___0912/status/1130318488118030337

### 1枚目
![Dropboxbug01_D6-ypNjV4AMeANs](https://user-images.githubusercontent.com/11251874/58005703-367fe780-7b21-11e9-942c-1fd7cbfc9489.jpg)

### 2枚目
![Dropboxbug02_D6-ypNhUwAEYjAr](https://user-images.githubusercontent.com/11251874/58005716-3c75c880-7b21-11e9-84be-551297121c9b.jpg)

### 3枚目
![Dropboxbug03_D6-ypNjU0AAmRrE](https://user-images.githubusercontent.com/11251874/58005724-40a1e600-7b21-11e9-9bb5-75f9cc5a5d2c.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.17でリリース予定٩( ᐛ )و

**Comment by ny-yamana** [comment]
はやえもん、dropboxから曲ダウンロード出来なくなってる？
https://twitter.com/kv_creator/status/1129673558483845120

**Comment by ny-yamana** [comment]
iPadをアップデートしたところDropboxから追加、Dropboxに入っている曲の再生ができなくなってしまいました。
iPadを再起動しましたがだめでした。
バージョンは(iOS ver.3.16)です。
https://twitter.com/uz_mizuho/status/1130060452170362880

**Comment by ny-yamana** [comment]
#ハヤえもんAppStoreでのやりとり
何？ オフラインって
★☆☆☆☆
1 day ago by ワンダー☆
iOS | Version 3.16 | Japan

インターネットがオフラインの状態って書かれてあるけど、ちゃんと繋いでるのに
https://twitter.com/ryota_yama/status/1130290789223813120

**Comment by ny-yamana** [comment]
ネット繋がってるのにこれ出てきたんですけど、なんですかこれ
https://twitter.com/kento_825/status/1129584232978735105
