### ISSUE TITLE
「だんだん高く」「だんだん低く」エフェクトを追加してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#510]
ループごとに音の高さ変えて転調させたいなって思いますた(*´ω`*)
https://mobile.twitter.com/emeen231/status/1102867743815004160

**Comment by ny-yamana** [comment]
たとえば、「一曲リピートで、一曲終わるごとに半音ずつ上がっていく」とかも面白そう...？とか思ったり...
https://mobile.twitter.com/mikuta0407/status/1101115058510225408

**Comment by ryotayama** [comment]
https://twitter.com/OnkaiManiac/status/1155437251091808256?s=20
ハヤえもん iOS ver.3.27 iOS 12.3.1 iPhone8,1  要望なのですがだんだん早くとだんだん遅くがあるのでだんだん高くとだんだん低くは実装することは出来ないでしょうか？

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1158165323587059712?s=20
#ハヤえもんAppStoreでのやりとり
追加要望
★★★★★
インフィニティ(INF)
「だんだん高く」と「だんだん低く」の音程が徐々に変化するエフェクトの追加はどうでしょうか？
だんだん速く&遅く のエフェクトがあるので、音程も同じ機能があればいいと思います。
速度を変化させたくない時に使えそう…

**Comment by ryotayama** [comment]
対応した！　バージョン3.54でリリース予定！
