### ISSUE TITLE
「だんだん速く」「だんだん遅く」機能について、ループごとに加速／減速できる機能がほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#511]
ラジオボタンの進捗。2枚目の方がそれっぽいかな？
上の白丸の方が大きく見える錯視。。（同じ大きさです
https://mobile.twitter.com/UmeboshiKantaro/status/1105048883581747200

**Comment by arigayas** [comment]
### 1枚目
![01_D1Xrm_IVsAAMCMw](https://user-images.githubusercontent.com/11251874/58226331-38d08480-7d61-11e9-9440-6190bb82d199.jpg)

### 2枚目
![02_D1XrtYjU8AAZsD3](https://user-images.githubusercontent.com/11251874/58226341-3ec66580-7d61-11e9-85c6-5121e83e66b6.jpg)

**Comment by ny-yamana** [comment]
「一曲ループ再生時に、頭に戻る度に設定した値ぶん再生速度が変わるエフェクト」を開発リストに加えていただけたら嬉しいです。
https://mobile.twitter.com/toshiya_c/status/1133489409087627264

**Comment by ryotayama** [comment]
https://twitter.com/prince_angel_v/status/1185592015406301185?s=20
楽器練習者としての希望なのですが、リピート回数に応じて速度が上がっていく機能があれば嬉しいです。例えば、x回リピートごとにy%スピードを変えれる、ような機能です。irealpro（コードを入力したら伴奏するソフト）にある機能で便利なので、ハヤえもんにもあれば最高です！

早速ありがとうございます！🙏
ハヤえもんmacOS版だと、エフェクト→再生速度→だんだん速くするメニューがイメージ的に近いでしょうか？？

ありがとうございます！だんだん上がっていくより、リピートごとにきっちり上がっていく方が練習には向いていると思います。mac何故か英語版になってインストールされてて修正を試みていますorz

ループごとに上がっていくオプションもありますよ！👍
言語の切り替えはSystem→Languageから切り替えられます💡

お〜〜〜！！！！ありがとうございます！！！mac版はループごとにもできるのですね！！！これはすごいです！！！iOSにはこの選択肢なかったと思うのですが僕が気付いてないだけでしょうか？！早速日本語化してみます！！

そうなんですー、iOS版の方はデザインはすでにできているのでいずれ実装したいと思います！👍

これはすごいです！！！！できるまではリピートごとの速度アップはmac版で使わせていただきます！！！！

**Comment by ryotayama** [comment]
対応した！　バージョン2.42でリリース予定！٩( ᐛ )و
