### ISSUE TITLE
ループ画面の虫眼鏡ボタンについて、限界値まで達した場合は薄いグレーにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#512]
思ったんだけどループ画面の虫眼鏡って、波形をこれ以上縮小しきれない時と拡大しきれない時はグレーにした方がいいのかな…？？
https://mobile.twitter.com/UmeboshiKantaro/status/1108296224547860481

**Comment by ryotayama** [comment]
対応した！　バージョン3.18でリリース予定٩( ᐛ )و
