### ISSUE TITLE
ループ画面の虫眼鏡ボタンについて、再生中以外は無効（薄いグレー）にしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#513]
さっそく1個いいかな！？！？ループ画面の虫眼鏡なんだけど、これって再生してないときは両方ともグレーになるのがいいのかな…？？
https://mobile.twitter.com/UmeboshiKantaro/status/1131446209577533440

**Comment by ryotayama** [comment]
対応した！　バージョン3.18でリリース予定٩( ᐛ )و
