### ISSUE TITLE
再生リスト画面の曲ごとのメニューに「アートワークを変更」を追加してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#514]
もしよかったらアートワークの変更をここから出来るようにしてくれると嬉しいです…！
https://mobile.twitter.com/D_esu_2/status/1131634414515961858

**Comment by arigayas** [comment]
### ユーザーさんが提案したスクリーンショット
![resized_D7Rff1EUcAAP1ZJ](https://user-images.githubusercontent.com/11251874/58301638-31bd7b00-7e22-11e9-9c89-e50328d530bd.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.21でリリース予定٩( ᐛ )و
