### ISSUE TITLE
複数選択モードに移行する際、再生していたファイルが選択状態になってしまう

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#515]
再生終了直後に別のファイルを選択すると、勝手に再生していたファイルまで選択されます。
https://mobile.twitter.com/tt_anti/status/1131822864271724544

**Comment by ryotayama** [comment]
◆メモ
PlaylistViewController.mのdidSelectRowAtIndexPathで、self.bMultiSelectingがNO（複数選択モードではない）の時に[self.tableSongs deselectRowAtIndexPath:indexPath animated:NO];を呼び出す。

**Comment by ryotayama** [comment]
直した！　バージョン3.21でリリース予定٩( ᐛ )و
