### ISSUE TITLE
複数選択モードに保存／エクスポート機能を追加してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#520]
まさにこんな感じで考えていたんだよね！
でも言語的な説明がないとアイコンだけじゃ伝わらないと思って、翻訳の手間とかを考えて後回しにした…！
https://twitter.com/UmeboshiKantaro/status/1081199351525855232

**Comment by ny-yamana** [comment]
まとめて選択した時に他のアプリ（iMovieとかDocuments）に保存エクスポート出来たら良いなと思いました
もし可能であればお願いします(๑>◡<๑)
https://twitter.com/Almaty_Game/status/1132613390700953600

**Comment by arigayas** [comment]
> まとめて選択した時に他のアプリ（iMovieとかDocuments）に保存エクスポート出来たら良いなと思いました
> もし可能であればお願いします(๑>◡<๑)
> https://twitter.com/Almaty_Game/status/1132613390700953600

### 上記コメントのスクリーンショット
![resized_50_D7fZ391UIAE5-Nu](https://user-images.githubusercontent.com/11251874/58382215-9f280200-8002-11e9-83c4-1fd852bac6b5.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.23でリリース予定٩( ᐛ )و
