### ISSUE TITLE
カスタマイズ系の機能がVoiceOverに対応しきれていないので直してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#521]
やっぱりリバーブのカスタマイズ機能がVoiceOver環境で±のボタンを押してもスワイプしても値が変更されませんでした。
ぜひ直していただけるとありがたいです。
https://twitter.com/93gEPdOZaRqcOvz/status/1129684739424546816

**Comment by ny-yamana** [comment]
ハヤえもんのリバーブのカスタマイズがボイスオーバーを使うとできません。もしりょーたさんがこれを見ていらしゃったら、改善していただけると助かります。
ボイスオーバーという特殊な環境なので可能な限りでお願いします
https://twitter.com/ijokuzuy/status/1129397230681460741

**Comment by ryotayama** [comment]
◆メモ
EffectViewController.mの各set関数の中でaccessibilityValueの値をセット。

例：setCompGain関数の中で、self.sliderCompGain.accessibilityValue = self.labelCompGain.text; とする

**Comment by ryotayama** [comment]
対応した！　バージョン3.21でリリース予定٩( ᐛ )و
