### ISSUE TITLE
歌へたエフェクトについて、音程と速度のゆらぎを調整できるようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#528]
俺「休んで…wl
⁇「させるかぁ！」
⁇「歌ヘタの音程only versionを作れぇ！」
俺「くっ！きっ、貴様！」
⁇「ははは！更新待ってるぞ！」
https://mobile.twitter.com/gakihure/status/1018085662363226113

**Comment by arigayas** [comment]
良太さん
歌ヘタの詳細設定みたいな画面で、音程のゆらぎと速度のゆらぎを調整できたらいいのかなぁ？？


フレンさん(要望を出した方)
あー、それ良いかもw

**Comment by ryotayama** [comment]
対応した！　バージョン3.27でリリース予定٩( ᐛ )و
