### ISSUE TITLE
iPhone機能追加：全曲リスト画面(再生中)

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#53]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/55

2017.11.08
![image](https://user-images.githubusercontent.com/33012932/44828370-8563b500-ac52-11e8-8a15-081fb5394bb4.png)
# 全曲リスト画面(再生中)機能：全曲リスト画面(停止中)のヘッダー部分の上部に設置する
- 再生中の曲名
- 再生中の曲名を収録しているアルバム名
- 再生中の曲名を演奏しているアーティスト名
- 再生中の曲のシークバー
- 再生中の曲の現在の再生時間
- 再生中の曲の時間
# 全曲リスト画面(再生中)機能：
- 再生中の各曲が収録されているアルバムのジャケット画像の左側に「▸」を表示

**Comment by KanzakiSaki** [comment]
再生中バーは実装済みなので、こちらのissueはcloseします！
全曲リスト画面に関しては #52 に続きます！
