### ISSUE TITLE
曲の削除ボタンが追加ボタンと重なる場合があるのを直してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#534]
曲削除がしにくいです…
https://mobile.twitter.com/gareki_nana_/status/1099294916813873152

**Comment by arigayas** [comment]
### 指摘ツイートのスクリーンショット
![resized_D0F65c8UwAAf54L](https://user-images.githubusercontent.com/11251874/58545911-3aa5b680-823f-11e9-8534-d7b2db49c9b2.jpg)

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1135378415333171200
うめちゃーん、これって一時的に「＋」ボタンが右か下に逃げてくれる仕様でいいかなぁ？٩( ᐛ )و

あー！スワイプ削除が出たらボタンが避けてくれるの！？アニメーションで！？それできたらいいなぁ…！

わー、嬉しい！٩( ᐛ )و
ちなみに自分から言っておいてアレだけど、できるかどうか分かんないから調べてみるね！
いったんヒョコッと右に避ける感じで考えてみる！

**Comment by ryotayama** [comment]
直した！　バージョン3.22でリリース予定٩( ᐛ )و
