### ISSUE TITLE
イコライザのアクションシートを分離したい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#539]
イコライザ個別のアクションシート内に「テンプレートの並べ替え」「すべてのテンプレートを初期化」が入っているのが違和感があるため、そちらはイコライザ全体のメニューとして分離したいです。
　
　
**イコライザ一覧画面↓**

![イコライザ一覧画面2](https://user-images.githubusercontent.com/32741225/58685692-88452f00-83b7-11e9-8ef1-6aacb0f2f491.png)

「オフ」ボタンの右側に「•••」ボタンを新設。
　
　
**全体のアクションシート↓**

![イコライザ一覧画面2アクションシート1](https://user-images.githubusercontent.com/32741225/58685773-c5a9bc80-83b7-11e9-874f-56c5ad89f71e.png)
　
　
**個別のアクションシート↓**

![イコライザ一覧画面2アクションシート2](https://user-images.githubusercontent.com/32741225/58685791-d3f7d880-83b7-11e9-8ff8-bbd9caa210b6.png)

テンプレートをコピーしてから微調整するケースもあるかな？と思い「コピー」のメニューを新たに入れてみました。

**Comment by ryotayama** [comment]
対応しました！　バージョン3.21でリリース予定٩( ᐛ )و
