### ISSUE TITLE
「各画面の設定を保持」した曲を再生する際、該当するイコライザのテンプレートが選択された状態になるようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#540]
イコライザのやつだけまだ見てる途中だったんだけど、「各画面の設定を保持」した時に該当するテンプレートが選択されてないのは仕方ないかな…？
https://mobile.twitter.com/UmeboshiKantaro/status/1134567691358859264

**Comment by ryotayama** [comment]
対応した！　バージョン3.25でリリース予定٩( ᐛ )و
