### ISSUE TITLE
再生リスト名が空の場合、OKを許可せずエラー扱いになる（画面を横に揺らす）ようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#542]
再生リスト名が空の状態許可してたの気が付かんかった。。(*ﾉﾉ)
無名で登録しようとしたら自動で「再生リスト」「再生リスト2」とかって入るのがいいのかなこれって…
https://mobile.twitter.com/UmeboshiKantaro/status/1134579209718837248

**Comment by ryotayama** [comment]
◆メモ
UIAlertController中のUITextFieldに文字が入っていない場合はボタンを押せないようにする
http://ai-argument.hatenadiary.jp/entry/20150409/1428513848

**Comment by ryotayama** [comment]
https://twitter.com/UmeboshiKantaro/status/1134583546293628928
あとはVoiceOverで読み上げてくれるようにメッセージも出せたら1番いい気がする…！
![D77ZuBIUYAA06z9](https://user-images.githubusercontent.com/6075785/58742556-7e2b3b00-8460-11e9-9036-2510cbef4fa9.jpg)

これ赤いエラーメッセージを出そうとするとオリジナルでダイアログを作らないといけないから、２段階に分けようかと思うけどいいかなぁ？٩( ᐛ )و

①空をはじく
②エラーメッセージを出す

おお！！そういうことか！いいと思うよ！
入力系のポップアップってオリジナルで作ったことなかったもんね…！

うんうん、ありがとー！
色々調べたら空の時にOKを押されたら画面を揺らすってのもオリジナルじゃないと無理みたい！
空白の時はOKボタン自体押せないってのならギリギリできそうだけど、ひとまずこれでもいいかなぁ？
![D78QL-eVsAALEWl](https://user-images.githubusercontent.com/6075785/58742563-926f3800-8460-11e9-99e5-c70a3764716c.jpg)

おお！！一文字でも入力されたらOKが押せるのか！！それ1番良さそう！！👏

ありがとー、その路線で進めてみるね！٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.21でリリース予定٩( ᐛ )و
