### ISSUE TITLE
イコライザ画面のテンプレート追加ボタンにVoiceOver用のテキストを設定してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#543]
あー、このボタンVoiceOver用のテキスト仕込むの忘れてるわ！
あとで対応しよーっと！٩( ᐛ )و
https://mobile.twitter.com/ryota_yama/status/1134686100704808960

**Comment by ryotayama** [comment]
対応した！　バージョン3.21でリリース予定٩( ᐛ )و
