### ISSUE TITLE
速度／音程のローラー上部のメニューに「リセット」を追加してほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#547]
いま美容室でテストしてるけどこれやばい！便利！
そしてリセットボタンこの中にも欲しい😂 
https://mobile.twitter.com/UmeboshiKantaro/status/1134732020003758080

**Comment by ryotayama** [comment]
対応した！　バージョン3.21でリリース予定٩( ᐛ )و
