### ISSUE TITLE
iOS 9.3.5の環境で他のアプリからハヤえもんにエクスポートする際、ハヤえもんを立ち上げていないとデータが取り込まれない

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#548]
ハヤえもん iOS 3.20 今日やったらPuffinから取り込めなくなっていました(T_T)ここに関係する修正なんてあったかなあ…?
https://twitter.com/cranberry_talks/status/1134833000376545280
↓
こっちの環境で同じ事をしてみたけど、うまくいっちゃった！
「ハヤえもんの再インストール」「Puffinでの曲の再ダウンロード」「Puffinの再インストール」あたり試してみてくれるかなぁ？
https://twitter.com/ryota_yama/status/1134959985471832064
↓
うまくいかない:ハヤえもんを「立ち上げてない」状態でPuffinを操作
うまくいく:ハヤえもんを「立ち上げた」状態でPuffinを操作

もしかして「エクスポート先アプリは立ち上げておく」って常識?
色んなファイラーからハヤえもんにエクスポートしようとして、今のところ全滅だったのも このせい…?
https://mobile.twitter.com/cranberry_talks/status/1135004783553597441
↓
立ち上げてない状態でもこっちの環境（iOS 12.3.1、ハヤえもん3.20、iPhone 7 Plus）だとうまくいくんだよなー！
https://twitter.com/ryota_yama/status/1135006071796379648
↓
iPad第3世代なので、iOS9.3.5で止まってます…
https://twitter.com/cranberry_talks/status/1135006921545506816
↓
うぉー、iOS9.3.5か！
なんかiOSのバージョンによる環境の違いのような気がしてきた！
結論出るか分かんないけど、調べてみるね！
ありがとう！
https://twitter.com/ryota_yama/status/1135007479467634688

**Comment by ryotayama** [comment]
バージョン3.49で修正済みの為、クローズします！
