### ISSUE TITLE
イコライザ画面でテンプレートのコピーをした場合、コピー先のテンプレートまで自動でスクロールしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#549]
関連:https://github.com/ryotayama/Hayaemon_iOS/issues/550

とりあえず途中まで、、投げときますね、、😇
https://mobile.twitter.com/UmeboshiKantaro/status/1135009976580169733

**Comment by ryotayama** [comment]
対応した！　バージョン3.22でリリース予定٩( ᐛ )و
