### ISSUE TITLE
曲名についても再生リスト名と同様、入力時に空の場合はOKボタンが押せないようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#552]
思ったんだけど曲名も空だと「OK」ボタン押せないようになってた方がいいのかな…？ ここは問題ないのかな…
https://mobile.twitter.com/UmeboshiKantaro/status/1135071429391572993

**Comment by ryotayama** [comment]
対応した！　バージョン3.22でリリース予定٩( ᐛ )و
