### ISSUE TITLE
イコライザ／エフェクト画面について、選択中のものが明確になるようチェックマークを付けるようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#553]
ありがとう！再生中もステータスマークがあるので、背景ブルーにしつつチェックマークつけつつがいいかなって思ってた！
https://mobile.twitter.com/UmeboshiKantaro/status/1135143462175514630

**Comment by ryotayama** [comment]
https://twitter.com/umeboshikantaro/status/1135408399519064064?s=21
ℹ︎ボタン更新しました！確認お願いします〜

あとチェックマークも汎用ボタンのとこに入れといたよー！
こんな感じで適用できればいいなって…🙏
![Image](https://i.imgur.com/C1dLqZb.jpg)
![Image](https://i.imgur.com/x2Llubw.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.29でリリース予定٩( ᐛ )و
