### ISSUE TITLE
イコライザ画面でテンプレート選択中に「＋」ボタンを押した場合は適用中のイコライザの値のまま各スライダーを調整できるようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#554]
ありがとう！
そしてもう1個気になるとこ見つけた！
イコライザオンの状態で新規テンプレートボタン押したら、今のイコライザの値を引き継いでてほしい…！変かな…？？
https://mobile.twitter.com/UmeboshiKantaro/status/1135154362576097281

**Comment by ryotayama** [comment]
対応した！　バージョン3.21でリリース予定٩( ᐛ )و
