### ISSUE TITLE
イコライザ／エフェクト選択中の背景色を再生リストに合わせて青にしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#555]
そうだ前にも少し話出した気がするけど、イコライザとエフェクトの適用中の背景色を、再生中の背景色と同じ色にしてもらえたら統一感が出ていいなって思いました🙏
ほんとはリストの左側にステータスアイコン（✔︎←こんな感じのチェックマーク）つけてあげたい気もするけど…
https://mobile.twitter.com/UmeboshiKantaro/status/1135122449475854336

**Comment by arigayas** [comment]
## 現状のスクリーンショット
### 再生リスト
![resized_PlayList_tD8DD2AxUIAM2urE](https://user-images.githubusercontent.com/11251874/58761994-7e712680-8585-11e9-8540-b2d0cbad158e.jpg)


### イコライザ
![resized_equalizer_D8DD2AuUEAAaIq-](https://user-images.githubusercontent.com/11251874/58761999-84670780-8585-11e9-8157-129533ff0b51.jpg)

### エフェクト
![resized_effect_D8DD2AuU0AIBNc2](https://user-images.githubusercontent.com/11251874/58762001-88932500-8585-11e9-987c-321a8abbe524.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.25でリリース予定٩( ᐛ )و
