### ISSUE TITLE
エフェクト画面について、同じ種類ごとに別画面に階層化したい（リバーブ編）

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#556]
https://twitter.com/UmeboshiKantaro/status/1106758851330609152
今更だけどエフェクト画面なげぇー、、

エコーとリバーブ、階層にした画面考えてみようかな？？ラジオボタン…？？🤔
![D1v_TujVAAU1Ihp](https://user-images.githubusercontent.com/6075785/58773079-b795af00-85f6-11e9-90bc-a160490940f3.jpg)

分類的にはこうかな？？（下が保存エクスポートで反映されないエフェクト
![D1wH_4WVYAERXy7](https://user-images.githubusercontent.com/6075785/58773095-c3817100-85f6-11e9-887e-cbf6f4b372ae.jpg)

こんな感じで階層にするのはどうかな？？というのを考えてみた！ 
![D1xN_3zUgAA1hGe](https://user-images.githubusercontent.com/6075785/58773109-d136f680-85f6-11e9-9d94-c8189526acac.jpg)

おぉ、すごく良いと思う٩( ᐛ )و
パラメータをカスタマイズしたいってニーズも多いから、それとの兼ね合いだけ気になるかな！

ありがとう…！(*ﾉﾉ)
そうそう、そのパラメータってどんな値があるのかな？？何種類かのバランスをスライダーで動かす感じ？？

そう！

こんな感じかな？？（遅レス
![D2Ay2lkU0AYpCQE](https://user-images.githubusercontent.com/6075785/58773137-e9a71100-85f6-11e9-8a4f-912513e6cffe.jpg)

おぉ、いいねいいね！！٩( ᐛ )و
スタジアムエコーとか選んだら下のパラメータにも反映される感じかな？？

そんなことができるのか…！！Σ(ﾟДﾟ )

うんうん、スタジアムエコーのパラメータを基準にちょっと変えたいみたいな人がいるだろうから、その方がいいよね……！

あーーなるほどな…！めちゃ細かいニーズだけどできたらすごく良さそう…！😭🙏

https://twitter.com/ryota_yama/status/1127352072741875712
うめちゃん、もしかして色々踏まえるとこうなのかなぁ？？٩( ᐛ )و 
![D6Uou7lUwAAl4c5](https://user-images.githubusercontent.com/6075785/58773236-40ace600-85f7-11e9-801a-298c357c2431.jpg)
![D6Uou7kU0AA_s4z](https://user-images.githubusercontent.com/6075785/58773241-43a7d680-85f7-11e9-89c5-6063a323194f.jpg)
![D6Uou7mUIAEnhSW](https://user-images.githubusercontent.com/6075785/58773243-460a3080-85f7-11e9-8a03-f26f739020db.jpg)
![D6Uou7yVUAAdVv9](https://user-images.githubusercontent.com/6075785/58773247-47d3f400-85f7-11e9-92fb-b6815bfb3c68.jpg)

すご！！さらに階層ができてる！！Σ（・□・；）
でも…いいと思う！この基本の形ができれば他のエフェクトにも適用できそうよね！

このIssueではまず「リバーブ」を対象に階層化する対応をします！
「名称の変更」や「並べ替え」については、別Issue対応にする事とします！

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1137140348373700608?s=21
thank you for fixing the effect customizer for voiceover users.☺️
★★★★★
Tony Satriano__769
Hello Ryota, Thank you for fixing voiceover so that it can move the effects slighter in the effect customizer properly. So far, I have no new features to request for. The only other feature  that I would like is to record your performance of The parameters that you have   adjusted. Keep up the great work that you have put into this amazing app and I hope in The future,    you could create an app similar to this app or even create a new app entirely.

デベロッパの回答
Hello Tony, I'm glad that you noticed my fix. Oh, thank you for requesting the new feature, I will add the feature for saving customized parameter! I'm so happy that you said "Great work" and "Amazing app". If you have any other requests or bug reports, please send me any time. @ryota_yama is my Twitter account, and you can contact me using Twitter any time. See you!

**Comment by ryotayama** [comment]
◆開発時用のメモ書き
（１）エフェクト画面のプリセットとしては、「リバーブ」１つにする。
（２）「ℹ︎>」ボタンが押されたら、リバーブ専用のテンプレート一覧に遷移する。
（３）リバーブ専用のテンプレート一覧から「ℹ︎>」ボタンが押されたら、リバーブのカスタマイズ画面に遷移できるようにする。
（４）テンプレート一覧右下の「＋」ボタンが押されたら、新規テンプレート作成画面に遷移できるようにする。

**Comment by ryotayama** [comment]
対応した！　バージョン3.24でリリース予定٩( ᐛ )و

**Comment by ny-yamana** [comment]
関連会話の記録:

ハヤえもん iOS 3.15 要望。カスタマイズリバーブに既存リバーブの値を読込みたい。そしたら「バスルームの初期値はこうなのか。そしたらここをいじってみるか…」とかカスタマイズの敷居が低くなりそう。
https://twitter.com/cranberry_talks/status/1127221186155278341
↓
あ！！それ以前案出てましたね！！貼っておきますね！
https://twitter.com/UmeboshiKantaro/status/1127222956910731264
↓
クランベリーさんありがとうございます
うめちゃんも引用ありがとー！٩( ᐛ )و
https://twitter.com/ryota_yama/status/1127350269505703936
