### ISSUE TITLE
イコライザ画面の新規テンプレートボタンが伝わりづらい為、ボタン画像を差し替えたい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#557]
これ新規イコライザ画面なんだけど分かりにくいよねやっぱ…デザイン変えるかも…(´･ω･`;)
https://mobile.twitter.com/UmeboshiKantaro/status/1135331551170842624

**Comment by ryotayama** [comment]
対応した！　バージョン3.22でリリース予定٩( ᐛ )و
