### ISSUE TITLE
再生リスト一覧／曲一覧／イコライザのテンプレート一覧の「コピー」機能について、すぐ近くの行にコピーされるようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#558]
そうだね、、
あ〜隣にコピーされるのと、1番下にコピーされるのが混ざってるのも変なのかな…💦
https://mobile.twitter.com/UmeboshiKantaro/status/1135450021669658624

**Comment by ryotayama** [comment]
対応した！　バージョン3.22でリリース予定٩( ᐛ )و
