### ISSUE TITLE
再生リスト一覧／曲一覧／イコライザのテンプレート一覧について、新規追加時に自動でスクロールするようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#559]
テストしてみたよ！コピー系のスクロールめっちゃいい！！ありがとう！！
そしてここまできたら曲追加と新規再生リストと新規イコライザも、1番下までスクロールされた方がいい気がしてきたごめん(*ﾉﾉ)
https://mobile.twitter.com/UmeboshiKantaro/status/1135665481329680384

**Comment by ryotayama** [comment]
対応した！　バージョン3.22でリリース予定٩( ᐛ )و
