### ISSUE TITLE
スプラッシュスクリーン(ハヤえもんを起動したらすぐに表示される画像)が欲しい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#56]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/58

2017.11.08
https://twitter.com/Pikamu_W7/status/927877086034800640

iPhone版やAndroid版の起動時に間があるので起動作業中なのか不安になるので
ハヤえもんを起動したらすぐに表示される画像が欲しい。

検索語：

- スプラッシュスクリーン，splash screen
- ローンチスクリーン, launch screen
- スプラッシュ画面

**Comment by ryotayama** [comment]
対応しました！　ver.2.77でリリース予定！
↓リンク先に動画があります。
https://twitter.com/ryota_yama/status/1055478945364070400
