### ISSUE TITLE
イコライザ画面の既存テンプレートが選択された場合、エフェクト画面の聴覚トレーニングをオフにするようにしてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#560]
あ、聴覚トレーニングは既存テンプレートとか新規テンプレートを押した時点でオフにした方がいいかなぁ？٩( ᐛ )و

確かに！既存のテンプレート押されたらオフにした方が親切かも…！
新規は…前みたく動的に反映されてたら変かなやっぱ😓
https://mobile.twitter.com/UmeboshiKantaro/status/1136156548042973184

**Comment by ryotayama** [comment]
対応した！　バージョン3.53でリリース予定！
