### ISSUE TITLE
「ベースの耳コピ（オクターブ上げ）」などのイコライザに影響を及ぼすエフェクトを選んだ後、イコライザ画面で新規テンプレートボタンを押すと各スライダーがゼロになってしまっている

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#562]
そういえばイコライザの「ベースの耳コピ」を選択して新規イコライザすると、パラメータの値が反映されるけど、
エフェクトの「ベースの耳コピ（オクターブ上げ）」の方は、新規イコライザに反映されてなくていいのかな？？（コントロール画面には反映されてる
https://mobile.twitter.com/UmeboshiKantaro/status/1136154907566731264
あー、それ考慮漏れだね！
気づいてくれてありがとー！٩( ᐛ )و

考慮漏れだったか💦
サイドギターとかもそうなのかな？？
聴覚トレーニングは…難しいか💦

そうだねー！

**Comment by ryotayama** [comment]
直した！　バージョン3.54でリリース予定！
