### ISSUE TITLE
選択中のテンプレートが削除された場合に、「オフ」が選択された状態にならない

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#565]
よしよし、また発見！　これiOS版でも発生してるなぁ٩( ᐛ )و
□選択中のテンプレートが削除された場合に、「オフ」が選択された状態にならない
#ハヤえもんAndroid版
https://mobile.twitter.com/ryota_yama/status/1137014162024833024

**Comment by ryotayama** [comment]
最新版で修正済みである事を確認済み٩( ᐛ )و
