### ISSUE TITLE
自動Issue登録ツールについて、短縮URLを展開するようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#572]
Issueで管理するべきか分かりませんが、ひとまず。
↓しゅがーくんのこのツールについて、短縮URLを展開できるようにしたいです٩( ᐛ )و
https://twitter.com/12guitar21/status/1137235027186425856

**Comment by ryotayama** [comment]
変な切れ方をしたので手動で直した！　要検証！
٩( ᐛ )و←こいつのせいだったりするかなw

**Comment by ryotayama** [comment]
あと、「title:」を「タイトル：」に「body:」を「内容：」に直したのも原因あるかも。要検証。

**Comment by ryotayama** [comment]
タイトル／内容に直した時に文字数のコードを直し忘れてたのが原因っぽい！

**Comment by sugartarou** [comment]
対応しました〜

**Comment by ryotayama** [comment]
しゅがーくんありがとう！
ちゃんと展開されました！→ #577 
Closeします！٩( ᐛ )و
