### ISSUE TITLE
スマフォ版でスマフォをかなり振ったら再生リストがシャッフルされて自動再生する機能

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#58]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/60

2017.11.09
https://twitter.com/arigayas/status/928543452563783681

ハヤえもんを起動時にスマフォをかなり振ったら再生リストがシャッフルされて自動再生する機能

**Comment by ryotayama** [comment]
ぼくは個人的に「スマホを振る」という操作方法があんまり好きではないんですけど、他の方はどうですかね？
特に反対意見が無ければ却下扱いにしようかなーと考えています٩( ᐛ )و

**Comment by arigayas** [comment]
思いつきでissue登録したので却下でもOKです。

**Comment by ryotayama** [comment]
ありさん、ありがとー٩( ᐛ )و
３日ぐらい待って、「いやいや、斬新でいいじゃん！」って意見が無ければCloseしようと思いまーす！

**Comment by KanzakiSaki** [comment]
ユーザー設定でシャッフル機能のオンオフ切り替えができるとかならアリかな？？

個人的には曲や再生リストの削除後にスマホを振ったら元に戻せるって機能なら嬉しいかな…！

**Comment by ryotayama** [comment]
あー、これは的確……！
iPhoneで「スマホを振る」ってジェスチャーは「取り消し」を意味するので、その方がいいね！
他の意見が無ければこのIssueはCloseして、「取り消せるようにしたい」っていう別のIssueを立てまーす٩( ᐛ )و

**Comment by ryotayama** [comment]
反対意見が無かった為、こちらのIssueについてはCloseします٩( ᐛ )و
