### ISSUE TITLE
エフェクト画面の「オフ」について、イコライザのテンプレート一覧画面とデザインを統一してほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#609]
https://twitter.com/academic_siona/status/1139418279443701760

**Comment by arigayas** [comment]
### スクリーンショット1枚目
![resized_D9AG4RfU8AAT9le](https://user-images.githubusercontent.com/11251874/59545222-9e75f200-8f56-11e9-9593-1446e4170b61.jpg)

### スクリーンショット2枚目
![resized_D9AG4RiVUAAKAJ_](https://user-images.githubusercontent.com/11251874/59545223-9e75f200-8f56-11e9-87b4-d159df8b04f0.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.27でリリース予定٩( ᐛ )و
