### ISSUE TITLE
イコライザのカスタマイズ画面が表示されている際に下部のイコライザボタンを押したら、イコライザ一覧に戻るようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#615]
https://twitter.com/umeboshikantaro/status/1141290141958303744

**Comment by arigayas** [comment]
スクリーンショットでは`エフェクト`を指しているけど、
スクリーンショットがあればわかりやすいと思ったので添付します。
![resized_D9atVFuU8AAkafY](https://user-images.githubusercontent.com/11251874/59766800-ec368580-92db-11e9-8925-0b482291b344.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.26でリリース予定٩( ᐛ )و
