### ISSUE TITLE
エフェクト詳細画面が表示されている際に下部のエフェクトボタンを押したら、エフェクト一覧に戻るようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#616]
https://twitter.com/umeboshikantaro/status/1141290141958303744

**Comment by arigayas** [comment]
![resized_D9atVFuU8AAkafY](https://user-images.githubusercontent.com/11251874/59766800-ec368580-92db-11e9-8925-0b482291b344.jpg)

関連するissue
#615

**Comment by ryotayama** [comment]
対応した！　バージョン3.26でリリース予定٩( ᐛ )و
