### ISSUE TITLE
課金アイテム画面の「購入する」ボタンについて、視認性が低い為ドロップシャドウを付けたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#623]
https://twitter.com/umeboshikantaro/status/1141941581479415813

**Comment by ryotayama** [comment]
オレンジ色：♯f89f21
ドロップシャドウ：#000000（不透明度20%）

**Comment by arigayas** [comment]
### スクリーンショット
![resized_D9j9hyaUYAA9mFj](https://user-images.githubusercontent.com/11251874/59922596-19b23900-946c-11e9-9646-ba956eaad877.jpg)
![resized_D9j9iUEUcAAQwaV](https://user-images.githubusercontent.com/11251874/59922599-1b7bfc80-946c-11e9-8603-67de20e1d584.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.26でリリース予定٩( ᐛ )و
