### ISSUE TITLE
各画面の「戻る」ボタンについて、ハイライトしないものがある

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#625]
https://twitter.com/ryota_yama/status/1142036955556798465

**Comment by arigayas** [comment]
![resized_D9lTL_mUwAI8eSm](https://user-images.githubusercontent.com/11251874/59922753-6dbd1d80-946c-11e9-9305-819973bbedc6.jpg)
![resized_D9lTL_nUwAAIxaq](https://user-images.githubusercontent.com/11251874/59922755-6f86e100-946c-11e9-8f45-2915e9181f6d.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.26でリリース予定٩( ᐛ )و
