### ISSUE TITLE
エフェクトの詳細画面への切り替えについて、横スライドで画面が切り替わるようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#627]
エフェクトの詳細画面への切り替えについて、横スライドで画面が切り替わるようにします٩( ᐛ )و

関連Issue: #622 #626

**Comment by arigayas** [comment]
issueタイトルとラベルが不一致ですが、どういう事でしょうか？

**Comment by arigayas** [comment]
間違えていたということなので修正しました。

**Comment by ryotayama** [comment]
対応した！　バージョン3.26でリリース予定٩( ᐛ )و
