### ISSUE TITLE
「レビュー投稿」メニューから直接レビューのページに飛ばすようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#628]
https://twitter.com/atagon/status/1143037115908816897

**Comment by arigayas** [comment]
教えてくれた情報：

【Swift】AppStoreのレビューフォームを開くパラメーターが新登場 - action=write-review - - Qiita 
https://qiita.com/mshrwtnb/items/8fd60ba3a8bc89f3c013


ハヤえもんってSwiftで書いているんですか？

**Comment by ryotayama** [comment]
ありさん、ありがとー！
SwiftじゃなくてObjective-Cだけど、今回のケースはどっちでも変わらないはず！٩( ᐛ )و

**Comment by ryotayama** [comment]
対応した！　バージョン3.27でリリース予定٩( ᐛ )و
