### ISSUE TITLE
速度1000%(10倍速) 機能が欲しい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#63]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/65

2017.11.14
https://twitter.com/ryota_yama/status/930407427417108480

Windows版には実装済み。
iPhone版とAndroid版の速度機能。

**Comment by ryotayama** [comment]
https://twitter.com/s9990110u/status/1081929896656400384
いきなり夜遅くにすいません。はやえもんでの機能要望なのですが。
課金機能でもなんでもいいので再生速度を8倍速まで速くすることはできないでしょうか。

はじめまして٩( ᐛ )و
おぉ、８倍速……！
iOS版ですか？？

はじめまして(ФωФ)
はい。iOS版ですね。パソコン版もありましたよね？たしか持っているのですが速読術のトレーニングで自分の音読を録音して再生して目で追うのですがケータイの方が便利なのでもしできたら欲しいなと思いまして(・ω・｀)

了解です、ちょっと考えてみますね！
実装までの間は、「アプリ内に保存」という機能があるので、４倍速で書き出して、また４倍速にするって方法で対処くださいませ٩( ᐛ )و

**Comment by ryotayama** [comment]
これ音程の#12以上と同じ形式（グラフ外で表現）で実装しよーかな٩( ᐛ )و

**Comment by ryotayama** [comment]
@UmeboshiKantaro これむしろオプション画面で速度の上限／下限、音程の上限／下限を設定できた方がシンプルかなぁ？？

**Comment by KanzakiSaki** [comment]
上限を設定できることのメリットってなんだろう？？って考えてみたんだけど
使う範囲が狭い場合に、グラフで可視化しやすくなるってところなのかなーやっぱ？？🤔

**Comment by ryotayama** [comment]
うんうん、そうだねー！
あれ、そう考えると上限／下限はシステム的に可能な限界まではじめからできるようにしとけば良くって、オプションで「グラフの表示エリアをカスタマイズ」できるようにした方が分かりやすい……？？

**Comment by ryotayama** [comment]
@UmeboshiKantaro うめちゃん、これ時間ある時に意見聞かせてほしいなー٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
ごめん、オプション画面のイメージが湧かなくて保留してたわ💦
方向性としてはいいと思う！👍
1段階目としてはオプション抜きで、音程と同じくグラフ外で表現する方向のがいいとおもうけどどうかな？？

**Comment by ryotayama** [comment]
おっけー、ありがとう！
それではこのIssueでは、「グラフ外で速度1000%まで設定できるようにする」ってとこまでを対象に対応を進める事にするね٩( ᐛ )و

**Comment by KanzakiSaki** [comment]
了解です！
なんかたまに要望くるもんねこれ！
「数値入力か速ボタンのタップで可能になりました！」ってアナウンスできるしいいと思う！👍

**Comment by ryotayama** [comment]
対応しました！　バージョン3.01でリリース予定٩( ᐛ )و
