### ISSUE TITLE
左メニューについて、VoiceOver環境で各メニューがボタンになっている事が分からない為、「ボタン」と読み上げるようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#631]
https://twitter.com/nuiyzq5ohvzyue0/status/1143648845944934400

**Comment by arigayas** [comment]
#617 重複かな？と思ったら、他にも対応して欲しいって事なんですね。

**Comment by ryotayama** [comment]
対応した！　バージョン3.27でリリース予定٩( ᐛ )و
