### ISSUE TITLE
新規インストールの際は課金アイテムメニューの隣に未読数が表示されないようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#658]
https://twitter.com/umeboshikantaro/status/1148239915936653316

**Comment by arigayas** [comment]
### うめさんによるスクリーンショット
![resized_D-9eHTDU8AAilSX](https://user-images.githubusercontent.com/11251874/61095548-d5c0bb80-a48e-11e9-9673-321084b668a0.jpg)

**Comment by ryotayama** [comment]
対応した！　バージョン3.29でリリース予定٩( ᐛ )و
