### ISSUE TITLE
課金アイテム画面の「購入済み」ボタンについてテキストのドロップシャドウが表示されないようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#659]
https://twitter.com/ryota_yama/status/1146622826482290688

**Comment by arigayas** [comment]
### とあるユーザーさんによるスクリーンショット
![resized_D-mEBgYVAAAmVx4](https://user-images.githubusercontent.com/11251874/61095616-23d5bf00-a48f-11e9-90bb-fc5d9196a5e5.jpg)

**Comment by ryotayama** [comment]
対応済みなので、クローズします٩( ᐛ )و
