### ISSUE TITLE
再生画面に今何分何秒なのかの表記がほしい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#66]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/73

2017.12.01
Webページリニューアルスタッフ間のチャットより。

**Comment by ryotayama** [comment]
ループ画面に「再生位置」項目を追加した他、バージョン2.91で追加した再生中画面でも再生位置がわかるようにしましたので、Closeします٩( ᐛ )و
