### ISSUE TITLE
エフェクトのテンプレート画面で並べ替え中にテンプレートごとの「・・・」ボタンが非表示になっていない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#660]
https://twitter.com/ryota_yama/status/1148985995028598784

**Comment by arigayas** [comment]
### 良太さんによるスクリーンショット
![resized_D_IEqtxUEAEfC8e](https://user-images.githubusercontent.com/11251874/61095724-92b31800-a48f-11e9-9eb0-9514b6359ce3.jpg)

**Comment by ryotayama** [comment]
直した！　バージョン3.29でリリース予定٩( ᐛ )و
