### ISSUE TITLE
iPhone X系の端末でイコライザ画面の並べ替え中に一番下までスクロールできない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#661]
https://twitter.com/ryota_yama/status/1148995261206650880

**Comment by arigayas** [comment]
### 良太さんによるスクリーンショット
![resized_D_INGSGUwAA4DwF 1](https://user-images.githubusercontent.com/11251874/61095821-f4738200-a48f-11e9-9a87-667ada6c6d80.jpg)

**Comment by ryotayama** [comment]
直した！　バージョン3.29でリリース予定٩( ᐛ )و
