### ISSUE TITLE
再生リストタブの余白がおかしくなるケースがある

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#688]
https://twitter.com/chiimasuxu/status/1157502482374782976?s=20
ハヤえもんの起動直後のここちょっときになったりすんだよね
![EBBGXmsUIAE1aTu](https://user-images.githubusercontent.com/6075785/62408102-01eada80-b5fe-11e9-9413-b5afc75661d3.jpeg)

**Comment by arigayas** [comment]
一応確認です。
本来ならタブの間隔は少し空いているのが正しいんですよね？

**Comment by ryotayama** [comment]
ありさん、そうだよー！

**Comment by ryotayama** [comment]
対応した！　バージョン3.33でリリース予定٩( ᐛ )و

**Comment by arigayas** [comment]
> ありさん、そうだよー！
了解しました。
