### ISSUE TITLE
ノーマライズ機能が欲しい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#69]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/78

2017.12.04
https://twitter.com/kengo1228/status/937470402242027520
「ノーマライズ機能はよ。昔の音楽とかバランス取れない(笑)」

https://twitter.com/mizoshita_yuya/status/937512802700242944
「コンプ/リミッターかけられても面白いかもしれない...」

2017年12月4日現在：
iOS バージョン  1.97
Android バージョン 1.06

**Comment by ryotayama** [comment]
対応しました！　ver.2.82でリリース予定です٩( ᐛ )و
