### ISSUE TITLE
ダークモード時「タイトルとアーティスト名を変更」ダイアログの配色がおかしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/hayaemon_ios_issues#737]
iOS 3.36 iOS 9.3.5 iPad3,1
iOSのダイアログの色と文字色、これが仕様でしょうか?
https://twitter.com/cranberry_talks/status/1172116307958829056
![EEQxkHwUcAAyY1m](https://user-images.githubusercontent.com/50232313/71779972-b0f16f00-2fff-11ea-81b7-eebd206335a7.jpg)
↓
うぉー、まさかのこれと逆パターン……！
　https://twitter.com/ryota_yama/status/1171777057681887232
https://twitter.com/ryota_yama/status/1172116971409702912

**Comment by ny-yamana** [comment]
iOS3.53時点で直っています。
元の報告
https://twitter.com/ryota_yama/status/1171777057681887232
が、どうなったのかは不明。
https://twitter.com/cranberry_talks/status/1213796536640888832

**Comment by ryotayama** [comment]
@aafxaa クランベリーさん、ありがとー！🙏
対応済みなので、Closeします！
