### ISSUE TITLE
iPod touch 5thの環境でランダム再生にしようとすると５秒ぐらいフリーズするのを直してほしい。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#75]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/85

2017.12.10
LINE@にて頂いた要望です。

**Comment by ryotayama** [comment]
対応しました！　バージョン2.99でリリース予定٩( ᐛ )و
