### ISSUE TITLE
開始タイマー（カウントダウン）機能がほしい

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/hayaemon_ios_issues#756]
関連issue #522 

https://twitter.com/umeboshikantaro/status/1226086325436051456?s=21
ハヤえもん
前にセルフタイマー的な機能があると練習しやすい、というのを見かけたのでオプション設定画面につけてみた
秒数は10くらいまであればいいのだろうか

![セルフタイマー](https://user-images.githubusercontent.com/32741225/74094711-15d14500-4b29-11ea-9d3b-d0c8caf523be.png)

おぉ、ありがとー！🙏
ここで設定しとくと、再生／録音時にカウントダウン的なのが画面に出る感じかな？？

https://twitter.com/umeboshikantaro/status/1226092099549810689?s=21
カウントダウンは画面中央にうっすら出るといいかな？
これはLINEカメラのセルフタイマーだけどわかりやすいなーと
（動画あり）

おぉ、いいねいいね！👏
ハヤえもんだとライトモード時は黒、ダークモード時は白で画面中央に出す感じかな？？

そうだね！
それか両方とも白にドロップシャドウでもいいかも？黒だと強すぎかも…？

おぉ、ありがとー！🙏
また実装したら見せるね！👍

うんうん！ありがとうヾ(｡･ω･｡)ﾉ
いつも思いつきでごめん😅

めっちゃ嬉しいよー！　いつもありがとう😊

かなり前に、メトロノームで何カウント後に再生、というのもあったので、それも同時に考えたかったのだけど難しかった💦

うんうん、この形良いと思う！👍
いずれ「カウントダウン時に音が鳴るようにしてください」ってリクエストがきそう！

あーー視覚だけじゃなくてね！それいいなぁ、、！
画面に音のオンオフの項目を増やすよりは、マナーモードにしとけば鳴らない、みたいな感じでいいのかしら。。

マナーモードだと裏技っぽいかなぁ？（そもそも音楽再生アプリだから、マナーモードのオンオフによって機能が変わるというのが伝わりづらそう）
音が鳴るようにしちゃって要望が多かったらオフにする機能を考えるって感じでいいような気もするけどどーだろね？🤔
（とはいえ、初期段階では視覚のみ）

確かに確かに、、！
てかカメラアプリのセルフタイマーも音なるやつ見た事ないかも〜！
ちなみにアップル純正のカメラは1秒毎にフラッシュがピカピカするｗ
最初は音なしでいいと思う👍

フラッシュはだいぶ斬新だなー、でも遠くからみても分かるようにって趣旨なのかなー💡
うんうん、実装的にもいきなり音ありはハードル高いから、まずは文字だけで👍

フラッシュだいぶビックリしたｗ
こんな感じかな、再生中バー出た状態でカウント数字が出るとわかりやすいかも！
数字の色はライトモードもダークモードも白の50％にしてみた！共通で使えるならその方が実装が楽かなーと

![セルフタイマーカウントライト](https://user-images.githubusercontent.com/32741225/74094749-a740b700-4b29-11ea-8efe-6afb25b89521.png)

![セルフタイマーカウントダーク](https://user-images.githubusercontent.com/32741225/74094751-ae67c500-4b29-11ea-8b69-7436235fceca.png)

おっけー、ありがとー！👍👍

**Comment by ryotayama** [comment]
https://github.com/ryotayama/Hayaemon/issues/453
↑からの移行

https://twitter.com/moonsky1001/status/1027713423797190656
3カウントいれてから音楽再生できるようにできないですか！！！！

kengo1228 commented on 10 Aug 2018
3カウントって
1、2、3、ハイ、ドーン
のことなのか
1、2、3、ドーン
のことなのかどっちなんだろう。

ryotayama commented on 10 Aug 2018
３拍子なら１、２、３、ドーンだし、４拍子なら１、２、３、４、ドーンだしって感じで、３に対する強いこだわりがあるわけじゃないんじゃないかな、きっと。
ただこれ、曲の冒頭に空白があったりするし、開始位置の認識が難しいよね。

ryutaro commented on 10 Aug 2018
iTunesがギャップレス再生用のメタデータ持ってませんでしたっけ？

UmeboshiKantaro commented on 11 Aug 2018
過去にも同様の要望のやり取りがありますので掲載しますφ(･ω･｡)
（鍵垢さんなので現在ツイートのURLを取得できません💦わかりにくくて申し訳ないです🙏）

楽器演奏者としては曲の前にカウント入れれるようになったら自分にとって最強のアプリになる...
そのタイミングも微調整とかもできたら尚嬉しいです...

なるほどー！　ありがとうございます！　検討してみますね٩( ᐛ )و

私はドラムやってるんですが音楽に合わせて練習する時、ドラムから始まる曲になるとどうしても最初合わせることが難しかったんですよね...
期待して待ってます( ´ ▽ ` )

なるほどー。練習時に入りにくいんですね！　とは言え、自動テンポ解析は結構難易度高いんで、手動で……ってなるとうーん。悩ましいですね！　インターフェース勝負だなぁ。いかに分かりやすくその機能を画面に組み込めるか……。やりたいことはすごく良く理解できました！٩( ᐛ )و

私はBPMは各自で測定する感じで大丈夫だと思います(BPM解析はハイレベルすぎる笑)
曲の頭に空白がある曲があるので0.1秒単位で曲にカウントを食い込ませる(？)ことができれば理想です...

とりあえず考えてみました！
メトロノームのデザインはGoogleで検索したやつほぼそのままです笑
かゆいところに手が届くといいのですが…。

![Image](https://i.imgur.com/EMPZJab.jpg)

ほとんどこれで大丈夫だと思います！
ですが、曲の頭にほんの少しでも空白が入ると再生前のカウント数が調節できても必ず曲の0:00からカウントが始まるならズレてしまうのでは？と思います...
なので空白をトリミングorカウントを後ろにズラすように微調整できる機能が必要だと感じます

曲頭の空白をなくせば解決するので調節機能をつけるよりカットの方がシンプルで良いかもしれませんね
途中スタートでカウントは一時停止から再生時にカウントを入れられるようにすれば良いし

現在、ABループを保存する機能がないんですよねー。
曲名長押しオプションメニューの「エフェクトの設定状態を保持」のところでABループも保存できれば…
Aの位置を空白後に設置し、そこから再生で解決できるかと思います…(*･ω･)ﾉ違うかな？

あってる！

それで問題ないと思います！

ほんとですね！気づきませんでした
それならメトロノームのズレの問題はもう解決ですね

UmeboshiKantaro commented on 11 Aug 2018
当時の提案では、曲名長押しによるメニューでしたが、現在だと「…」のアクションシート内に「nカウント後に再生」という項目を設ける感じになると思います。

そして #182 に上がっている歯車アイコンの設定画面にて、ユーザー側で何カウントかを設定できるようにするのがいいと思われます。（デフォルト値は要検討）

曲の前にある空白については、現状だとABループを設定した状態で「保存／エクスポート」をすることによって実現できるかと思います。

他にいい案がありましたらコメントお願いいたします(´人･ω･｡)

ryutaro commented on 13 Aug 2018
無音部分はプログラム的にかなりの精度で探せると思うので曲追加時に解析してそれをデフォルト値として使い
最大で1拍分動かせたら事足りるかなと思います

拍のデフォルトは4/4が基本(?)だと思うので4が妥当かなと思うのですが、あまり詳しくないので広く意見を聞きたいですね

**Comment by KanzakiSaki** [comment]
https://mobile.twitter.com/ryota_yama/status/1137130258853838849
曲を再生する際、再生を少し遅らせることは出来ますか？
曲によって、すぐに再生される曲もあります。
ベース練習に使わせていただいていますが、再生をスタートして 3秒程度遅らせる事が出来れば助かります。

関連issue #156

**Comment by ryotayama** [comment]
https://twitter.com/ryota_yama/status/1226370028485791746?s=20
↓ちなみに「セルフタイマー」ってところは「カウントダウン」とかの方が良かったりするかなぁ？？考えている顔

おぉーありがとう！
カウントダウンカウントダウンって何回も並んじゃうのもあれかな？と思ったのと、カメラ用語として馴染み深いかなと思って付けてみたよ。
個人的にはどちらでも大丈夫かなOKサインの女性
それが他に言い回しがあれば…

ふむふむ、なるほどね書いている手
特殊な用語を使うと多言語化する時に難しそうなのと、個人的には「セルフタイマー」の語源が被写体を表してるのがちょっと気になるかなぁ…！

↓こういう感じだとどうだろう？？
＜カウントダウン＞
・再生時：３秒
・録音時：５秒

なるほどね！じゃあセルフタイマーやめよう！
カウントタイマーとかはどうだろう？分かりにくいかな？？

＜カウントタイマー＞
再生カウントダウン　n秒 or なし
録音カウントダウン　n秒 or なし

りょーたさんのやつもいい感じ！！

ありがとー！握った手
うめちゃんのやつもいいねイイね

今回はなんとなくパッと見認識しやすそうな↓こっちでも良いかなぁ？？
＜カウントダウン＞
・再生時　n秒 or なし
・録音時　n秒 or なし

ありがとう！じゃあそれでやってみて、またいい感じの文言が出てきたらその時に差し替えようか！ヾ(｡･ω･｡)ﾉ

ありがとー、あっ、でもカウントダウンの文字がかなりちっちゃいんだよな。。

https://twitter.com/PCnohito/status/1226377806486990849?s=20
これも総合的に踏まえると、こうかな？？

＜タイマー＞
再生カウントダウン　n秒 or なし
録音カウントダウン　n秒 or なし

おお！！
そしたら〈開始タイマー〉とか〈スタートタイマー〉というのもありかな？？

なんか終了タイマーもこの下に入れられそうな気がしてきた、、
![EQT9Cj4U8AETIe0](https://user-images.githubusercontent.com/6075785/78847051-a86a6380-7a48-11ea-9649-e0b9a73d1687.jpeg)

えっ、終了タイマーってそもそも何だっけ…？？

スリープタイマーのことかな？結構要望が来てたと思う…！

おぉ、左メニューをやめてオプション設定画面に入れちゃえって話か…！電球

そうそう、そこに画面をつけようとしてたんだけど、結構煩雑で汗マーク
オプション設定画面なら、項目を増やせばいい（もう一個下の階層は作らなきゃだけど）って考えて…そっちの方が、楽に実装できるかなぁと。。
ユーザーさん的には、左メニューからクイックアクセスできた方が便利かとは思うんだけどね口を開けて冷や汗をかいた笑顔

そっかそっか！電球
確かに手っ取り早く実装できそう！
まさかそっちまで話が広がるとは思わなくてビックリしたけど、そしたらこれで行こうか！イイね

＜開始タイマー＞
再生カウントダウン　n秒 or なし
録音カウントダウン　n秒 or なし

私も最初の時点では考えてなかった口を開けて冷や汗をかいた笑顔
でもタイマーって単語が出てきて、あれ、開始じゃなくて終わる方のタイマーは…？って考えが出てきちゃって汗マーク

色々考えてくれてありがとう！それでいいと思う〜拍手

わーい、ありがとー！٩( ᐛ )و

**Comment by ryotayama** [comment]
https://twitter.com/haratamapapa/status/1259397375916793861?s=20
そういやハヤえもんで唯一不満があるところとしては、曲の頭にカウント入れられないこと。タップとかで簡単にハット4回刻めたら最強なんだけどなーって思いながら毎回曲開始数秒前から再生して頭ミスって再度再生・・・頭ミスって・・・を繰り返すんだよなぁ。

**Comment by ryotayama** [comment]
対応した！　バージョン3.89でリリース予定！

**Comment by ryotayama** [comment]
https://twitter.com/KAZUAKI_virgiL/status/1292012085493166084
これは控えめに言っても神アプデでは⸜( ॑꒳ ॑  )⸝

**Comment by ryotayama** [comment]
https://twitter.com/Macchan1046/status/1292304837174951936
あっコレ欲しかった機能です！
ありがとうございます😊

**Comment by ryotayama** [comment]
https://twitter.com/guitarloveYu/status/1292289316853395456
最高の機能をありがとうございますキラキラキラキラキラキラ

**Comment by ryotayama** [comment]
https://twitter.com/tryfld418/status/1292309415920451584
とても便利な機能赤いビックリマーク

**Comment by ryotayama** [comment]
https://twitter.com/ksT3ZayMvsjZCRB/status/1292657126582546433
開始タイマー機能きました！　楽しみです!!マーク(*^▽^*)
