### ISSUE TITLE
Dropboxからの追加時、拡張子がwmaの再生できないファイルが読み込めないようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#759]
https://twitter.com/ryota_yama/status/1227884392699154432?s=20
新たにハヤえもんiOS版を試してくれた人からDMをもらってて、ユーザーサポートしてるんだけど、「Dropboxからの追加画面でWMA形式が選べるのに、実際には再生できない」という報告をもらって確認したらほんとだった！
いやー、ありがたい……！
選べないように直しておこーっと！

**Comment by ryotayama** [comment]
対応した！　バージョン3.62でリリース予定！

**Comment by arigayas** [comment]
ふと思ったのですが、wmaの再生できないファイルをもう取り込み済みの場合、データは削除されるのでしょうか？

**Comment by ryotayama** [comment]
消えない！　ユーザーさんに個別削除してもらう必要があるよ💡

**Comment by arigayas** [comment]
なるほど。

思いつきですが、
wmaの再生できないファイルをリストアップする機能があると便利そうと思いました。

**Comment by ryotayama** [comment]
まぁ一過性のものだし、そこに体力かけるのはやめとくよ！
ありがとー！🙏

**Comment by arigayas** [comment]
ですよねw
