### ISSUE TITLE
イコライザのインポート機能/エクスポート機能が欲しい。可能なら共有機能も。

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/hayaemon_ios_issues#82]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/93

2017.12.22
https://twitter.com/ryota_yama/status/943981910295953408
『そういう意味ではイコライザのインポートエクスポート機能をつけたいよね。「こんなイコライザ考えたんだけど良くない？」「なにこれすげー！」みたいなコミュニケーションが生まれるといいよね。』

https://twitter.com/Risowa19/status/943983695844728832
『イコライザのインポートエクスポート機能 とか良いなぁ…』

https://twitter.com/ryota_yama/status/916579135392063489
『ついでにエフェクトとかコントロール系もエクスポート／インポート機能をつけようかと……！』

https://twitter.com/ryota_yama/status/916581327834464256
『URLにしよーかと思ってるんですよね。
http://hayaemon.jp/equalizer/hFjnCsH … みたいな（未実装）
そこにアクセスすると自動的にハヤえもんにインポートさせるようにしようかと思ってます』

2018.08。24
#12 
に引っ越したのでcloseします！

**Comment by arigayas** [comment]
@guxtuti-raven これって#12の重複issueじゃない？

**Comment by yuri-regulus-25** [comment]
重複してました！
してたのでこっち側をCloseします
