### ISSUE TITLE
アイコンのクレジットを追加

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/hayaemon_ios_issues#823]

**Comment by ryotayama** [comment]
App Storeの概要欄にクレジットを追加します。
icons by icons8
https://icons8.com

**Comment by KanzakiSaki** [comment]
https://feathericons.com/

**Comment by KanzakiSaki** [comment]
MITライセンスの条件

MITライセンスを利用する場合、利用条件というものがあります。MITライセンスの利用条件は、著作権の表示とMITライセンスにおける条文の記載の2つです。なお、MITライセンスの条文を記述する代わりに、MITライセンスの条文が記載されているWebサイトのURLを載せることで対応することも公認されています。

そのため、ユーザーにとって使いやすいライセンスといえます。また、Webサイトに著作権の表示とMITライセンスの条文を記載し、URLを1つのファイルとして掲載するという方法も可能です。条文の日本語訳URLは以下の通りです。

【参考】：[The MIT License](https://licenses.opensource.jp/MIT/MIT.html)

**Comment by ryotayama** [comment]
Copyright (c) 2023 feather
Released under the MIT license
https://github.com/feathericons/feather/blob/master/LICENSE

**Comment by ryotayama** [comment]
↑をApp Storeの説明文に追記します！
